### ISSUE TITLE
Internationalize App Strings

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/MentorApp#1]
**Context**
Localisation for the app is setup using`i18n-js` for translations and `react-native-languages` for detecting the current locale of the device.

There is a `locales` json from the web app as a reference.

**ToDo:**
replace the strings in the app with the translated strings

**e.g.**
`<label>Username</label>` should be replaced with to
`<label>{i18n.t('login.username')}</label>`

**Comment by pA1nD** [comment]
Tracking now in #89
