### ISSUE TITLE
(BUG) [ MentorApp V1.9.15]  App crash  when i try to open the Application

### ISSUE THREAD

**Issue by XAMIR555** [FundacionParaguaya/MentorApp#1004]
#### Project Information
* Repository-----------:[Here](https://github.com/FundacionParaguaya/MentorApp)
* Project Name---------:  [Stoplight Mobile](https://play.google.com/store/apps/details?id=com.povertystoplightapp)
* Publisher------------: [Poverty Stoplight ](https://github.com/FundacionParaguaya)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

when I open the application after downloading it, the application will open and all its options will be displayed which I can easily use.

#### Actual behavior
Application cannot open App crash  when i try to open the Application

#### How to reproduce
* Download the latest version of Application
* After installing, try to open the app
* Note the Bug

* Browser/App version-: V1.9.15
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190729_160415](https://user-images.githubusercontent.com/49812927/62044746-8aa9e680-b1b8-11e9-8659-1e6912f12a9b.gif)

# Logcat

<pre><code>07-29 16:00:35.215 11737 11766 E AndroidRuntime: FATAL EXCEPTION: create_react_context
07-29 16:00:35.215 11737 11766 E AndroidRuntime: Process: com.povertystoplightapp, PID: 11737
07-29 16:00:35.215 11737 11766 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
07-29 16:00:35.215 11737 11766 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: FATAL EXCEPTION: create_react_context
07-29 16:00:37.579 11830 11853 E AndroidRuntime: Process: com.povertystoplightapp, PID: 11830
07-29 16:00:37.579 11830 11853 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
07-29 16:00:37.579 11830 11853 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: FATAL EXCEPTION: create_react_context
07-29 16:00:59.304 12836 12865 E AndroidRuntime: Process: com.povertystoplightapp, PID: 12836
07-29 16:00:59.304 12836 12865 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
07-29 16:00:59.304 12836 12865 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
</code></pre>

**Comment by Danman7** [comment]
This issue is fixed. No idea who XAMIR555 is. Looks like some bot.
