### ISSUE TITLE
Draft does not save priorities if I exit in lifemap Priorities screen

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#1005]
Connection: Online and offline
Environment: Testing
Version: 1.10.0rc2
User: t/demo
Survey: Any survey

Steps to reproduce:
1. I take any survey
2. I continue to the end of the survey
3. I'm in the lifemap screen to create priorities
4. I make some priorities
5. Then, I do not click on continue, I click on the X to exit and save a draft
6. I see the draft and click on it to continue the draft
7. I see the screen to resume a draft, click on it
8. Takes me to the lifemap priorities screen, without any priorities taken. 
So, I had to make the priorities again.

**Comment by pA1nD** [comment]
We assume this will be fixed by #958

**Comment by Danman7** [comment]
Yes it will.
