### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#1013]
Native Back Button behaves strange.

**Reported by Ana**

*a.* When in the middle of the stoplight indicators section, I click the back button, the first time it takes me to the previous stoplight indicator. And the second time I click on the back button it takes me to the "choose a survey" screen. - offline.
*b*. When in the screen "This Life Map has 29 questions..." I click the back button, it looks like it refreshes and keeps taking me to that screen. Actually it takes me back to wherever screen I was in - Online and Offline - Banco Solidario
*c*. When in the middle of Stoplight indicators, I clicked the back button and it took me back to "This Life Map has 29 questions..", then I clicked on Continue and I did not see which indicators I had chosen before - Offline - Banco Solidario (edited) 

We assume this will be fixed by #958

**Comment by Danman7** [comment]
This will be fixed by #958
