### ISSUE TITLE
Map download errors 

### ISSUE THREAD

**Issue by vasildimitroffhristoff** [FundacionParaguaya/MentorApp#1014]
There are several bugs related to map downloading in the Sentry : 

Timeout
https://sentry.io/organizations/poverty-stoplight/issues/1121823298/events/7883f0e224f64742be823c39af588850/?project=1332316&statsPeriod=14d

SSL handshake
https://sentry.io/organizations/poverty-stoplight/issues/1121823298/events/4b39433aaf3f4b47bc76c6b9b47abed6/?project=1332316&statsPeriod=14d

Unable to resolve host "api.mapbox.com": No address associated with hostname: 
https://sentry.io/organizations/poverty-stoplight/issues/1121823298/events/137982939f234d40841d7ee2157dd95b/?project=1332316&statsPeriod=14d

**Comment by pA1nD** [comment]
We could analyze via Test Fairy, that those errors seem not to cause any trouble as the package is handelling them in an appropriate way. We should build in a feature that ignores specifically these errors and still sends the other issues.

**Comment by zommerberg** [comment]
not reproducible anymore.
