### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#1016]
We received two Sync errors via Sentry:

https://sentry.io/organizations/poverty-stoplight/issues/812022016
https://sentry.io/organizations/poverty-stoplight/issues/812022016/events/875cbb6546214cfa9c61513b60ef7849

**Comment by Danman7** [comment]
No new events for 3 weeks. This has been set as fixed in next release. If new errors show, we will properly mark them in bugsnag.
