### ISSUE TITLE
App crashes on Location Permisions request on reviewing Family screen

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#1037]
If the app is reinstalled or installed anew and the user hasn't give location permission and isn't prompted for it the app would crash. The above requirements are fairly rare (someone to completely re-install the app) that's why we haven't seen error reports of this.

A while ago we fixed the same issue for the location screen, but now it happens in the family review screen on brand new installations

**To Reproduce**
1. Clear app data
2. Enter app
3. Login and navigate to Families/Any family with saved location
4. See a crash error

**Expected behavior**
Map would just show above the family details

**Comment by vasildimitroffhristoff** [comment]
This is solved in #958
