### ISSUE TITLE
Priority in excel download: Client already waiting for 1 week

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#104]
> As a HUB user &amp; and as an ORGANISATION user<br>I want to<br>download a csv file that denotes which indicators have been prioritised<br>so that I can<br>create reports detailing most often prioritised indicators to allow for organisational planning on most needed solutions.

**Link:** [Conversation with sprendeville@gmail.com](https://app.intercom.com/a/apps/msjjl81s/respond/inbox/all/conversations/19782762924)

**Customer:** [sprendeville@gmail.com](https://app.intercom.com/a/apps/msjjl81s/users/5bfbdc37bfcbfcff30d86d2c/all-conversations)
**Customer ID:** 57dc7de4-e6ab-447b-836e-c746ec91d728
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/msjjl81s/respond/inbox/all/conversations/19782762924) when this issue is closed.

**Comment by Danman7** [comment]
Is this for the web app? This is the first time I hear of such a feature since the beginning of the whole process.

**Comment by pA1nD** [comment]
@Danman7 this is completely irrelevant. It goes into another place.
