### ISSUE TITLE
When retaking a life map, use endpoint that retrieves the latest version of the survey.

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/MentorApp#1042]
When retaking a life map, there's no way to know if the SurveyID referenced belongs to the newest version of the survey.
Use the endpoint that expects any `surveyID` and retrieves the definition of the latest version.

**Comment by Danman7** [comment]
@javierpf I need a bit more context for this task. If we get the latest definition, why would we need to know whether it belongs to the latest? And we would know which definition it belongs to since we save it with the definition.

**Comment by javierpf** [comment]
Closing this ticket, use case not relevant for the mentor-app
