### ISSUE TITLE
Socioeconomic answer (checkbox) not saved - Chortitzer survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#1068]
Environment: Production
Survey: Chortitzer
Question type: checkbox AND required
Device: tablets and smartphones

---
**Problem:**
---

Two weeks ago, Chortitzer mentors took 100 surveys in tablets and smartphones, they downloaded their report today and saw that one of the columns are completely empty, there is no information saved on "Situacion de Vivienda". 

![situacion.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f05c44c1-0ef2-47d6-84d0-05317cabc025)

Reproducing the error:
---
I reproduced the error in the demo environment with a tablet, and I cannot see the information in the reports. However, I took a survey in the web platform, and I do see the information.

**Comment by Danman7** [comment]
We cannot reproduce this issue on the given survey or any survey with checkboxes. It seems it wasn't properly tested.
