### ISSUE TITLE
Edit option visible in family profile

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#1069]
Environment: demo and production
Survey: Not applicable
Where: Family profile

Problem
---
When I go to a family profile choosing from the family list, if I go to a socioeconomic section, I can see that I have the option to change an answer. So, I tried to change an answer and the app crashed. 
(This happens only with socioeconomic questions)

Solution
---
Disable the possibility to edit a family profile.

**Tech health channel**
BugsnagAPP [15:50]
*Event* in *production* from Stoplight Mobile in index.android.bundle:946 (details)

**Comment by stacylorraineprendeville** [comment]
There is no EDIT option in the retrospective views.
This should be super clear to EVERYONE on the team! @aprojas @Danman7

**Comment by Danman7** [comment]
I went trough ~30 families from various surveys having all sorts of answers - checkboxes, radio buttons, whatever. I could not find any way to edit anything.

@aprojas Could you provide further feedback? Which account, which family, which socio economic screen?

**Comment by aprojas** [comment]
@Danman7 
I tried it again and it happened. It happened with my t/nelixiademo account and now t/ana_comunidad. 
Families: 
Ana Rojas
Ana Rural

Try changing any answer in the socioeconomic screen

**Comment by Danman7** [comment]
Related to crash after terms issue from the other day. Adjusting estimate.

**Comment by Danman7** [comment]
Closing after confirming it works on actual in-store app.
