### ISSUE TITLE
Image caching crash - `Could not invoke RNFetchBlob.fetchBlob`

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#1088]
This continues #631 as it seems we still have issues with this. Related reports: https://povertystoplight.testfairy.com/projects/6819694/builds/8971333/sessions/4433668153, https://app.bugsnag.com/penguin-digital/stoplight-mobile/errors/5d4c72e3dd1a360019b69e94?filters[event.since][0]=30d&filters[error.status][0]=open

This is an old issue we have tried several approaches to solving. The device reports at least 1.8GB of free space on both device and sd, so this is not the issue.

**Comment by zommerberg** [comment]
currently we are using rn-fetch-blob  0.10.16 with react-native 0.59.10 which is not unsupported.
@Danman7 
This could be one of the reasons why we get the error, but i will try to actually reproduce it.

<img width="916" alt="Screenshot 2019-09-17 at 10 41 36" src="https://user-images.githubusercontent.com/43446836/65021757-65c02d00-d938-11e9-9b6c-e78f80a7c9c9.png">

**Comment by zommerberg** [comment]
according to my research the bug is happening only on t/demo from the same user.

look at the 5 errors ,they are all on t/demo, but the same device can log in without any problems with other username.

https://povertystoplight.testfairy.com/search/?filters=W3sidHlwZSI6ImRhdGUiLCJhdHRyaWJ1dGUiOiJyZWNvcmRlZF9hdCIsImNvbXBhcmlzb24iOiJndCIsInZhbHVlIjoibm93LTMwZC9kIn0seyJ0eXBlIjoic3RyaW5nIiwiYXR0cmlidXRlIjoiaXAiLCJjb21wYXJpc29uIjoiZXEiLCJ2YWx1ZSI6IjE4MS4xMjYuMTU4LjQzIn1d

**Comment by zommerberg** [comment]
We have 2139 images on t/demo , while on other accounts we have < 200
The testfairy tells us how much free space the SD has ,not the internal storage.

I have created a new device with the emulator that has 300mb internal storage and 512 sd space.

After trying to download the maps they were stuck on 63% on t/demo , i believe that this is directly related to the bug that Ana was experiencing where the maps would stuck downloading.
The maps are being downloaded on the internal storage and not on the SD.
<img width="1321" alt="Screenshot 2019-09-17 at 12 51 18" src="https://user-images.githubusercontent.com/43446836/65031403-df144b80-d949-11e9-9b53-4ef6f5d29d27.png">

When i skipped the maps and decided to download the images only. With 300mb internal storage i installed the app and after trying to download over 2000 images on t/demo i was able to reproduce the bug, in the emulator the app does not crash, however i believe it is the same bug. It was indeed a "need more space" error. We are storing the images and the maps on the internal storage and not the SD, BUT when we are trying to log in we are checking the SD free space and not the internal storage.
<img width="1611" alt="Screenshot 2019-09-17 at 13 58 24" src="https://user-images.githubusercontent.com/43446836/65036119-64502e00-d953-11e9-9956-812096d7c3db.png">


The fix:
-Check the amount of free space on the  internal storage  and not the SD.

**Comment by Danman7** [comment]
Ana, is still having issues: https://app.bugsnag.com/penguin-digital/stoplight-mobile/errors/5d4c72e3dd1a360019b69e94?filters[event.since][0]=30d&filters[error.status][0]=open&pivot_tab=event

Based on her input and our research it looks like the issue is not disk space related.
