### ISSUE TITLE
Questions not showing options

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#1117]
Environment: production
Survey: Forestal Sylvis

I had two bugs in the socioeconomic section. 

1. When I chose the option "Propia con titulo" in socioeconomic, another question should have appeared "A nombre de quien:" and it did not appear, only when I went back to the map and then forward again to that page, it did appear.

2. The question "tiene auto o camioneta" Should display options "Si" and "no" as radio buttons, and they don't show. but it's still a mandatory question, so I can't move forward because the options are not displayed.

Screenshot:
![Screenshot_2019-09-24-10-46-33.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/59d6e75c-259a-4253-8b17-dcd5d419b1ba)

**Comment by Danman7** [comment]
@aprojas @diegotorrespy There are notable differences between the configuration of the production survey and the one we get on testing. On testing this question is a select dropdown:

<img width="383" alt="Screenshot 2019-09-25 at 10 34 56" src="https://user-images.githubusercontent.com/3336245/65579387-51a3ad80-df80-11e9-8c54-4a05f502b69a.png">

<img width="433" alt="Screenshot 2019-09-25 at 10 36 05" src="https://user-images.githubusercontent.com/3336245/65579398-56686180-df80-11e9-8449-a2ef95a4987a.png">

The question `A nombre de quien:` that is conditionally dependent on the top is not even present in the survey on testing. Unless we have the actual survey config on production, or we have access to the account you are testing it on, we can't properly debug.
