### ISSUE TITLE
Achievement roadmap is not saving in app PDF

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/MentorApp#1137]
**Describe the bug**

The achievement is not appearing when I download the PDF in the mentor app, before finishing the survey, only the priorities appear.

**Comment by aprojas** [comment]
Correction:

The achievement is not being saved in the PDF that is generated in the Mentor app, before the survey finishes. The one that is generated when clicking on the "download" button.

However, the data is being sent to the database. 

@Danman7

**Comment by aprojas** [comment]
This is ready for release.
@vasildimitroffhristoff
