### ISSUE TITLE
Testcases

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#114]
### Take a survey online

- [x] Download the app
- [x] Run the initial setup
- [x] Take a survey (or multiple)
- [x] Check if Survey has synced

### Take a survey offline

- [x] Download the app
- [x] Run the initial setup
- [x] Remove wifi and mobile data
- [x] Close app and do all kind of things to it (restart phone, ...)
- [x] Take a survey (or multiple)
- [x] Close app and do al kind of things to it (restart phone, ...)
- [x] Switch mobile data/wifi on again
- [x] Check if Survey has synced

### Check if new surveys show up in the app

- [ ] Download the app
- [ ] Run the initial setup
- [ ] Add an additional survey in the server
- [ ] Open the app and see if it shows up there

### Check if deleted surveys disappear in the app

- [ ] Download the app
- [ ] Run the initial setup
- [ ] Remove a survey in the server
- [ ] Open the app and see if it does not shows up there

**Comment by stacylorraineprendeville** [comment]
@pA1nD OK - As I understand we will not have the sync until monday - correct?

**Comment by pA1nD** [comment]
We will have sync. But not the screens. But it will sync. Talked with Iva about it today. We will use the list on the dashboard. It will show the badges (draft, pending, synced, error).

**Comment by stacylorraineprendeville** [comment]
@pA1nD ah ok - let me know when so I can test this - Also maybe we can just change that title from "Latest drafts" to something more applicable for the short term

**Comment by pA1nD** [comment]
@stacylorraineprendeville could you run through them and close this issue if everything is alright?

**Comment by stacylorraineprendeville** [comment]
@pA1nD Is the server working? Last time I checked it was down meaning I cannot test this
...also can you repost the details. Cannot find it again in slack channel

**Comment by stacylorraineprendeville** [comment]
@Danman7 This is useful? Could be in the WIKI?
