### ISSUE TITLE
Validation Error after going back to a view

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/MentorApp#1166]
## General Description
See video sending in slack for a better understanding 

If a field is focused it never validates. We can always click continue and it will allow you to save invalid snapshots

**Comment by zommerberg** [comment]
In this issue we would like to fix the validation not working when navigating directly to the next screen.

Problem (as described by the Ana)
If a field is focused it never validates. We can always click continue and it will allow you to save invalid snapshots

Solution
The validation check should be triggered one more time when clicking on the "continue button".
This way we can ensure that all of the field are completed correctly.

Approach
When clicking the "continue" button we are checking if there are any errors from the fields, and if there are then we show them. We should also check every field one more time or make the validation run every time we type in the text, the second approach will affect the performance so i assume it would be better to use the first approach.
