### ISSUE TITLE
Form dropdowns have phantom element

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#119]
**Describe the bug**
When using the pop-up modal that currently replaces the dropdown element in the forms - the first line of the dropdown is empty BUT a user can select this empty field. 
The empty field shows a rollover effect on the empty element.

**To Reproduce**
1. Go to the primary participant page
2. Tap on Gender
3. Touch on the empty space between the title and the first visable element.
4. See error/rollover effect that makes an empty selection.

This issue is present on ALL modal windows featuring a dropdown.

**Comment by pA1nD** [comment]
How should it behave? The empty field is the empty state to unselect a value.
