### ISSUE TITLE
Resume Draft View if Snapshot was skipped

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/MentorApp#1191]
Change Resume Draft View if the draft has skip all the stoplight section. Now, it shows the stoplight icons like: 

![image](https://user-images.githubusercontent.com/740232/74968506-b9f49f00-53f9-11ea-946f-eb481a421457.png)

**Comment by aprojas** [comment]
Change all texts to this:

SPANISH
Title: `Borrador`
Texto: `¡Continúa donde te habías quedado!`
Botón: `Continuar borrador`
(without Stoplight circles)

ENGLISH
Title: `Draft`
Text: `Continue where you left off!`
Button: `Continue draft`
(without Stoplight circles)

Also, please take out all the Stoplight circles
@loorely
