### ISSUE TITLE
The app is not allowing Armenian characters

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/MentorApp#1229]
## Problem
The app is not allowing Armenian characters.

![armenian_characters.jpg](https://images.zenhubusercontent.com/5c1a3b279be21e037cb696fc/a095922e-cb44-409f-be26-1af3263e73ae)

## Possible solution
Change the input validation to allow unicode characters but with the restriction of the blank spaces.

**Comment by zommerberg** [comment]
Hello, i looked into the code and it seems like the regex we have now allows only certain PG and English characters, instead we should change the regex so it works in a way where we check if the text contains invalid characters. like "_$*&#@$!" and if it does , then show the error.
