### ISSUE TITLE
Several crashes in the App when trying to finish drafts

### ISSUE THREAD

**Issue by zommerberg** [FundacionParaguaya/MentorApp#1233]
# Problem
The app crashes when the user submits the draft.
This happens because in some cases the phone code is an empty string and this is because if you click on the phone code and then click outside the phone code dropdown, it will close itself and delete the phone code in the draft , despite showing a phone code in the page, its not there. And after that we are trying to format the code right before sending it to the back end. We are using google-libphonenumber library for that, and when we pass an empty string as a phone code the app will crash.

# Solution
Don't delete the phone code when clicking outside the box and add a validation for missing phone code in the phone number formatting function that we use right before sending the draft to the back end.

**Comment by aprojas** [comment]
This is solved in the Internal Test track
