### ISSUE TITLE
Lifemap not completed loop

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#125]
**Describe the bug**
When I click the X on the "Privacy Policy" screen, I cannot create a new draft but always come back to the modeal that asks me wether I want to cancel.

**To Reproduce**
1. Go to 'Dashboard' and click "Create Lifemap"
2. Tap on "Agree"
3. On the Privacy Policy Screen tab on "X"
4. Tab on "Yes"
5. On the 'Dashboard' click "Create Lifemap" again
6. Now the modal pops up again.

**Expected behavior**
When the draft is cancelled, before ANY information is put in, don't save it.
Don't show the modal in this case.
Don't show the modal when clicking "Create Lifemap".

**Comment by Danman7** [comment]
This should have been fixed, but I saw that I haven't pushed the change. This is a tough to spot but, thanks! Expected behaviour is to actually show a different modal: https://projects.invisionapp.com/d/main#/console/15615767/332220673/preview
