### ISSUE TITLE
Is it possible to delete a local draft?

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#126]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I created 10000 drafts and don't know how to get rid of them.

**Describe the solution you'd like**
Have a way to delete a draft.

**Comment by stacylorraineprendeville** [comment]
I would prefer to wait and discuss this - The saving of a family and the saving of a draft should be two separate processes.....deleting a draft should then NOT delete a family.
So I think this needs more thoughts and some prelimanery work on saving draft and family(and it was not a request from the orgs at this point - In fact internally it was not a "desired" feature)

**Comment by Danman7** [comment]
Closing due to long time inactivity and project discontinuation.
