### ISSUE TITLE
Green check button on indicator page does not work

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#129]
**Describe the bug**
Perhaps not a bug as such more a miscommunication? 
The circular green check box was meant to be an additional "button" to select an indicator. Popular dating apps work like this its a fairly common UX approach. You can swipe the images left or right - the centre image aligns to the buttons below-----ie when red inidicator is in centre clicking the green circular button highlights the red indicator etc.

**To Reproduce**
1. Go to the lifemap indicator page
2. Click on the green circular button
3. Error - Nothing happens
-----Version 2
1. Go to a saved draft
2. Go to the indicator page
3. Error - Circular checkbox icon is not coloured with the previous choice (the previous choice is also not centre aligned) - In this way a user has no way of knowing what the previous choice of the draft was.

**Expected behavior**
- Green check button features green link colour #89BD76
-On choosing an indicator or clicking the green check button in reference to the above indicator the button would then show the colour of the selection.
- On reviewing a draft the chosen indicator would be centre screen and the check box would be coloured as per the choice.

**Screenshots**
Green Circular Checkbox
<img width="362" alt="screen shot 2018-12-06 at 13 22 18" src="https://user-images.githubusercontent.com/45012899/49597048-6617aa80-f95a-11e8-8726-37da980b0fa9.png">

**Additional context**
People are trying to click the button and do not understand why it is unresponsive.

**Comment by IvaKop** [comment]
@stacylorraineprendeville  ok, what color should the button be before click? grey?
