### ISSUE TITLE
Get privacy policy and terms from survey

### ISSUE THREAD

**Issue by IvaKop** [FundacionParaguaya/MentorApp#138]
Currently these are hardcoded, the information should come from the survey query instead.

**Comment by stacylorraineprendeville** [comment]
This now becomes more relevant with: https://github.com/FundacionParaguaya/MentorApp/issues/178
@pA1nD @IvaKop please decide how to rectify this.

**Comment by pA1nD** [comment]
Nowo tracked in #178
