### ISSUE TITLE
Unfillable Day field in Date of Birth Field in Family Participant screen

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/MentorApp#139]
**Describe the bug**
Day Field in Date of Birth Field in Family Participant Screen is unfillable ( But year is OK)

**To Reproduce**
1. Go to Family Participant Screen
2. Try to fill in date of birth, any number inputted into Day dropdown 

**Expected behavior**
I should be able to fill in a number

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Andy YEZZ 4E12
 - OS: Android Kitkat
 - Version 4.4.2

See video (unfortunately scaled wrongly when converting to gif)

![ezgif com-optimize](https://user-images.githubusercontent.com/5770876/49689318-c0ae3380-fb1f-11e8-84aa-b59ea526fd70.gif)

**Comment by IvaKop** [comment]
@gigerbytes can't reproduce this issue on the emulator, can you check if it's still there with the update? thanks

**Comment by pA1nD** [comment]
@gigerbytes

**Comment by stacylorraineprendeville** [comment]
We close this issue due to inactivity
