### ISSUE TITLE
Going a step back resets data

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#146]
**Describe the bug**
Going back when taking a survey will reset the form once going forward again.

**To Reproduce**
1. Fill the Family Participant form
2. Go back
3. Click "agree" again.
4. YEAH. Data reset.

**Expected behavior**
Data should still be there. Or have a warning.

**Smartphone (please complete the following information):**
 - Device: Huawei P10
- Android: 8

**Comment by Danman7** [comment]
It doesn't reset the data. It does something much worse. It creates a new draft.

**Comment by Danman7** [comment]
There is no way of knowing where the user will navigate back to next and we could potentially save empty drafts which contradicts #131. I will always delete the draft and add a warning.
