### ISSUE TITLE
Invalid email and phone accepted

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#147]
**Describe the bug**
There is a glitch that makes it possible to continue with an invalid email.
Entere a wrong email, close the 

**To Reproduce**
1. Take a survey
2. Enter a wrong email
3. Close the survey
4. Enter it again.
5. Now you can continue

**Expected behavior**
Should not be possible to contine. Show an validation error.

**Smartphone (please complete the following information):**
 - Device: Emulator! Nexus 5X API 27

**Comment by IvaKop** [comment]
@pA1nD can't reproduce. Please check again.
