### ISSUE TITLE
Navigation problems

### ISSUE THREAD

**Issue by IvaKop** [FundacionParaguaya/MentorApp#154]
- The active tab in navigation is always Create life map, even when you switch to dashboard it does not change 
- When you click on the active navigation item the drawer has to close
- On family participant screen when you close the draft and click No it should stay on the same screen
- On the family participant screen when you click back the same popup should appear as when you click the X and it should have the same behaviour (delete the draft if user clicks yes)

**Comment by Danman7** [comment]
It does close when clicking on an item. Just doesn't happen for lifemap because of the 1st issue.
