### ISSUE TITLE
Connecting the app to real data for testing (suggested WARC Sierra Leone)

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#158]
**Is your feature request related to a problem? Please describe.**
To understand fully the functioning of the app we must also test with real data. Using WARC´s Credentials we log in and find after 30 mins no images downloaded. The app stalls on the preparing screen - Synching surveys 0/0 - Synching survey images 0/0

**Describe the solution you'd like**
Connect the app to the survey for WARC Sierra Leone - These will be the first testing in field. Download all surveys and images to be able to test with real content.

**Additional context**
Requested by the Poverty Stoplight team- urgent client will be working in the field this week!

**Comment by stacylorraineprendeville** [comment]
Various people in the team from Poverty Stoplight requesting this

**Comment by stacylorraineprendeville** [comment]
@pA1nD Is this a credentials issue?

**Comment by stacylorraineprendeville** [comment]
Further issue - Now when I close and re-open the app - It does not ask for credentials anymore -just takes me back to the app preparing screen! So I have had to de-install to be able to login again with another user.....

**Comment by Danman7** [comment]
If you close the app the expected behaviour is not to ask you for credential until you hit logout. It is an issue with the production server as I cannot reproduce it from the test server. Thus it's an issue for the backend team.
