### ISSUE TITLE
Restarting a draft at point left off

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#159]
**Is your feature request related to a problem? Please describe.**
When a user is retaking a draft it is causing frustration to be returned to the first screen.

**Describe the solution you'd like**
When a draft is resumed take the user to the point where the map was exited.

**Additional context**
Later this could be optional on modal (start from beginning/start from where you left off and we could try a slightly amended view - like a frame when reviewing a draft

**Comment by stacylorraineprendeville** [comment]
This I give a bit more weight to - though it is UX. Simply at present the usability of the draft with indicators is not good (noted in a seperate issue) - It is too difficult to see what is selecting - Fixing the above maybe is a quick way of dealing with this?

**Comment by stacylorraineprendeville** [comment]
@IvaKop I would like to review this implementation with you - Reviewing the app we have not followed the UX for the Draft retrieval - This screen was meant to look like this below: Then by clicking resume draft you return to the exact point left. Is the work you are doing on this task coherent with this plan?

![Screen Shot 2018-12-23 at 10.13.33.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/8c752336-2c56-4e74-bb82-eedec8ed18c0)

**Comment by IvaKop** [comment]
@stacylorraineprendeville thanks for pointing this out! I will implement it like this.
