### ISSUE TITLE
Translations Issues

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#162]
- [ ] When in Spanish, the text in the menu section still appears in English.
- [x]  "Bienvenido!" needs the exclamation mark in the beginning
- [x] The genders are in English
- [x] Options of "genero", "Tipo de documento", is in English, not Spanish

**Comment by IvaKop** [comment]
Maybe writing a custom drawer can be the solution here: https://codeburst.io/custom-drawer-using-react-navigation-80abbab489f7
