### ISSUE TITLE
Location doesn't always return position data

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#163]
On some devices (KitKat tablet and Stacy's new Oreo tablet) `geolocation` never returns position data.

**To Reproduce**
1. Create a life map or open a draft and go to Family location
2. Wait 20 secs and see that there is no location displayed
3. Reload app or go back 1 page and forward again and repeat step 2.

This is reproducible only on specific devices. We have at least 2 other Oreo devices (Dan and Bjorn's phones) that don't reproduce this issue.

**Expected behavior**
See a location immediately or after several retries.

**Additional context**
If `geolocation` doesn't return anything before timeout there is probably nothing we could do. I will spent time to research this.

**Comment by stacylorraineprendeville** [comment]
I notice here that when I re-installed the app - It asked - Allow stoplight to access location - I answered yes - maybe this is relevant? @Danman7

**Comment by Danman7** [comment]
This is related to #193 and will be completely fixed in that issue.
