### ISSUE TITLE
Send logout request to server

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#165]
When logging out we should send a request to an endpoint to destroy the token in the server as well 

Endpoint is documented here: https://github.com/FundacionParaguaya/FP-PSP-SERVER/blob/master/docs/OAUTH.md

It's called `/oauth/revoke-token`

**Comment by Danman7** [comment]
Closing due to long time inactivity and project discontinuation. We still don't have an endpoint for logging out, we just clear the local device data.
