### ISSUE TITLE
Performance: App gets progressively slower as you go through the survey

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/MentorApp#169]
**Describe the bug**

App slows down a lot as you go through the survey. Experience was significant performance decrease from Indicator 28

**To Reproduce**

Take the survey.

**Expected behavior**

- Be able to quickly go through the questions
- speed the same from start to end of app

**Screenshots**

**Device (please complete the following information):**
 - Device: Samsung T-560 Tablet 8.5" screen
- Android 4.4.4
- 1.5GB ram

**Additional context**

Theory is older versions of android are the ones experiencing the performance issue since
- It works well on Stacy's tablet, which is 

We will know for sure when Sierra Leone tests because they have the same Samsung T560 tablets with android 7.1.1

**Comment by stacylorraineprendeville** [comment]
@gigerbytes please assign to project and priority these types of issues
