### ISSUE TITLE
Create specification for unique per survey socio economic validation

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#177]
This task is to review the socio economic questions on a per survey basis

**Comment by pA1nD** [comment]
mh?

**Comment by stacylorraineprendeville** [comment]
@pA1nD This was created by me and assigned to me....For me to review and continue later.

Essentially each and every form needs reviewing regarding Socio Economic and especially validation.
The state of the forms on the previous app is not good. Numerical fields are not validated as such. Some clients have dropdowns for currency - others not. Spelling errors etc. I spoke to @IvaKop about this briefly, will need to speak to Diego. We should discuss this in the team. The UK improvements are here so you can see an example:
https://github.com/FundacionParaguaya/MentorApp/issues/192
