### ISSUE TITLE
UK privacy notice

### ISSUE THREAD

**Issue by pepamc** [FundacionParaguaya/MentorApp#178]
Upon taking the UK survey in the new app, the text of the privacy notice is not the same as it was in their old survey.

**Comment by stacylorraineprendeville** [comment]
This is not a development issue. @pepamc The text that has been added was given by Kathi and Telma - Please review this issue with them.

**Comment by pepamc** [comment]
Okay. Where should I mark this kind of request? The text they provided is incorrect. The correct text is in demo.povertystoplight.org under "UK Demo Survey."

Also, you may see here:
(1) Terms and Conditions
Terms and Conditions - Stoplight Platform
Please read carefully before using this application.
This site is provided by the Stoplight and its use is subject to the following Terms and Conditions:

1. Your access and/or use of the web survey and/or app constitutes acceptance of these Terms and Conditions.

2. The Stoplight reserves the rights to modify, add or delete any point of these Terms and Conditions at any time. Your use of this page and/or application constitutes your acceptance of these Terms and Conditions.

3. The Stoplight does not warrant that the functions and materials contained in the web survey and/or app will be uninterrupted or error free; that the website, or the server that makes it available are free of viruses or bugs; or represent the full functionality, accuracy and reliability of the materials. We will try to the best of our ability to correct any error presented within a determined time frame.

4. All intellectual property of the web survey and/or app and the material or information it contains (including without limitation copyright, designs, database rights and trade marks (registered or unregistered) is and shall remain the property of The Stoplight and Fundación Paraguaya or its third party licensors.

5. Commercial use or publication of all or any item displayed is strictly prohibited without authorization from Fundacion Paraguaya (The Stoplight Team) and its third party licensor. Nothing contained in these Terms and Conditions shall be construed as conferring any license by Fundación Paraguaya to use any item displayed.

Please read the following to understand how your personal information will be treated. The policy may change from time to time so please check back every time you are to use this page or app.

Information in the survey cannot be copied, shared or posted on any mean of communication.

If these Terms and Conditions are not accepted in full, the use of the Stoplight survey must be terminated immediately.

(2) Privacy Notice

Privacy Notice
The privacy of your information is very important to us. Please carefully read the following to understand how we use and protect your data. We may update this notice when necessary. Please always refer to this notice whenever you use this page or app.

In using our platform please understand that you agree to the all the terms of this notice.

This notice applies to all of the pages of this platform and any mobile version of it. It does not apply to any pages hosted by other SIGNAL associates, related organisations, partners or the privacy policies or notices of other organisations.

WHO ARE WE?

We are Transmit Enterprise. We are a Community Interest Company. We offer SIGNAL. It is a community service in the United Kingdom.

WHAT INFORMATION DO WE COLLECT?

We collect the personal information you provide in completing the SIGNAL Survey. This personal information consists of: your name, your contact details, statistics about the population group you come from, your social and economic circumstances and your current living standards that are explored by the questions of the SIGNAL Survey.

We need this information to properly explore your circumstances. You can choose to answer any/all or part of this survey. You can remove, change or leave out any of its questions. Anything you delete will not be kept or put back into the data we collect from you.

WHY DO WE COLLECT YOUR INFORMATION?

We need to collect your personal information to better understand all the things that affect your life and the conditions you live in.

HOW IS THIS INFORMATION USED?

All of the personal information you provide helps your support agency understand what they can do to provide you any support you may need once you complete our survey.

DOES SIGNAL SHARE YOUR INFORMATION?

We will never sell, rent or share your personal information with anyone outside of our organisation (including HMRC, Job Centre, DWP) unless you allow us to do so. If the law requires that we must share this information, however, we will have to do so.

HOW LONG DO WE KEEP YOUR INFORMATION?

You can change or delete any of your personal information collected in our survey at any time. You will need to update this personal information regularly so that we can keep track of your circumstances accurately. We will give you a reminder every year to do so.

DELETING OUT-OF-DATE INFORMATION

If you leave your support agency and you choose not to update your personal information every year in our survey, we will delete that information after a period of two years. This protects your privacy and ensures that all your personal information is always accurate in line with your changing circumstances.

HOW SECURE IS THE INFORMATION YOU GIVE US?

We use proper regulated industry practices to protect your privacy, including encryption and anonymization (removing identifying information). We cannot, however, fully secure your personal data from hackers, crackers or cyber-criminals.

HOW CAN YOU ACCESS OR CHANGE YOUR DATA?

Please submit a Subject Access Request to contact@clearsignal.org to access your personal data.

All personal information you provide in our survey can be changed, deleted or left out. If one of our representatives is not present, you can make a request to delete any of your information within thirty days of your completing our survey.

WHAT IF YOU NO LONGER WANT TO BE INVOLVED WITH SIGNAL?

SIGNAL highly values your personal information in order to actively and properly assist you if you may be in need. Any personal information you provide may always be deleted. Please contact us on the details provided below if you have any queries.

HOW CAN YOU COMPLAIN ABOUT HOW WE USE YOUR DATA?

Please contact us with any complaints about the use of your personal data or our service and activities.

If you wish to complain to The Supervisory Authority in the UK please contact the Information Commissioners Office (ICO). See https://ico.org.uk/

HOW CAN YOU CONTACT US?

You can contact the SIGNAL team by email: contact@clearsignal.org

or by writing to: Transmit Enterprise, Gateshead International Business Centre, Mulgrave Terrace, Gateshead NE8 1AN

PROFILING AND AUTOMATED DECISION-MAKING

We remove any identifying information before we conduct any statistical profiling. This is called anonymisation and it protects your privacy.

**Comment by stacylorraineprendeville** [comment]
@pA1nD Each survey has the possibility of unique terms and conditions.

**Comment by diegotorrespy** [comment]
@IvaKop I have updated the survey service in order to obtain the text of the tc and pp as follows: ```termsConditions{text}```. 

@stacylorraineprendeville With this update the correct text should already be displayed.

**Comment by IvaKop** [comment]
@diegotorrespy What about the privacy policy?

**Comment by diegotorrespy** [comment]
@IvaKop Regarding to pp, is the same syntax to get the text: ```privacyPolicy{text}``` 

And regarding to the en line character, let me change again because I thought you'd just need the plain text.

**Comment by IvaKop** [comment]
@diegotorrespy we need to also separate the title from the text as per the design: So we need something like privacyPolicy{ title text }

**Comment by IvaKop** [comment]
@diegotorrespy we need this implemented in the testing environment as well, as it should work with the new update.

**Comment by stacylorraineprendeville** [comment]
Two issues here

1. The UK Text retains unnecesarily the titles - 
In the page Terms & Conditions Remove the line "Terms and Conditions - Stoplight Platform"
In the page Privacy Policy please remove the text "Privacy Notice" This text is already in the page titles.
2.Sierra Leone and Elmira are now loading in the UK Terms and Conditions and Privacy notice - NOT the default Poverty Stoplight text. Can you look into this @gigiroyg?

**Comment by diegotorrespy** [comment]
The texts are already updated, but in the mobile app it is necessary to logged out first in order to synchronize the definitions again.

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy @gigiroyg The UK text is now appearing in the Sierra Leone survey - Please review this - Its urgent

**Comment by stacylorraineprendeville** [comment]
@gigiroyg We can leave this now to edition to review...I think this in there end if we are sure we are retrieving now from the server....Are we 100% sure?
