### ISSUE TITLE
Remove the summary of skipped questions that comes before the dashboard and life map

### ISSUE THREAD

**Issue by pepamc** [FundacionParaguaya/MentorApp#181]
There should be no summary of the questions that were skipped at the end of the survey (right before the dashboard and life map). Can partners opt-in or opt-out of this feature?

**Comment by stacylorraineprendeville** [comment]
This is not a correct issue.
This feature was added by Eduardo to push that the minimum of questions go unanswered and to ensure people have the opportunity to re-answer. The system has been built to add this.
We will not remove unless we have majority feedback that this is not required.
