### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#187]
**Describe the bug**
This bug has been reported by a client.
The clients words:

"Re sync error - can’t take a screen shot with this tablet version. However, once all activity is complete ie after priorities etc there is a note in red box at bottom of screen saying error with syncing. Tried x 2/3 times and same note appears."

This is UK Poverty Stoplight

This error is visible on the dashboard.

**Comment by stacylorraineprendeville** [comment]
OK - I cannot reproduce this - for now I presume this was due to work in progress on the server

**Comment by stacylorraineprendeville** [comment]
This issue appears to have been while the work on the web platform was in progress.
After testing with the UK credentials I could not reproduce this error.

**Comment by stacylorraineprendeville** [comment]
Just received a sync error on the UK Poverty Stoplight form whilst connected via WIFI

**Comment by pA1nD** [comment]
@IvaKop

**Comment by IvaKop** [comment]
@pA1nD Can we or can we not send fake data on the UK survey? If not, I have no way to test/reproduce this. And from the comments above I assume Stacy is crating tests surveys on the UK account or is that not the case @stacylorraineprendeville?

**Comment by stacylorraineprendeville** [comment]
I am logging in with the UK credentials

**Comment by stacylorraineprendeville** [comment]
- I am not able anymore to sync. I get an error when I try to sync with the UK survey. Login: `mentor` PW: `test`
- Logging in with `life_survey_user` results in a problem with sync... Nothing syncs and I am stuck in this screen.

reported by @pA1nD

**Comment by stacylorraineprendeville** [comment]
@gigiroyg can you please get back to Iva regarding this....she is blocked
