### ISSUE TITLE
Country of residence should not default to country of birth

### ISSUE THREAD

**Issue by pepamc** [FundacionParaguaya/MentorApp#188]
In the UK survey, as I'm trying to choose my GPS location, the "country of residence" question defaults to the answer chosen for "country of birth". This is not ideal; the default answer for "country of residence" should be the country where the survey is being taken.

**Comment by stacylorraineprendeville** [comment]
This is a duplicate
https://github.com/FundacionParaguaya/MentorApp/issues/82
