### ISSUE TITLE
Map UI - handling offline and no location available

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#193]
**(1) Map is available (online)**
If GPS location is available:
Wait (max 10 seconds) with showing the Map to fetch the location. (Show some loading indicator). This is to protect from a loading with a jump afterwards.

In case you don't receive the location within the timeout, show the map centered on the default location. (do NOT set the draft location) 
When clicking on the "locate me" button, move the center to the received location and set the draft location.
When moving the map set the draft location. 

In case you receive the location within the timeout, set the map center and the draft location to the received data.

**(2) Map is not available (offline)**
Do NOT set draft location. Don't show the map. _**We will improve this in January.**_

**Comment by Danman7** [comment]
@pA1nD We need this better defined and it's not temporary anymore.

**Comment by Danman7** [comment]
This now also includes centering on survey location.
