### ISSUE TITLE
1 Mandatory fields required in creation of priorities or achievements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#198]
**Describe the bug**
A user can create a priority or achievement without saving any content to the screen

**To Reproduce**
1. Go to make a priority
2. Click save
3. Priority is saved =error

**Expected behavior**
Please enforce that “how many months will it take” question is mandatory in priorities
Please enforce that the first question of achievements is mandatory.

**Comment by stacylorraineprendeville** [comment]
We will continue with the disabled continue/save button until this further issues is worked on.

**Comment by Danman7** [comment]
Doing this issue I've also discovered an issue where a required text field with value in it will still show a lonely * when there should be nothing.
