### ISSUE TITLE
Remove option to exit process on the final thankyou screen.

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#199]
When a user has completed the Life Map and is viewing the thankyou screen they should not have the option to quit the process in the top right hand corner. Actually this message is incorrect - it states the life map is not complete (it is) and that it will be saved as a draft (it will not)

**Describe the solution you'd like**
Remove the X option from the top right corner of the screen on the thankyou page.

<img width="362" alt="screen shot 2018-12-17 at 17 32 44" src="https://user-images.githubusercontent.com/45012899/50100941-da3b3380-0221-11e9-903c-719046b4ce87.png">

**Comment by Danman7** [comment]
Remove the back button as well.

**Comment by stacylorraineprendeville** [comment]
DO NOT REMOVE THE BACK BUTTON!!!!!

**Comment by stacylorraineprendeville** [comment]
DO NOT REMOVE THE BACK BUTTON AS WELL
