### ISSUE TITLE
Amend order of Indicators in UK Survey

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#200]
**Describe the bug**
The ordering of all indicators within the UK survey is incorrect.

**Steps to resolve**
Change the order within the UK Survey as per the spreadsheet

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy can you add the UK ordering - I sent it to you in Slack

**Comment by IvaKop** [comment]
@stacylorraineprendeville @diegotorrespy this is a server issue, please move it to the appropriate repository.

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy I need an urgent update on this issue.

**Comment by stephannman** [comment]
Hi all! On Friday, many of the indicators were restored to the proper order but the order is still not 100% right. 

If you login to production with username A Cox and password AC001 you can see that the indicators are still in in the order specified by the UK survey google spreadsheet.

The following indicators remain out of place:
-Eating a nutritious diet is at 4 but should be at 22, before Health-Care access.
-Separate bedrooms is at 21 but should be at 13, before Home comforts
-Set meals is at 36 but should be at 21 before Eating a nutritious diet.

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy @gigiroyg Can you please review stefanies comment above and action these changes.

**Comment by gigerbytes** [comment]
@stacylorraineprendeville : Review Frontend again.

**Comment by stacylorraineprendeville** [comment]
Just reviewed the front end under demo demo
This task is not complete
