### ISSUE TITLE
Images do not synchronize

### ISSUE THREAD

**Issue by gigiroyg** [FundacionParaguaya/MentorApp#204]
**Describe the bug**
Does not synchronize the images.

**To Reproduce**
1. Login.
2. Wait too much time for the synchronizing but nothing happens. It stays "synchronizing" but it keeps in 0/0 forever.

**Expected behavior**
Syncrhonize all the images.

**Comment by IvaKop** [comment]
@gigiroyg which user are you using here?

**Comment by stacylorraineprendeville** [comment]
I believe this issue is in regards to the test server - correct @gigiroyg ?

**Comment by stacylorraineprendeville** [comment]
@IvaKop I see this issue currently under Demo Demo
Everytime I remove data on logging back in the images do not sync
I then have to quit the app and restart it - then it works

**Comment by pA1nD** [comment]
Closed because it's not clear and seems to be fixed but the current issue is another one. Going to open another issue for this.
