### ISSUE TITLE
"Other" fields 

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#221]
As a mentor user...

WHEN I select the option "Other" within a dropdown 
THEN a text field must appear below that allows me to provide the details of "Other"
AND this text field must be activated
AND the title must be "Specify "insert name of previous field"
AND If the field in which other was selected is mandatory 
THEN the text field must itself be mandatory.
AND if I select another option in the dropdown
THEN the other field disapears

![Screen Shot 2018-12-21 at 20.41.35.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/bb1b8433-c77e-4403-8887-f40cdfd7cef1)

**Comment by pA1nD** [comment]
This is an additional requirement which was not available before and not discussed so far. It would need additional technical specification.

**Comment by stacylorraineprendeville** [comment]
@pA1nD Can we create the technical specification for this?

**Comment by stacylorraineprendeville** [comment]
This would be a back end issue first.....

**Comment by pA1nD** [comment]
This requires a new schema for sending data. 
There is one new value that should be transmitted: "Custom Document Type".
It would be possible to pass it as Document Type but this would cause confusion.
Document Type should be "other" as value and a new value should be added.

@IvaKop could you make a suggestion?

This also requires a new Schema for the Database
@diegotorrespy could you make a suggestion?

**Comment by Danman7** [comment]
For the front-end we need to get the following structure from the back-end when we get the survey:
```json
{
  "id": 1,
  "surveyConfig": { "gender": { "other": true } },
  "surveyEconomicQuestions": [
    {
      "answerType": "select",
      "codeName": "areaOfResidence",
      "other": true
    }
  ]
}
```
This will allow us to see if age or a given socio economic question supports other. The API call for getting surveys will look like this.
```graphql
query { surveysByUser { title id minimumPriorities privacyPolicy { title  text } termsConditions{ title text }  surveyConfig { documentType {text value} gender { text value other } surveyLocation { country latitude longitude} }  surveyEconomicQuestions { questionText codeName answerType topic required forFamilyMember options {text value} other } surveyStoplightQuestions { questionText codeName dimension id stoplightColors { url value description } required } } }
```
Above you have `other` in both `surveyConfig/gender` and `surveyEconomicQuestions`.

Submitting back the answers will look like this in an example draft:
```json
{
  "draftId": 4,
  "surveyId": 1,
  "economicSurveyDataList": [
    { "key": "educationPersonMostStudied", "value": "O", "other": "Classess" }
  ],
  "indicatorSurveyDataList": [],
  "familyData": {
    "countFamilyMembers": 2,
    "familyMembersList": [
      {
        "firstName": "Juan",
        "lastName": "Perez",
        "gender": "O",
        "genderOther": "Elephant",
        "birthDate": 12345,
        "firstParticipant": true,
        "socioEconomicAnswers": [
          { "key": "receiveStateIncome", "value": "O", "other": "Some" }
        ]
      }
    ]
  }
}
```
The new thing is other fields in `economicSurveyDataList` and `familyData.familyMembersList.socioEconomicAnswers` and `genderOther` in ``familyData.familyMembersList`

**Comment by zommerberg** [comment]
i dont have a proper way of showing the specifying textfield for document types since on the background we write them down with a value from 0-X , see pictures for reference.
in the first picture we have 3 options eg 0-3
in the second picture we have 5 pictures eg 0-5 and it doesnt even have a "Other" option.

is it safe for me to rely on the text only or should we make unique identification for "Other" type for document type,just like we have in" gender  select" where M is male , F is female and O ist other? 


<img width="283" alt="Screenshot 2019-05-02 at 15 58 37" src="https://user-images.githubusercontent.com/43446836/57077824-a73b9d00-6cf5-11e9-98f2-87cc9317f5dd.png">
<img width="282" alt="Screenshot 2019-05-02 at 16 02 40" src="https://user-images.githubusercontent.com/43446836/57077825-a73b9d00-6cf5-11e9-8819-3b159bd11a9f.png">

**Comment by zommerberg** [comment]
I have already added specify gender to primary participant and family members . The new field is called specifyGender
<img width="367" alt="Screenshot 2019-05-02 at 16 05 37" src="https://user-images.githubusercontent.com/43446836/57079459-0b139500-6cf9-11e9-80c0-27c7d24f0548.png">
<img width="270" alt="Screenshot 2019-05-02 at 16 03 29" src="https://user-images.githubusercontent.com/43446836/57079478-14046680-6cf9-11e9-9f1d-126b8486dbff.png">
