### ISSUE TITLE
Date Validation Improvements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#222]
This issue is to create an effective date validation.
At present we fix the validation and the user is unaware of which field causes the validation issue.
A client has also reported that it seems "fixed"

Lets discuss our options here - We can also use a different way of using the fields - i.e. Dropdowns for days and years - In this method we would only need to validate empty fields and thus we could solve the issue.
OR
we can look into further UX changes and date pickers.
Lets decide a best approach on this.

**Comment by IvaKop** [comment]
@stacylorraineprendeville @pA1nD Let's specify a solution before I can add an estimate here.

**Comment by stacylorraineprendeville** [comment]
Ok 2 things are the issues

1. The most important - the validation should not appear after selecting the month - but only after the three fields are entered
2. Does this mean then that all three fields need the star for mandatory - to be discussed!

**Comment by stacylorraineprendeville** [comment]
DECISION - DROPDOWN S FOR DATE AND YEAR (1919-2019)

ERROR WOULD APPEAR ONLY IF MONTH WAS NOT POSSIBLE WITH DAY.....

ERROR MESSAGE - Please enter a valid date
