### ISSUE TITLE
Bug in revealing checkbox for chosen indicators when moving backwards and forwards in a survey

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#225]
This bug has been noted by a client:

#### Whilst using the stoplight questions.....

If I go back one question (using the back arrow at the top left corner), it doesn’t show what I
previously selected (it might go to the stoplight, but doesn’t show the tick mark)

.....But if I go back one more question, select an option, it will bring me to the next question
and my previously selected response will be show.

#### Steps to Reproduce
Q4 – Select red
Q5 – Select yellow
Q6 – No selection, go back to Q5
Q5 – Arrives at yellow option shown, but no tickmark. Go back to Q4
Q4 – Arrives at red option shown, but no tickmark. Select red again.
Q5 – Arrives at yellow option, with tickmark shown.

Client notes "This behaviour above is also inconsistent. Sometimes it happens, other times it will
display a tickmark."

#### Intended Behaviour
The Check box should be displayed for each question - clearly indicating to the user their previous choice.

**Comment by Danman7** [comment]
I've QA-ed this and can't reproduce it after latest deploy.
