### ISSUE TITLE
Add handeling for numeric type for socio economic fields

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#230]
When the server sends the value `numeric` in surveyEconomicQuestions.answerType,
THEN the input field should validate for numbers
AND the keyboard should show the "numbers keybord"

**Comment by diegotorrespy** [comment]
The information about the type it will be came in the socio economic question:  

```
surveyEconomicQuestions{id,orderNumber,codeName,answerType,...}
```
