### ISSUE TITLE
UX warnings for Logout with Unsynced data

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#231]
##### As a user I want to clearly understand the effect of logging out with unsynced data so that I can  ensure I do not delete data.

1. When a user chooses to logout without any data to sync the user is prompted to be sure.

When a user chooses to logout with unsynced data the steps are the following. 
1. The user is informed that they will loose data - If they continue to choose yes....
2. A secondary screen advises them and asks for each area of potential data loss to be agreed to by checking a checkbox.
3. If the user tries to click to logout without checking ALL checkboxes - The checkboxes are highlighted and underlined.

This step is essential for our users.

![Screen Shot 2018-12-27 at 11.32.00.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/f4f3796a-2b7a-45e2-9c76-294701c199e5)

**Comment by Danman7** [comment]
@stacylorraineprendeville I'm working on this, but I have a question. At the moment the user can only really loose drafts and cached images. He doesn't save families locally so he can't lose them separately from a draft, he always gets them online. He also can't really lose life maps as they are in fact drafts.

My question is: are the checkboxes contextual to what the user can actually lose or are they seeing all of them every time there is unsynced data?
