### ISSUE TITLE
Families Screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#234]
This issue is to add the families screen. In the first iteration we will add this WITHOUT the map.

The spec is to add:
- The search feature by name
- Display the families alphabetical ascending
- change the total number of families to reflect the search criteria
- Add the family member numbering on the icon.
- As a TEMPORARY interim measure the family page can be linked directly to the lifemap review screen (the next sprint will deal with creating review pages for socio economic)

![Screen Shot 2018-12-27 at 14.04.58.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/d204b4e8-ee52-40ce-901e-ea471ae4168c)

![Screen Shot 2019-01-14 at 16.56.27.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/b2c07ccc-de92-4db2-b819-dca0918f61a4)

**Comment by IvaKop** [comment]
@stacylorraineprendeville we should discuss thus before implementing.

**Comment by stacylorraineprendeville** [comment]
@IvaKop Exactly - We have time for this later today

**Comment by Danman7** [comment]
@stacylorraineprendeville This should be an epic instead of a single issue. Too big for even a 13.

**Comment by stacylorraineprendeville** [comment]
@Danman7 We will need to make this priority for the next grooming.

**Comment by stacylorraineprendeville** [comment]
This screen will display families from the server (those already synched)

**Comment by IvaKop** [comment]
@stacylorraineprendeville I need translation for this screen for the search bar placeholder.
"Search by name or ID number"

**Comment by stacylorraineprendeville** [comment]
moving from sprint 002 to sprint 004 - Work blocked by back end
