### ISSUE TITLE
Add Dimensions to the Life Map Indicator Questions Screen.

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#245]
Please add the dimensions name to the indicator questions screen.

(It was stated previously that these were not available on the platform and thus the app - BUT if we review the lifemap screen we can see that these are available to the app - Just that these are missing from the individual indicator screens.

**Comment by Danman7** [comment]
Resolved with 27eaf929a82062dbc1be2a9781aaa43bc5917309
