### ISSUE TITLE
Duplicated Content on Platform

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#246]
2 reports of Duplicated content

1. Eduardo - On Demo Platform - Demo /Demo
"it also duplicates the information when seeing it from Partner login (its organization)"

2. Stacy - When completing 2 life maps on demo / demo I both times when to the last page - Great you have completed - then went backwards and added a priority - then forwards and closed. This created duplicate lifemaps - 1 with the priority and one without - Please review this under the Family Name Stacy Prendeville ( I am aware this may be an app issue though I prefer this to be diagnosed by yourselves now that I have recevied the information from Eduardo above)

**Comment by gigerbytes** [comment]
Seems like an issue of the app sending data duplicated.

**Comment by pA1nD** [comment]
@IvaKop is this now handled in #199 ? Or is there anythng else to this?
