### ISSUE TITLE
Print and Email Life Maps

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#247]
As a user I want to be able to print or send an email of a completed life map to myself or a family so that I can follow up and give a record of the results.

This feature was currently in the platform in that at the end of taking a lifemap a user could print or email this (Stated by the PS Team)
Currently this is not possible from the app - (Though it should be a future feature)

The UK team is waiting for this feature...

**Comment by gigerbytes** [comment]
Printing lifemaps implemented and tested.

Notes: There were some issues with conflicts when merging to master so I copy pasted bjoern's code to the individual files to make it work.

I've reviewed @pA1nD 's PR #280
