### ISSUE TITLE
Missing "Make priorities message" when priorities are not mandatory.

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#248]
When no priorities are mandatory - On the review screen - Alert the user to the next step of creating priorities.

![Screen Shot 2019-01-14 at 11.41.01.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/6a47125d-fbe5-4297-8878-813f5767f267)

**Comment by IvaKop** [comment]
Translation:
*To complete the lifemap... Create some priorities!:* 
Para completar el Mapa de Vida... ¡Crea algunas prioridades!

**Comment by Danman7** [comment]
Duplicate of #322
