### ISSUE TITLE
New surveys not downloading if logged in

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/MentorApp#252]
**Describe the bug**
If I am logged into the app and I add a new survey on the backend. THe app automatically goes to the dashboard and does not download any of the new surveys.
Also, only the old surveys are available to me.

**To Reproduce**
1.Login to app & get to dashboard
2. Create a new survey
3. Close & open app

**Expected behavior**
The new surveys should appear if I log back in.

**Additional context**
Note that this happens even after the survey has been migrated properly into the data_collect.survey_organization table

**Comment by Danman7** [comment]
@pA1nD @IvaKop I need to discuss how to handle this with you guys.

**Comment by stacylorraineprendeville** [comment]
@pA1nD This needs to be groomed - fairly urgent

**Comment by pA1nD** [comment]
When downloading the latest surveys, they could have been:
(1) New one was created
(2) Existing one got deleted
(3) Existing one was updated (version should change)

### A few edge cases to think about:

(1)
- Pictures needs to be synced. This would take longer and a UI should be provided.

(2)
- Can't really happen, as there is no way to do this in the platform. Survey should stay in the app. Logging out would remove all the data.

(3)
- Could require pictures to be synced. This would take longer and a UI should be provided.
- Lifemaps in progress should continue with the version of the lifemap they were started with.

**Comment by stacylorraineprendeville** [comment]
@pA1nD Please can you meet with Dan and Iva and get this groomed this week :)

**Comment by Danman7** [comment]
@stacylorraineprendeville I need UI for this.

**Comment by pA1nD** [comment]
@stacylorraineprendeville we could do periodical checks if there's a new survey available to download. If there is, we could show a message on the dashboard that would lead the user to a sync screen similar to when he's logging in.

**Comment by stacylorraineprendeville** [comment]
How would you do the periodical checks - Would these be automatic and thus invisible to the user?
So the the message only appears if there is something to update? @pA1nD

**Comment by pA1nD** [comment]
exactly.

**Comment by stacylorraineprendeville** [comment]
OK One more question - We need to stop the user from using the app until they do this.........correct?
If so we will need a simple error message as from the style guide - A window -
These windows are for when something is required and the user cannot move forward without doing so:
<img width="364" alt="Screen Shot 2019-04-09 at 15 58 59" src="https://user-images.githubusercontent.com/45012899/55834918-9924a300-5ae0-11e9-945b-6b8234886d6b.png">

**Comment by stacylorraineprendeville** [comment]
@Danman7 What are the next steps with this one?

**Comment by stacylorraineprendeville** [comment]
@Danman7 What shall we do with this issue? Still relevant? Or no - As we now have Surveys downloading on the login....

**Comment by stacylorraineprendeville** [comment]
Currently we only cover on App Update - Update Survey
As we discovered there are survey updates that don’t include app updates
For example jorge adding new offline maps, that doesn’t need me to update the app version
This still needs to be resolved

**Comment by stacylorraineprendeville** [comment]
@pA1nD Can you please review this - Been trying to get someone to look at it since I began as PO

**Comment by Danman7** [comment]
This issue will finaly be solved in #1035 after design is provided.
