### ISSUE TITLE
Adjust logic for server selection so that the App can be tested in testing server

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#256]
### Problem:

When logging in, only the string `life_survey_user` will use the testing server. This was alright in the past. In a recent update, we made the usernames more simple and reset the data every 24h. `life_survey_user` is not an easy username.

### Solution

Create a logic that will route any username to the testing or demo server.
- Use a pre-fix to allow defining which server to use in the format: `d/username`
- When there no pre-fix, use the production server.
- When the username is "demo" use the demo server.

Use the pre-fixes:

```
'p/': prod
'd/': demo
't/': test
```

### Pseudo Code:

Working in the web app.

Instead of importing the objects maybe use strings in the function.
```
import { prod, demo, test } from './../env.js'
```

```
  selectServer(username) {
    if (!username) return { server: prod, user: username }
    if (username === 'demo') return  { server: demo, user: username }
    switch (username.substring(0, 2)) {
      case 'p/':
        return { server: prod, user: username.substring(2) }
      case 'd/':
        return { server: demo, user: username.substring(2) }
      case 't/':
        return { server: test, user: username.substring(2) }
      default:
        return { server: prod, user: username }
    }
  }
```

Usage:
```
    const { server, user } = selectServer(username)
```

**Comment by Danman7** [comment]
@pA1nD This is a very questionable idea. I've not seen something like this implemented. Let's discuss this in more detail.

**Comment by stacylorraineprendeville** [comment]
Can we not just have a new user - Testing testing? @pA1nD

**Comment by pA1nD** [comment]
I would highly recommend to implement this as described.
I've seen this implemented in other systems like LDAP Microsoft systems.
The name before the slash referred in those cases to the user group or environment.

Everything else would add restrictions to testing (what if you want to use a seonc account to test certain things).

I was not able to find any article with points against the suggested solution.

@stacylorraineprendeville it's up to you to decide how this should be implemented.

**Comment by Danman7** [comment]
@pA1nD Who is this helping at the moment?

**Comment by pA1nD** [comment]
It would help to test the app against the testing server.

**Comment by pA1nD** [comment]
Any update?

**Comment by stacylorraineprendeville** [comment]
@pA1nD @Danman7  Lets sort this out  - The app cannot be tested on the testing server - Does this fix this?

**Comment by Danman7** [comment]
@stacylorraineprendeville @pA1nD With the conditional logic we just had our first case where we need this. I would much prefer a select dropdown that shows after the user click on a button somewhere in the login page (so we don't bother normal users), but I understand the implications here. We can implement this.
