### ISSUE TITLE
Elmira survey - dashboard has a couple words that don't match

### ISSUE THREAD

**Issue by stephannman** [FundacionParaguaya/MentorApp#258]
**Describe the bug**
Upon taking the Elmira, U.S. survey in the mobile app, the dashboard with the short names of each indicator doesn't match what it said in the old version. 

**To Reproduce**
1. Select Elmira's survey and proceed until the end when you see the dashboard.
2. Upon looking at the dashboard, you will see short titles of each survey question. (i.e. "We have enough income".)
3. The error is that what is currently in production does not match what was previously in production. Please see below for the correct list:

1 - We have enough income

2 - We have savings

3 - We have access to credit

4 - We have different sources of income

5 - We have forms of ID

6 - We live in an unpolluted environment

7 - We manage our garbage well

8 - We have running water

9 - We have access to health services

10 - We have a nutritious diet

11 - We have good hygiene

12 - We have too sexual health

13 - We have healthy teeth

14 - We have healthy vision

15 - We are vaccinated

16 - We have insurance

17 - We have a safe home

18 - We have a comfortable home

19 - We have separate bedrooms

20 - We have a suitable kitchen

21 - We have a suitable bathroom

22 - We have appliances and other goods

23 - We have a phone

24 - We have sufficient and appropriate clothes

25 - We are safe from violence

26 - We have not been robbed

27 - We have electricity

28 - We have regular transportation

29 - We have safe roads

30 - Our children go to school

31 - We know how to read and write

32 - We have school supplies

33 - We have a budget

34 - We know how to generate income

35 - We have access to information

36 - We have hobbies

37 - We respect differences

38 - We respect human rights

39 - We do not promote child labor

40 - We are part of a group

41 - We know how to contact public officials

42 - We solve our own problems

43 - We vote in elections

44 - We have family goals

45 - I feel confident

46 - We make decisions together

47 - We control our emotions

48 - We have no violence in our family

49 - We are business-minded

50 - I have control over my life decisions

51 - We don't have addictive behaviors

**Comment by stephannman** [comment]
Hey @stacylorraineprendeville checking to see if this has been assigned to anyone yet?

**Comment by stacylorraineprendeville** [comment]
@stephannman This is in the wrong repository and thus has been missed - I need to close and move this to the server repository and then will add it to this sprint 007

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #556](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/556) via [**ZenHub**](https://www.zenhub.com/)
