### ISSUE TITLE
Elmira survey - some questions can't be skipped

### ISSUE THREAD

**Issue by stephannman** [FundacionParaguaya/MentorApp#260]
Some questions on the Elmira survey cannot be skipped.

1. Login on a tablet with username: mentor pass: test and chose the Elmira survey.
2. Advance through the socioeconomic survey and see that once you're in the PS survey, you can't  skip questions 30, 31, 32, 39. It makes you select a color.

Every question in PS survey should be able to be skipped.

This happened on a Samsung tablet.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #377](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/377) via [**ZenHub**](https://www.zenhub.com/)
