### ISSUE TITLE
Automated GQL response checking

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#262]
### Problem:

The app crashes over and over again and it looks like it is unstable. But this is because the data from the server is constantly changing and it is not predictable what will break the app next.

Building in all possibilities for data sent / not sent by the server is a not managble effort.

### Solution:

The GQL query defines, which keys should be pressent. As the GQL query exists as a string, we can check the received data for consistency and directly show a concrete error message, in case there are missing keys, etc. This will allow for faster debugging and a much better user experience as the app not just "crashes" and makes an instable impression.

### Suggested Pseudocode:

- Get the string for the query
- Parse it to create an object out of it
- Get the data from the server response
- Iterate over the own keys of the object from step 2 and check if they are present in the server response
- If not show an error.
- If helpfull, add additional checks.

**Comment by IvaKop** [comment]
@pA1nD I plan to use this or similar method to validate on the front, but this should absolutely be integrated in the server tests to make sure the api actually works. If not possible for the Java, at least in the new server:
https://assertible.com/blog/testing-and-validating-api-responses-with-json-schema

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy anything required on the back end here...

**Comment by stacylorraineprendeville** [comment]
This needs to be unblocked -  @diegotorrespy @pA1nD @Danman7 Comments please

**Comment by pA1nD** [comment]
@Danman7 what do you think about this issue? Could we implement this?

Looking at #384 , I think we should at least implement something that prevents the app from crashing but shows a message "The data from the server seems to be corrupt".

**Comment by stacylorraineprendeville** [comment]
@Danman7 @pA1nD This is one of these issues that we need to move on - its lingering - what is required?

**Comment by Danman7** [comment]
@stacylorraineprendeville @pA1nD I can show a simple corrut data message as bjorn has sugguested. No need for the 2 previously blocking issues to be completed. We are requesting data from the server only when caching after login (and updating families list). We already have an implemented ticket for this: we show a something went wrong screen #822. I can specify which portion went belly up, which is either surveys or families or maps. I would need some design to update the something went wrong page 
<img width="361" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563313966666139613839366461356438336436613064302f36363933643932372d313136612d343639642d623164372d363234336234326533656362" src="https://user-images.githubusercontent.com/3336245/60658073-231fa600-9e5b-11e9-9fc1-2c2918868115.png">

**Comment by Danman7** [comment]
I can do the initial request. It will take some time, but we can check the GraphQL response.

**Comment by Danman7** [comment]
At this point this is of little use. We never got corrupt data, rather had errors from the server where the app didn't properly notify the user.
