### ISSUE TITLE
Duplicate key props of dropdown options in Primary Participant view

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#266]
There are multiple items with the same key and probably id as well. Although this results in an error which no user can see (I see this in dev console), it also results in multiple options appearing selected in a single select dropdown.

**Comment by Danman7** [comment]
@pA1nD The problem here comes from the survey data. In the Sierra Leone survey, for the Document Type I get the following data:
```
[
 {text: "Passport", value: "0"}
 {text: "Driver license", value: "1"}
 {text: "National ID card", value: "2"}
 {text: "State ID card", value: "3"}
 {text: "Permanent resident card number", value: "2"}
 {text: "Organization-assigned number", value: "2"}
]
```
You can see that Organization-assigned number, Permanent resident card number and National ID card have the same value and that is causing this issue. Is this a bug on the data side an expected behaviour in the data that the app should handle in some way? If yes, how?

**Comment by pA1nD** [comment]
This should be fixed in the data. It's not possible to have same values within a list.

@diegotorrespy could you take it over?
