### ISSUE TITLE
Sync Screen - Corner Case - Sync needs manual start

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#280]
In the instance where the user is connected online BUT sync has not initialised manually - allow the user to manually start the sync process.

![Screen Shot 2019-01-15 at 11.15.06.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/5a4e24dd-859c-4da3-9ef1-7bf21010fb6b)

**Comment by stacylorraineprendeville** [comment]
@Danman7 @pA1nD - Originally with Iva I had understood that the app never needed a manual sync - however now we have this use case again.
@Danman7 Can we close this ticket? Its completed now?
Can you send me a screen grab of the screen so I can preview it - Hard to test it as I have no error.

**Comment by Danman7** [comment]
This is long completed.
