### ISSUE TITLE
Skipped indicators still allow priorities

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#282]
[https://demo.povertystoplight.org/#families/687/snapshots/%0A%20%20%20%20%20%20772/indicators](url)

When clicking on a gray indicator, which means that this indicator was skipped, I can still have the option to add priorities (however, it's not a red or yellow indicator). It should just not give me the option to click on it.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/fp-psp-frontend #291](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/291) via [**ZenHub**](https://www.zenhub.com/)
