### ISSUE TITLE
Print section of the Life Map: Not aligned

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#287]
Bug:
On the Web App, when we want to print a Life Map, the description of the indicators are not aligned and the priorities are not shown there. 

**To Reproduce**
1. Go to Household
2. Tap on Stoplights
3. Tap on Sprint

**Expected behavior**
The list of the indicators and their description should be correctly aligned, and the priorities of the chosen indicators should be displayed also. 

THIS IS ON THE WEB APP
<img width="1002" alt="screen shot 2019-01-16 at 11 59 09" src="https://user-images.githubusercontent.com/44477708/51258094-ec76d180-1987-11e9-9fd1-6ca4b077447d.png">

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/fp-psp-frontend #290](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/290) via [**ZenHub**](https://www.zenhub.com/)
