### ISSUE TITLE
404 error on Cali survey household

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#288]
Bug
On the Web App: The 404 internal error appears when I clicked on the demo survey I took of the California survey

**To Reproduce**
1. Go to 'Households'
2. Tap on 'ana rojas'
3. See error

**Expected behavior**
The Life Map with the indicators
![2019-01-16](https://user-images.githubusercontent.com/44477708/51259731-82f8c200-198b-11e9-9ee3-bcc46354e3f7.png)

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/fp-psp-frontend #289](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/289) via [**ZenHub**](https://www.zenhub.com/)
