### ISSUE TITLE
Unique demo for UK

### ISSUE THREAD

**Issue by stephannman** [FundacionParaguaya/MentorApp#289]
The U.K. used to have their own demo survey in the demo web platform and demo app that they could show to potential partners and to onboard new partners. When the new app was updated in January, they no longer had access to it. They had different accounts such as username: UK_demo and UK_demo_su

Can that eventually be re-activated?

Note: not urgent

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #385](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/385) via [**ZenHub**](https://www.zenhub.com/)
