### ISSUE TITLE
Separate Family in redux store from the dtraft

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#293]
When a user edits a draft and a family they should edit the same entity. This means that in data terms the family should be separate from the draft reducer. It also means that the draft will have access to the given family and this will require some changes in the navigation as well.

**Comment by pA1nD** [comment]
This means that:

(1) 
- Adding a family in a draft
- Going to the family list, the family would show up there
- Going into the draft and changing the name there
- Going to the family list, the family name would automatically update

(2) In a later sprint when adding the family edit views, changes you would take here would also show up in the family draft directly.
