### ISSUE TITLE
Delete cached images on logout

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#303]
This should also reflect in the modal for log out.

**Comment by Danman7** [comment]
For this I need:
@stacylorraineprendeville some basic design for what is visible while images are deleted as that takes time.
@stacylorraineprendeville @pA1nD In the current UI if the user doesn't have unsynced drafts or whatever he doesn't see the you have cached data to be deleted modal. So in that case we won't remove the cached images?

**Comment by pA1nD** [comment]
To answer this I would need to better understand the Problem. Why do we want to delete cached images on logout? @Danman7

**Comment by Danman7** [comment]
@pA1nD Because we delete everything on logout.

**Comment by Danman7** [comment]
This has been implemented. We show a loading modal while deleting.
