### ISSUE TITLE
Families Profile Screens - Read Only

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#304]
This task is to create the family profile screen.

![Screen Shot 2019-01-23 at 10.00.05.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/d9e1189d-4786-4ac6-b423-3a810db6d1b2)

**Comment by Danman7** [comment]
This includes the +N circle for the family lists.
