### ISSUE TITLE
Wrong characters in the FUSAI survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#308]
**Describe the bug**
Whenever a word has a typed accent on a vowel, it shows a strange symbol.

**To Reproduce**
In the FUSAI survey, in the section of the indicators. The text has these symbols. 

**Smartphone (please complete the following information):**
 - Device: Samsung tablet
 - OS: Android 5.1.1

**Comment by IvaKop** [comment]
Dublicate of https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/381
