### ISSUE TITLE
App allows invalid data input. Family count 

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#309]
###Problem

It's possible to enter two as a count in family member but not enter the name and continue.

#### Steps to reproduce 
Take a survey.
Select 1 in "number of people living in this household" and continue. 

Leave the draft and save it. (important step that allows the glitch) 
Enter it and continue the draft. 
Use the back button on the top to go back. 
Change to two people living in this household (do not enter a name). 
Use the phone's back button. 
You will be able to finish the draft without entering the details of the second person. 

### Expected behavior
When going back with the phones back button, you should not go forward?

**Comment by Danman7** [comment]
Closed in branch.
