### ISSUE TITLE
Create priorities for red indicators 

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#310]
### Problem 

It seems to be possible to create achievements for red / yellow indicators. 

Create a new Lifemap.
Answer one indicator with green.
Exit Lifemap.
Set a achievement on this indicator.
Continue the survey.
Go to the above mentioned indicator and change the indicator to red.
Exit survey.
Now you have a achievement on a red indicator.

### Expected behavior

Don't allow to set priorities / achievements before the Lifemap is fixed. 

OR

Remove the priority / achievement if state is changed from yellow, red to green (or vice versa). Show a warning in this case?

**Comment by Danman7** [comment]
Closed in branch.
