### ISSUE TITLE
Uploading Paraguay indicators

### ISSUE THREAD

**Issue by JuanFerGom** [FundacionParaguaya/MentorApp#317]
Uploading Paraguay's version of indicators to web and app. 

[Indicadores del Semáforo 16 oct 2018 (1).pdf](https://github.com/FundacionParaguaya/MentorApp/files/2807558/Indicadores.del.Semaforo.16.oct.2018.1.pdf)
https://docs.google.com/spreadsheets/d/1jRkSahRJbfDXDyzrw56_YkxIfnBNaqabgKSZG69MLQk/edit#gid=0

**Comment by stacylorraineprendeville** [comment]
Open in https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/392

**Comment by aprojas** [comment]
https://docs.google.com/spreadsheets/d/1jRkSahRJbfDXDyzrw56_YkxIfnBNaqabgKSZG69MLQk/edit#gid=0

**Comment by aprojas** [comment]
It is finished!
