### ISSUE TITLE
Wrong language when choosing Spanish

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#318]
**Describe the bug**
When choosing the language Spanish on the left side. The names below are are in English, it says "Dashboard" and "Create a life map", but then it says "Cerrar sesión". 

**To Reproduce**
1. Open the app
2. Tap on "ESP" on the left hand corner
3. See wrong language below

**Expected behavior**
It should read "Tablero" instead of "Dashboard"
It should read "Crear un Mapa de Vida" instead of "Create a life map"

**Comment by IvaKop** [comment]
Dublicate of #162

**Comment by aprojas** [comment]
This still happens. I logged in today and the left hand dashboard is still in English when I choose Spanish

**Comment by IvaKop** [comment]
The issue is closed because it's a duplicate of another one, which means we are tracking this bug elsewhere.
