### ISSUE TITLE
Progress Bar in Life Map Creation to be within all Screens

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#325]
The progress bar is currently visible ONLY within the indicators pages
This issue is to join the whole of the lifemap process from beginning to end - Therefore the progress bar will run throughout ALL screens

![Screen Shot 2019-01-30 at 15.52.02.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/79794ee6-2de2-49a3-a4a2-1691a9e762fd)

**Comment by stacylorraineprendeville** [comment]
@Danman7 Could this be a nice task for the new person - I can review the design work in the next few days and have it for next week...

**Comment by stacylorraineprendeville** [comment]
These screens are now in invision
Please look for the header - progress - bar.

In short
The progress bar begins at
Primary Participant Page
Ends at
Skipped Questions screen

Please note there are design changes in the indicator page within the header.
These may need to incur an increase (as you will see instead of repeating the word "lifemap" we use the dimension name above and the indicator name below)

**Comment by stacylorraineprendeville** [comment]
@Danman7 this is now groomed and unblocked - please review your end

**Comment by Danman7** [comment]
@stacylorraineprendeville We are a bit stuck at this. I will help Vasil out.
