### ISSUE TITLE
N. 1 default for number of family members

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#329]
On the family members screen.
Please auto-select 1 Family member - This would then facilitate people continuing - Those people who do not want the additional family members.

![banco solidario avelina](https://user-images.githubusercontent.com/44477708/52057104-e9144600-2542-11e9-9276-1a6cd29aa8c0.png)

**Describe the solution you'd like**
There are many families with only one member. When arriving to the "number of family members" section, the scroll down bar should already be in number 1 by default. 

**Additional context**
This is a request from Avelina from Banco Solidario.

**Comment by aprojas** [comment]
@egustale

**Comment by egustale** [comment]
If we can set 1 as the default number that will be great. Approved on my side.

**Comment by aprojas** [comment]
This is only requested for the Ecuador survey. Is it going to be ready for the next sprint?

**Comment by stacylorraineprendeville** [comment]
THis is not a task we will complete.
This section of the survey is hard coded and we will not make changes or pre-selects that invalidate data. The correct answer would be "prefer not to say" not "1" for instance,
