### ISSUE TITLE
Elmira - survey stopped message

### ISSUE THREAD

**Issue by stephannman** [FundacionParaguaya/MentorApp#330]
**Describe the bug**
On a tablet, partner was taking the Elmira survey when it suddenly showed a message that said "PS has stopped, send feedback".  This occurred just before the GPS question of the survey.

**To Reproduce**
1. Login and choose Elmira survey
2. Take survey
3. Fill out questions and see if it suddenly stops.

**Comment by Danman7** [comment]
It will be fixed by #262
