### ISSUE TITLE
Making the Poverty Stoplight Balls bigger

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#331]
Wherever the lifemap is visible....(EXCEPT FROM THE SAVE AND CLOSE SCREEN - WHERE THIS WOULD BE TOO LARGE)
Please make the size larger - We change from:
![Screen Shot 2019-01-31 at 19.56.31.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/578280fd-d023-4e07-b058-94a592f5d255)
This was a team request.

**Comment by Danman7** [comment]
@stacylorraineprendeville Can you specify exactly which screens they need to be larger?

**Comment by stacylorraineprendeville** [comment]
Life Map Review Screen is the only place where this is in effect.

![Screen Shot 2019-02-01 at 11.00.26.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/04b5ad37-2b53-4397-b758-39a2d2e65f5f)

For the final save and close screen  - Can we have a responsive version? So as not to allow the "balls" to force the height to be larger than 100%.

![Screen Shot 2019-02-01 at 11.01.11.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/d55bbdf8-d9ff-48f1-81f3-199a739f39dd)
