### ISSUE TITLE
Sync List Improvements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#332]
Iva - This story is to cover notes regarding Sprint 002 Sync Screens.
The main improvement I saw required in the review was the fact that the list on the screen CONTAINS all pending sync - e-g- those with errors as well.
I would hope to review this before the release.

**Comment by IvaKop** [comment]
@stacylorraineprendeville Please specify this further - design + specs. Let's discuss. Thanks!
