### ISSUE TITLE
Bug in Family Member text

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#337]
The title of Family Member 6 also appears in the text box when filling in the name of the family member.

![screenshot_2019-02-04-11-35-48](https://user-images.githubusercontent.com/44477708/52217775-e9c91700-2877-11e9-8ea3-6ae486b3d218.png)

**Comment by aprojas** [comment]
This also happens with other surveys, such as the UK one. 
![screenshot_2019-02-04-12-30-30](https://user-images.githubusercontent.com/44477708/52224264-5519e580-2886-11e9-8acc-a0efbd9a9296.png)

**Comment by Danman7** [comment]
I know the reasons. It doesn't happen for these cases only.
