### ISSUE TITLE
Required App Updates and UX

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#345]
Inform the user to update the app. As we can't avoid breaking changes in the app, we should give pre-notice to the users of around 2 weeks to 1 months. There should be a release that will be able to cope with the breaking changes without them being applied, yet. For this reason, we introduce a protocol (tbd) how the frontend can get information of the availability of an important update. There is a design to show this information and ask the user to update the app.

**Comment by stacylorraineprendeville** [comment]
Push Notifications would do this
Email Notification implemented on the server - Send automatically.

**Comment by Danman7** [comment]
Further clarification needed.

**Comment by Danman7** [comment]
@stacylorraineprendeville Can you specify which channels should we use for this? Emails,something in app? As this will probably turn into an spike.

**Comment by stacylorraineprendeville** [comment]
@Danman7 I am converting this to an epic

**Comment by Danman7** [comment]
@stacylorraineprendeville Could you say, apart from the messages, what else should be related to this so I can create the issues.

**Comment by stacylorraineprendeville** [comment]
@Danman7 perhaps it is more @javierpf that can explain what is related to this. It should all be within a epic for survey versioning

**Comment by stacylorraineprendeville** [comment]
@javierpf I created a new EPIC for the back end - I think we should everything related to this over there and close this epic as it is not only a mentor app issue.
OK?
Here is the new epic - Can you populate with the other issues that are required
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/822
