### ISSUE TITLE
Link 2 questions

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#347]
The questions:
How many people live in your household?
And
How many people in your household have an income?
should be linked in some way. 
For example, it should throw an error message if the amount of people generating income in the household are more than the amount of people who live in the household. 

Or else this could easily lead to inconsistencies in the reports accidentally.

**Comment by stacylorraineprendeville** [comment]
This is logic again - @aprojas not something that was in the previous app - something we DO want to do....but it is not our priority for the next few sprints.
