### ISSUE TITLE
Ecuador survey: "Family Details" in wrong language

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#348]
It should be in Spanish.
![screenshot_2019-02-05-11-58-11](https://user-images.githubusercontent.com/44477708/52281773-8dc8c600-293d-11e9-8751-de2db3b194e6.png)

**Comment by aprojas** [comment]
Just ignore this, since it should be deleted anyway.

**Comment by stacylorraineprendeville** [comment]
@this is important!

**Comment by IvaKop** [comment]
@stacylorraineprendeville this is not a bug on the frontend, the title (topic) comes from the server.
