### ISSUE TITLE
Dashboard button doesn't work when on a survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#352]
When on the middle of a survey, and when I click on Dashboard from the menu, nothing happens. A pop-up message similar to when you click on the exit button should appear. 

![screenshot_2019-02-06-16-34-53](https://user-images.githubusercontent.com/44477708/52370505-d9f53280-2a31-11e9-9439-a482a23cb2a6.png)

**Comment by IvaKop** [comment]
@stacylorraineprendeville is this what should happen with the error message?

**Comment by IvaKop** [comment]
blocked by #362

**Comment by Danman7** [comment]
We are working on the blocking issue in the same pull request.
