### ISSUE TITLE
Message error when trying to continue

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#353]
After filling in the field and then clicking on Continue, an error message appears as if I didn't fill in the field. Only if I click somewhere outside of the field, then I can continue with the survey. 
![screenshot_2019-02-06-16-43-17](https://user-images.githubusercontent.com/44477708/52370641-37897f00-2a32-11e9-9993-4beb41fcdd89.png)

**Comment by stacylorraineprendeville** [comment]
@aprojas  are you sure that you are not still within the field when clicking the continue button?

**Comment by stacylorraineprendeville** [comment]
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/mentorapp/335

Duplicated in this

**Comment by aprojas** [comment]
I am in the field when clicking the continue button. So, I can't move forward if I don't leave the field?
