### ISSUE TITLE
Map Visible Offline

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#355]
Show the map even when offline.

**Comment by Danman7** [comment]
I see that the client has requested this in another issue. Here are my findings on how this can be done: https://github.com/FundacionParaguaya/MentorApp/issues/273#issuecomment-456874850

**Comment by Danman7** [comment]
@pA1nD I need to discuss this with you.

**Comment by stacylorraineprendeville** [comment]
@Danman7 @pA1nD Why does this still have a question? Has this been discussed?
