### ISSUE TITLE
Curved Corners on top left and top right of form elements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#356]
Please add top left and top right curve at 8
![Screen Shot 2019-02-10 at 15.49.22.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/b6b9541b-e308-41f6-aba6-16e506ed5f73)

This seems like a small thing but actually it has relevance:

"Rounded corners are easier on the eyes. When we align cards in a row, it’s easier to count the total number of cards when they have rounded corners
It’s because distinguishable edges on the corners of cards guided our eyes to recognize the visual differences. Conversely, cards with sharp corners look identical and unified from each other, which are less likely to attract our attention."

**Comment by Danman7** [comment]
If I understand the title correctly (literally), this should be rather simple.
