### ISSUE TITLE
Multi Language and Single Language Surveys

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#358]
If Surveys are NOT translated and are to given locally WHY do we need the language interchanger.

What are our options?

**Comment by Danman7** [comment]
There is static text, not part of the surveys, like navigation and Dashboard. If the is multiple language needed for the surveys, this has to come from the server.

**Comment by Danman7** [comment]
@stacylorraineprendeville Do you need any further info here? I'm not sure what you mean by our options. To do what?

**Comment by stacylorraineprendeville** [comment]
@Danman7 I do not think we should offer a language switcher in the APP. I think we should state whcih language the survey is in and when the mentor logs in or the users assigned to that survey they should just receive the app in that language - What are the implications @diegotorrespy @JDelPuerto

**Comment by Danman7** [comment]
Closing due to lack of communication and updates.
