### ISSUE TITLE
Allowing families to have no content/life map

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#359]
### Problem:

We have two databasaes. The GQL (Mentor App) reads from DB schema B and the web app creates all data in DB schema A.

We have a script which syncs B to A but not A to B.

This causes that data that was created in A (Original Web App) would not show up in B (Mentor App).

This is blocking the development of the family related screens.

This is not a teechnical problem but a UX issue as it might cause confusion.

### Suggestion:

Analyze where the use case is given that families are created in the web app and need to show up in the mentor app.

Show a warning for families that have no attached survey, that data that was created in the web app might now show up in the mentor app.

**Comment by stacylorraineprendeville** [comment]
This could be solved with an Error message in the famiies list - It would need to be in the families list as we would not have socio economic data either - 
How much of a corner case is this? Eduardo.......

**Comment by stacylorraineprendeville** [comment]
This will now be solved - Hoewever via the patch in issue 424
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/424

However do we still need this error message

Can a family have no lifemap - In the database?
Methodologically?
