### ISSUE TITLE
An Accessible Android App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#365]
Here we will follow the Accessible Android App specification at:
https://developer.android.com/training/accessibility/testing

- Manual testing: Interact with your app using Android accessibility services.
- Testing with analysis tools: Use tools to discover opportunities to improve your app's accessibility.
- Automated testing: Turn on accessibility testing in Espresso and Robolectric.
- User testing: Get feedback from real people who interact with your app.

Manual Testing
Initially we will ask the developers to install anything necessary for Talkback Functionality.
Then we will conduct a manual Talk Back Test.
A quick run through of this has already shown that we will need to amend labels (e.g. Asterisk should  say required element) This manual report will create the first step of the recommendations.

Other services will need to be discussed.
-----------------------------------------------
Testing with Analysis Tools
We will then complete tests with Accessbility Scanner. A quick run through of this tool has already shown that various design elements will require minor changes.

Other services will need to be discussed.

-----------------------------------------------

Automated Testing
To be discussed with the tech team.

-----------------------------------------------

User Testing
UX Project

**Comment by Danman7** [comment]
@stacylorraineprendeville This issue looks complete. We should reevaluate and add new tasks for what's missing.

**Comment by Danman7** [comment]
Epic is complete.
