### ISSUE TITLE
Manual testing with Talkback

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#366]
TalkBack is Android's built-in screen reader. When TalkBack is on, users can interact with their Android device without seeing the screen. Users with visual impairments may rely on TalkBack to use your app.
Turn on TalkBack
1. Open your device's Settings app.
2. Navigate to Accessibility and select TalkBack.
3. At the top of the TalkBack screen, press On/Off to turn on TalkBack.
4. In the confirmation dialog, select OK to confirm permissions.
Note: The first time you enable TalkBack, a tutorial launches. To open the tutorial again in the future, navigate to Settings > Accessibility > TalkBack > Settings > Launch TalkBack tutorial.
Explore your app with TalkBack
After TalkBack is on, there are two common ways to navigate:
* Linear navigation: Quickly swipe right or left to navigate through screen elements in sequence. Double-tap anywhere to select.
* Explore by touch: Drag your finger over the screen to hear what's under your finger. Double-tap anywhere to select.
To explore your app with TalkBack, complete these steps:
1. Open your app.
2. Swipe through each element in sequence.
3. As you navigate, look for the following issues:
    * Does the spoken feedback for each element convey its content or purpose appropriately? (Learn how towrite meaningful labels.)
    * Are announcements succinct, or are they needlessly verbose?
    * Are you able to complete the main workflows easily?
    * Are you able to reach every element by swiping?
    * If alerts or other temporary messages appear, are they read aloud?
For more information and tips, refer to TalkBack user documentation.

**Comment by stacylorraineprendeville** [comment]
@aprojas Please review in English and Spanish - How does the APP respond?????? The multi lingual environment is a challenge.

**Comment by stacylorraineprendeville** [comment]
@aprojas any update on this?

**Comment by aprojas** [comment]
Talkback Report:
https://docs.google.com/document/d/19tlnHh7tFK5rpj9IQcBFYX_qNaxASXpqx2x25zrfzB8/edit?usp=sharing
