### ISSUE TITLE
New titles for the surveys

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#378]
We need to establish a title protocol for each Survey name. 
It will be like this: [Country/State - Hub]

Can we change what we have now in this order?
(edited)

OFFICIAL NAMES

Argentina - Fundación Irradia
Colombia - Fundefir
Ecuador - Banco Solidario
El Salvador - FUSAI
Mexico - USEM
Paraguay - Activate, FUPA
Sierra Leone - WARC
United Kingdom - Signal
USA California - UCI & Salvation Army
USA Elmira - CCE Chemung

**Comment by stacylorraineprendeville** [comment]
This is a backend task @aprojas Can you re-assign?

**Comment by stacylorraineprendeville** [comment]
@aprojas Do we really need the word stoplight repeated?

**Comment by aprojas** [comment]
The word stoplight is used instead of survey!

**Comment by aprojas** [comment]
Ok. Let's do it without the word "Stoplight"

**Comment by aprojas** [comment]
ENGLISH:

1. Colombia - Fundefir
2. Ecuador - Banco Solidario
3. El Salvador - FUSAI
4. Paraguay - Fundación Paraguaya
5. Sierra Leone - WARC
6. United Kingdom - Signal
7. USA California - UCI & Salvation Army
8. USA Elmira - CCE Chemung

SPANISH:

1. Colombia - Fundefir
2. Ecuador - Banco Solidario
3. El Salvador - FUSAI
4. E.E.U.U. California - UCI & Salvation Army
5. E.E.U.U. Elmira - CCE Chemung
6. Paraguay - Fundación Paraguaya
7. Reino Unido - Signal
8. Sierra Leona - WARC

**Comment by aprojas** [comment]
OFFICIAL NAMES

Argentina - Fundación Irradia
Colombia - Fundefir
Ecuador - Banco Solidario
El Salvador - FUSAI
Mexico - USEM
Paraguay - Activate, FUPA
Sierra Leone - WARC
United Kingdom - Signal
USA California - UCI & Salvation Army
USA Elmira - CCE Chemung

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #520](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/520) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #519](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/519) via [**ZenHub**](https://www.zenhub.com/)
