### ISSUE TITLE
Design Amendements to the Family Member Pages

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#379]
Add decorative element and icon to the Family Member page + Birthdates/genders

![Screen Shot 2019-02-14 at 16.18.49.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/bab7216c-9660-44c3-9959-46d218de12e9)

**Comment by Danman7** [comment]
The decoration is part of #371. The Icon will be added here so this is a 1.
