### ISSUE TITLE
Error Messaging and the App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#384]
Some work has taken place here:
https://mm.tt/1215425417?t=IM2lPi2B0l
to be completed

**Comment by Danman7** [comment]
The way this is structured - it should be an epic. So we know what is done exactly, we should look at that. And this will not make it into sprint 7.

**Comment by stacylorraineprendeville** [comment]
@Danman7 @pA1nD This has been assigned to Bjorn since Sprint 004.
If you want an epic - make one!

**Comment by Danman7** [comment]
@stacylorraineprendeville I no longer have notion of what this issue is about. Link above sends me to a blank page. Server error messaging has been changed a few times in last months.
