### ISSUE TITLE
Include punctuation marks for thousand position

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#385]
Include commas (in case if it’s English) or periods (in case if it’s Spanish) to signal the thousand position. For example: “1,000” or “1.000”.

**Comment by Danman7** [comment]
@aprojas @stacylorraineprendeville Where would this be applicable? Which places will show such numbers?

**Comment by aprojas** [comment]
Every country uses or a comma or a period to point out the thousand position. For example: You should write USD 2,000. Not "USD 2000". 

In the future, it would be great if by choosing first the currency in which you receive your income, it would automatically add or commas or periods when filling in the numbers.

**Comment by aprojas** [comment]
Just to know if there was an update on this. 
Was the question answered? @stacylorraineprendeville @Danman7

**Comment by Danman7** [comment]
@aprojas So sorry. I wasn't available for proper grooming last sprint.

We are getting closer to the answer. It's just a bit abstract now and in order to properly estimate it I need structure for the commas. We have number fields that can accept thousands only in the socio economic questions section. By your response about currencies l believe we are talking about that.

Is this only about specific fields like currencies or any other field like for example a possible question of how many litres of water you are consuming? I need to know in order to decide if we need Diego for this.

**Comment by aprojas** [comment]
Exactly! It would mainly be in the socioeconomic section, in order to avoid mistakes by the person taking the survey. 
I can consult your question to the methogological committee about the other types of questions like litres. But I think this is specially required for currencies only. I can upload a video here to show how it could look like. 

However, we should just prepare for having this option of "thousand" position for any other necessary future requests!

**Comment by aprojas** [comment]
@Danman7 Just as you requested, these are the fields that need the dots:
(I'll attach screenshots just in case)

In the GECO survey:
1) Salario mensual
2) Negocio familiar
3) Otros miembros ¿cuantos ingresos?
4) Subsidios del gobierno

![Screenshot_2019-04-04-09-53-45](https://user-images.githubusercontent.com/44477708/55563791-91ba5f80-56c4-11e9-9093-b3d9f7f75eb7.png)

In the USEM survey:
1) Ingreso mensual
2) Monto de ingresos de otros miembros

![Screenshot_2019-04-04-09-59-22](https://user-images.githubusercontent.com/44477708/55563851-a991e380-56c4-11e9-9790-6a5cfea55ddd.png)

In the UK survey:
1) How many people in your household have an income? (This would not necessarily arrive to a thousand, but it's still a number field)
2) Gross monthly household income
* For example, I believe that UK uses commas to separate the thousand position.

**Comment by stacylorraineprendeville** [comment]
@aprojas this would need to be on a per survey basis then ? Because telephone number is a numerical field and does not have this
It would need to be noted in the new survey spreadsheet (speak to Stefanie) and given as content- Each current survey would need to be reviewed for this
@Danman7 ON HOLD

**Comment by Danman7** [comment]
I would agree with Stacy. Ana has described this perfectly for a human to understand, but the per survey logic is vague and complicated. I will give this a though.

**Comment by aprojas** [comment]
Ok! I will ask Replicas to add them in the spreadsheet for all existing surveys, and then I'll add them here as a list, indicating if it should be commas or periods. 
@Danman7

**Comment by aprojas** [comment]
Can we have a thorough discussion on what is needed for this? 
Because I don't remember, was it that it should be in the spreadsheet?

Maybe we don't need to make it commas (,) or periods (.) for one survey or another. Maybe we can just choose one for all. I have some personal finance apps in my phone, and even though it says PYG (Paraguay) next to my amount, it still separates the thousand position in commas. Even though we use periods here. 

Could this be an option? @stacylorraineprendeville 

Not asking for the near future solution for this, just to take into account somehow :)

**Comment by Danman7** [comment]
This is estimated based on discussion in https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/809

**Comment by zommerberg** [comment]
So we need a proper implementation from the back end, right?

**Comment by pA1nD** [comment]
@zommerberg 

some links:

https://www.varvet.com/blog/format-numbers-in-input-fields-using-react/
https://medium.com/@nidhinkumar/react-js-number-format-and-styling-a1a6e211e629
https://www.varvet.com/blog/format-numbers-in-input-fields-using-react/ (not so relevant)

also: https://www.google.com/search?q=react+number+formatting
