### ISSUE TITLE
Amend Paraguay Survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#393]
We need to add some questions in the socioeconomic section. And delete some. 
Nancy Ramos made the changes in a second sheet. 

https://docs.google.com/spreadsheets/d/1jRkSahRJbfDXDyzrw56_YkxIfnBNaqabgKSZG69MLQk/edit?usp=sharing_eil&ts=5c673482

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy Please do not add to the sprint without me!
I am trying to organise that this task is clearly defined to save you time.

**Comment by stacylorraineprendeville** [comment]
@aprojas @diegotorrespy 
1. Please define the task properly - NOT "nancy made changes in the second sheet". List the changes in the issue.
2. Do not add to the sprint without passing by the PO - otherwise we invalidate the sprint planning if the team add without approval - and we have a situation where poorly defined work affects the team

**Comment by aprojas** [comment]
1. FAMILY DETAILS SECTOR (DATOS DE LA FAMILIA)
a) areaOfResidence - MAKE OBLIGATORY
b) housingSituation - MAKE OBLIGATORY
c) memberDisability - remains the same
d) memberDiedBefore5 - MAKE OBLIGATORY
e) familyCar - MAKE OBLIGATORY

ADD AFTER THE /familyCar/, the following question:

f) ¿Mi familia accede al servicio de agua con?

with drop-down list:
- ESSAP
- SENASA
- Junta de Saneamiento
- Red Comunitaria
- Red Privada
- Pozo artesiano
- Otro
- No sé 
- Prefiero no responder
- No tengo acceso a agua

2. ADD THE EDUCATION PER MEMBER LIKE THE ARGENTINA SURVEY:
a) ¿Actualmente estudia?
- Si
- No
- No se
- Prefiero no responder

b) Nivel actual o nivel máximo alcanzado
- Pre-Primaria 
- Primaria 
- Secundaria 
- Técnico Superior a la secundaria 
- Universitaria 
- Pos Grado 
- No sé 
- Prefiero no responder

c) Grado actual o grado máximo alcanzado
- Pre-Primaría
- Primer Grado - Año
- Segundo Grado - Año
- Tercer Grado - Año 
- Cuarto Grado - Año 
- Quinto Grado - Año 
- Sexto Grado - Año 
- Septimo Grado 
- Octavo Grado  
- Noveno Grado 
- 1 curso 
- 2 curso 
- 3 curso 
- No sé 
- Prefieron no responder

3. DELETE
The slide of "Nivel de Educacion de la persona con más estudios en la familia"

4. INCOME & EMPLOYMENT
- activityMain - MAKE OBLIGATORY*
- currency - MAKE OBLIGATORY*
- householdMonthlyIncome - MAKE OBLIGATORY*
- otherMembersIncome - MAKE OBLIGATORY*
- receiveStateIncome - remains the same

5. ADD NEW SLIDE
TITLE: Para el jefe del hogar

a) ¿Trabaja por lo menos 30 horas semanales? (MAKE OBLIGATORY)
- Sí / No / No lo sé

b) ¿Si no trabaja o trabaja menos de 30 horas semanales, quisiera trabajar o trabajar más? (Not obligatory)
- Sí / No / No lo sé

c) ¿Al menos la persona percibe el salario mínimo? (MAKE OBLIGATORY)
- Sí / No / No lo sé

TITLE: Para la pareja del jefe del hogar
*all of these questions are optional, not obligatory.

a) ¿Trabaja por lo menos 30 horas semanales?
- Sí / No / No lo sé

b) ¿Si no trabaja o trabaja menos de 30 horas semanales, quisiera trabajar o trabajar más? 
- Sí / No / No lo sé

c) ¿Al menos la persona percibe el salario mínimo?
- Sí / No / No lo sé

**Comment by aprojas** [comment]
If there are any questions regarding what I wrote, just ask me!

**Comment by aprojas** [comment]
CHANGE:
- In Family Details make mandatory every question EXCEPT the disability one. (It's in the spreadsheet, just in case)
![2019-03-08 (3).png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/956793e0-e2b1-4f81-af29-ddec4b5c23b5)

EDUCATION
BUG: Nothing appears and I can't continue when clicking on continue. 
![2019-03-08 (4).png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/8915127c-4071-4cb7-9c89-9dae73bf02ba)
