### ISSUE TITLE
Title in English when still choosing Spanish

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#394]
The "Please read carefully before using this application" is still in English even though I chose Spanish before starting a survey. 

![screenshot_2019-02-18-09-14-59](https://user-images.githubusercontent.com/44477708/52950497-1db73880-335e-11e9-905f-bc0ca1e7bbb3.png)

**Comment by IvaKop** [comment]
@stacylorraineprendeville @aprojas this title comes from the server therefore it is not an app bug. It doesn't matter what language you choose on the app, the terms will come in the language of the survey.

**Comment by aprojas** [comment]
And can it still be changed anyways?

**Comment by IvaKop** [comment]
Yes, it can, on the server. It's a job for @diegotorrespy .

**Comment by Danman7** [comment]
@aprojas @stephannman The survey's terms and privacy policies are not bilingual. We need this to come from the server as Iva has said. Since there is no discussion when this will happen I'm putting this in the icebox.

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you review if this is still happening?

**Comment by aprojas** [comment]
This does not happen anymore! I am going to close it. 
@stacylorraineprendeville
