### ISSUE TITLE
"Other" option confusing

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#395]
The "other" option in "choose gender" is quite confusing because if you choose that option, you can't specify which. Or was this already previewed like this?
![screenshot_2019-02-18-09-22-41](https://user-images.githubusercontent.com/44477708/52950750-d41b1d80-335e-11e9-9679-6fe882a25464.png)

**Comment by stacylorraineprendeville** [comment]
@aprojas I am closing this - As explained in other tickets this is a duplicate. We are grooming this but it is not a priority due to the backlog and the fact clients DID NOT have this previoulsy.
