### ISSUE TITLE
Offline Maps and Localised Surveys

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#400]
In order for the map to function offline - a version of the map MUST be downloaded.
This is standard to Google Maps.

In order to ensure we do not use a high amount of MB´s we must restrict the size of the maps. The way to restrict the size of the maps is to localize - i.e. provide a pre-determinate area for each survey.

This is a methodology team task for the future but in this first instance we must define our necesities technical and help the team with how to do this.
This requires some time for Dan/Ana/Stacy before implementation....

**Comment by stephannman** [comment]
Please note that two partners have vocalized concerns on this feature after viewing their reports and noting that the GPS did not accurately capture families' locations.

**Comment by stephannman** [comment]
When taking the Elmira survey on a Samsung tablet, OFFline, the map does not usually/ever load. An error appears that says "Hmm! Unfortunately we cannot load the map..."

When taking the Elmira survey on a Samsung tablet, ONline, the map does load. But even then, the app doesn't always save the appropriate coordinates. In Elmira's case, they've administered about 70 surveys and only about 10 of them saved the coordinates appropriately. The remainder either say "Null" or defaulted to Elmira's office address.

**Comment by stacylorraineprendeville** [comment]
Pre download an specific area of the map

We need square area:
1. Co-ordinates - Top left - Latitude/Longitude
2. Co-ordinates - Bottom Right - Latitude/Longitude
3. Zoom Levels (Perhaps) Or we use a minumum zoom level of 15 (Zoom Out)/17(Zoom in) -
