### ISSUE TITLE
FP Admin Root Account

### ISSUE THREAD

**Issue by stephannman** [FundacionParaguaya/MentorApp#401]
From the FP Admin Root account, there seem to be functionalities missing or that have changed. In the past, I (Stephanie) could login into this Admin Root account to 1st: Create a Hub account; 2nd: assign a survey to that account; 3rd: create a Hub Admin user account. Then I could 4th: login to the newly created Hub Admin user account so that I could 5th: create an Organization and then 6th: create an Organization Admin account. Then I'd log into the new Organization Admin account to 7th: create a Survey user account. At the time of creating a survey user account, the survey user would immediately have access to the survey that the Hub had granted the organization access to.
As of recently, it seems that steps 1 - 7 are still possible BUT the survey user does not have any surveys assigned to them. The tech team (Diego or others) has to do something from their own account to enable access.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #438](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/438) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stephannman** [comment]
@diegotorrespy @stacylorraineprendeville @aprojas To be able to deliver to UK on issue #309, perhaps we consider a work-around where we don't actually fix the bug that's not allowing organizations to assign surveys to survey users. Instead, somebody (@diegotorrespy ?) just assigns the survey user the survey from the back end.
