### ISSUE TITLE
Rollover on Skipped Indicators BUG

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#403]
@stacylorraineprendeville commented on [Tue Feb 19 2019](https://github.com/FundacionParaguaya/stoplight-web/issues/151)

When using the indicator pages the rollover/onclick effect of the checkbox appearing...works on the first few pages - then stops working.

**Comment by Danman7** [comment]
@stacylorraineprendeville We were unable to reproduce this on any device we have. Even the emulators. Every time we touch  hold the stoplight question image we see the checkbox. Can you provide further feedback?

**Comment by stacylorraineprendeville** [comment]
No @aprojas unless you have further reports of seeing this I am closing this issue.

**Comment by aprojas** [comment]
Not anymore!
