### ISSUE TITLE
IRRADIA Argentina Survey: Change text in some indicators.

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#408]
This is NOT urgent. I will add it for the next sprint. 
They want to change some words that are only in one gender, or add some new words.
I'll add the changes when the team sends it to me.

**Comment by diegotorrespy** [comment]
@aprojas Could you specify which indicator has to change and the text that needs to be replaced please?

**Comment by aprojas** [comment]
Juanfer is going to send me this! I'll upload it asap when he does.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #525](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/525) via [**ZenHub**](https://www.zenhub.com/)
