### ISSUE TITLE
Internationalization of the date format

### ISSUE THREAD

**Issue by IvaKop** [FundacionParaguaya/MentorApp#410]
Currently in the application the dates are just formatted in English. When the language is switched to Spanish, the date format should change as well to the Spanish one. Spanish format to be defined by @aprojas.

Enero - Ene
Febrero - Feb
Marzo - Mar
Abril - Abr
Mayo - May
Junio - Jun
Julio - Jul
Agosto - Ago
Septiembre - Sep
Octubre - Oct
Noviembre - Nov
Diciembre - Dic

Format remains Dic 14, 2017

**Comment by aprojas** [comment]
It should read: "Creado el:"


Long version:
2 de marzo de 2019
(the month should always be lower case)

Short version:
2/MAR/2019

Let me know which version suits the coding system better.

**Comment by stacylorraineprendeville** [comment]
Ladies - The UX of the date has been decided.
We go
Month (Written e.g. Mar for March
Day - two digit number
Year

We do not change format of our dates for languages.
The above format is industry standard - Reason is that if not people get confused regarding month.

**Comment by aprojas** [comment]
Ok. Good to know this!
