### ISSUE TITLE
Reports: family address not downloading

### ISSUE THREAD

**Issue by stephannman** [FundacionParaguaya/MentorApp#414]
When I download reports as an Organization or Hub user, I should be able to see answers to all questions in the survey. In all surveys, families are asked to share their country of residence and physical address (in the same section as the gps). But when I download the report, there is no column with those questions and answers, even though there should be.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #470](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/470) via [**ZenHub**](https://www.zenhub.com/)
