### ISSUE TITLE
Ability to delete users

### ISSUE THREAD

**Issue by stephannman** [FundacionParaguaya/MentorApp#421]
As a Hub, logged into the web platform, 
I can create new Organization users and Survey users.
I can also partially edit them, that is: I can edit the associated email address and I can elect to activate or deactivate the account.
I would like to be able to edit the name and delete the account (unless there are implications for deleting accounts).

As an Organization, logged into the web platform, 
I can create new Survey users.
I can also partially edit them, that is: I can edit the associated email address and I can elect to activate or deactivate the account.
I would like to be able to edit the name and delete the account (unless there are implications for deleting accounts).

Note: not urgent.

**Comment by aprojas** [comment]
Is this going to be possible? Maybe they can have the button to "delete" but it is only just hidden for them. 
If it's not going to be possible, then I should tell this to Replicas. 
If it is, we need a time estimation.

**Comment by stacylorraineprendeville** [comment]
@aprojas No podemos añadir funcionalidad para un "admin" users ahora mismo
Danos una lista y lo hacemos al nivel servidor

**Comment by stephannman** [comment]
Okay, gracias. Yo te doy una lista o Ana te da una lista? Si es yo, avisame que tipo de lista.

**Comment by aprojas** [comment]
Hola Steph! Pasenme la lista de los usuarios que necesitan ser borrados. Coordina con Juanfer para enviar todos. Seria nombre de usuario, y hub correspondiente. @stephannman

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #729](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/729) via [**ZenHub**](https://www.zenhub.com/)
