### ISSUE TITLE
UX - Potential Issue in reviewing draft and location

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#423]

**Comment by Danman7** [comment]
@stacylorraineprendeville No info to groom.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/UX-and-Design #21](https://github.com/FundacionParaguaya/UX-and-Design/issues/21) via [**ZenHub**](https://www.zenhub.com/)
