### ISSUE TITLE
Automatic upper case on Family Member Names

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#424]
Upper case should be automatic when writing on a field. For example if I write my name on the name field with the app, it writes "ana", not "Ana". Is this something that can be fixed from the app?

**Comment by stacylorraineprendeville** [comment]
@Danman7 is there a capitilise feature  - there is in CSS BUT I think it capitalises every word

**Comment by Danman7** [comment]
@stacylorraineprendeville @aprojas We can set it up, but I need to be sure which fields this covers. All text fields? Document numbers? Probably not. Can you specify if this is for names only?

**Comment by aprojas** [comment]
I think it's any field. 
If I'm correct, it should capitalize the BEGINNING of a sentence. Just as you are writing a text message on your phone. 
Right?

**Comment by stacylorraineprendeville** [comment]
hmmm I need to think about this...on hold for now

**Comment by Danman7** [comment]
@stacylorraineprendeville We can implement this for family member names at least.

**Comment by stacylorraineprendeville** [comment]
@Danman7 Ok great - going to change the ticket name to capitilas Family member names (it will be both - First name and surname)

**Comment by Danman7** [comment]
It seems react-native has a problem with uppercase and duplication of the first letter: https://github.com/facebook/react-native/issues/11068

**Comment by Danman7** [comment]
We have fixed this in latest release.

**Comment by dhvector** [comment]
What action was taken? It's not clear here, as #11068 is still open
