### ISSUE TITLE
Delete USEM User

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#426]
Usuario: Nelly Hernandez
Correo: nelly.hernandez@usem.org.mx

USEM Mexico

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #530](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/530) via [**ZenHub**](https://www.zenhub.com/)
