### ISSUE TITLE
Conditional socio economic survey questions - Front-end

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#428]
Conditional logic includes socio-economic section questions being asked only if the survey taker has answered another question in a specific way. We need an API structure for this that would pass the conditions as logic in the survey.

A survey looks something like this like this:
```json
{
  "id": 1,
  "surveyConfig": {},
  "surveyEconomicQuestions": []
}
```
We should modify what comes in the `surveyEconomicQuestions` array in the form of questions.

## Questions depending on the age of a participant
Here is an example question that is dependent on age.
```json
{
  "answerType": "select",
  "codeName": "areaOfResidence",
  "topic": "Family Details",
  "required": false,
  "forFamilyMember": false,
  "questionText": "bla bla",
  "options": [
    { "text": "Urban", "value": "URBAN" },
    { "text": "Rural", "value": "RURAL" }
  ],
  "condition": {
    "type": "age",
    "value": 17,
    "operator": "above"
  }
}
```
**Whose age are we after?** We take a look at the `forFamilyMember` property. If that is `false` then we look at the age of the primary participant. If it's `true` this `areaOfResidence` question will be asked to each person in the family and we will look for the age of each person and apply the condition for them individually.

**We assume the value is in years.**

We are going to ask this question only if the age of the given person is 18 or greater. Since we can only get age trough `birthDate` and that comes in the form of a milliseconds number, we will have to calculate and compare. That is why the value is in years and then apply the front-end validation.

So in the following example draft:
```json
{
  "draftId": 4,
  "surveyId": 1,
  "economicSurveyDataList": [],
  "indicatorSurveyDataList": [],
  "familyData": {
    "countFamilyMembers": 2,
    "familyMembersList": [
      {
        "firstName": "Juan",
        "lastName": "Perez",
        "gender": "M",
        "birthDate": 12345,
        "firstParticipant": true,
        "socioEconomicAnswers": []
      },
      {
        "firstName": "Ana",
        "lastName": "Perez",
        "gender": "F",
        "birthDate": 12345,
        "firstParticipant": false,
        "socioEconomicAnswers": []
      }
    ]
  }
}
```
We look for Juan's `bithDate` if question's `forFamilyMember: false` and for both Juan's and Ana's if `forFamilyMember: true`.

What if we want the age less than or equal to? We can set upon the following operator types:
- `above`
- `equal`
- `below`

So fi the question should be asked to someone below 40 it would be like this:
```json
{
  "codeName": "areaOfResidence",
  "condition": {
    "type": "age",
    "value": 40,
    "operator": "below"
  }
}
```
## Questions depending on the answer of another question
What if we have to ask a question only if another socio economic question has been answered in a specific way? We have the following scenarios.
### Select and string questions
Here is a regular select dropdown type question as it comes from a survey:
```json
{
  "answerType": "select",
  "codeName": "educationClientLevel",
  "forFamilyMember": false,
  "options": [
    { "text": "Incomplete", "value": "INCOMPLETE" },
    { "text": "complete", "value": "COMPLETE" }
  ]
}
```
Then we want to ask the question (For example, what diploma do you have?) only if the above is answered with `COMPLETE`. It will look like this.
```json
{
  "answerType": "string",
  "codeName": "diploma",
  "condition": {
    "type": "socioEconomic",
    "codename": "educationClientLevel",
    "value": "COMPLETE"
  }
}
```
In the front-end this question will look if `educationClientLevel` has been answered with `COMPLETE` and only then display it. Same logic applies to any string typed questions - we check if the `condition.value` is equal to the answer.

**Where do we check for the answer of the first question?** This again depends on the `forFamilyMember` value of the initial question. Given the following draft:
```json
{
  "draftId": 4,
  "surveyId": 1,
  "economicSurveyDataList": [],
  "indicatorSurveyDataList": [],
  "familyData": {
    "countFamilyMembers": 2,
    "familyMembersList": [
      {
        "firstName": "Juan",
        "lastName": "Perez",
        "socioEconomicAnswers": []
      },
      {
        "firstName": "Ana",
        "lastName": "Perez",
        "socioEconomicAnswers": []
      }
    ]
  }
}
```
If the first question (in this example `educationClientLevel`) has `forFamilyMember: false` we look in `economicSurveyDataList` for the proper key. If `forFamilyMember: false` we look in `familyData.familyMembersList` and the `socioEconomicAnswers` of each individual member.

### Number questions
The logic is much the same as above, but with the added `operator` from age related questions. So if we want to ask for example `How many members of the family are employed?`, only after the participant has answered at least 1 to `How many members of the family generate income?`. We do the following:
```json
{
  "answerType": "string",
  "codeName": "howManyIncome"
},
{
  "answerType": "string",
  "codeName": "howManyEmployed",
  "condition": {
    "type": "socioEconomic",
    "codename": "howManyIncome",
    "value": 0,
    "operator": "above"
  }
}
```
Now `howManyEmployed` will be asked if `howManyIncome` has an answer above 0. Same operators as age related questions will apply.

## Load surveys API call
Here are the changed api calls to get the data.
```graphql
query { surveysByUser { title id minimumPriorities privacyPolicy { title  text } termsConditions{ title text }  surveyConfig { documentType {text value} gender { text value} surveyLocation { country latitude longitude} }  surveyEconomicQuestions { questionText codeName answerType topic required forFamilyMember options {text value} condition } surveyStoplightQuestions { questionText codeName dimension id stoplightColors { url value description } required } } }
```
The new thing is the `condition` inside surveyStoplightQuestions. We don't have any new calls for posting data as the condition is done in the front-end.

**Comment by Danman7** [comment]
The survey that has conditional is available on `testing` environment. It's the Sierra Leone survey with id `2`.

**Comment by Danman7** [comment]
This issue has been partially developed. The logic for questions depending on age is still blocked by having a survey with this information. The other portion of this task is done.

@diegotorrespy @aprojas What is the state of the age related dependency survey?

**Comment by stacylorraineprendeville** [comment]
@aprojas @diegotorrespy please respond today - we cannot loose another day on this - the conditional for Irradia was meant to solve the blocking on AGE
