### ISSUE TITLE
Technical Review and Implementation of Talk Back report Part 1

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#432]
This task concerns implementing changes required in the first set of talk back tasks and creating issues for the remaining tasks.

**Comment by Danman7** [comment]
Completed with this issue:
-  Date should be read completely
- Hamburger menu icon is not expressed 
- ENG/ESP is said like that. should be "change to English, change to Spanish
- Reading modals alous
- DOB abbreviation should be read "Date of Birth"
- Life map visualization: Either we should read each indicator with the color, or we should read an overall visualization when clicking on each indicator button. 

There are issues created for what is left to be done with accessibility.
