### ISSUE TITLE
Changes to Date of Birth Field - Better UX

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#435]
Changes to the current date of birth will make this easier for users
1 field that states Date of Birth - with a three wheel dropdown in one
![Screen Shot 2019-03-14 at 22.28.54.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/89c395a0-cd18-4bbd-8f1e-c8ff2c25a7ab)

![WhatsApp Image 2019-03-14 at 22.31.30 (1).jpeg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/d36a5a8c-49e4-44ef-94fc-b50f4c841cd5)

**Comment by Danman7** [comment]
I can make this, but will need to spend a bit of time to think how to do it properly. It's not as straight forward.
