### ISSUE TITLE
Access drafts that are pending sync

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#443]
In #441 we are setting up the draft begin accessible from the Dashboard when the state is Sync Error and Synced. But when we are dealing with Sync Pending status, there is the danger of us duplicating data. If we are offline and edit a Pending Sync draft and then re-submit it, and do 2 api calls, this can affect the DB.

@diegotorrespy What will happen if there are 2 requests to submit a lifemap for the same family? Can we discuss this at some suitable time?

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy @Danman7 please groom this during this week

**Comment by diegotorrespy** [comment]
@stacylorraineprendeville @danicricco @Danman7 

This will be tricky because two request to submit a lifemap will be create two different family records.

**Here we see two options:**
- Not allow edit option for lifemaps in Sync Pending status.
- Remove the api call from the queue.

**Comment by Danman7** [comment]
@stacylorraineprendeville In this case we should allow the user to go through the lifemap in read only mode. We have the infrastructure, but it's setup for the family details screen, each of which goes back to the family. We will need a different flow. Which is straightforward, but will take some time.

**Comment by Danman7** [comment]
This is solved with #504
