### ISSUE TITLE
Create a reusable decoration component with basic animation (Dashboard only)

### ISSUE THREAD

**Issue by IvaKop** [FundacionParaguaya/MentorApp#45]
![IMG_0810.JPG](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/a848422c-453a-45b9-a7d4-1ff95f1e200d)
[Uploading... Screen Shot 2019-01-30 at 21.00.52.png ]

Create a decoration component that allows adding decorative circles on the different screens of the application like in the image below. The circles should be green yellow and red. 
Dashboard and Choose LifeMap screens first and any other easy picking screens...............

**Comment by stacylorraineprendeville** [comment]
[Uploading... IMG_0810.JPG ]

The other pages could be static with the balls red and yellow turning green randomly at different speeds - This could be then a re-usable element

**Comment by stacylorraineprendeville** [comment]
Careful with the colours on this:
Yellow: F0CB17
Red: E1504D
Green: 50AA47

This is becuase if the colours are to be identified with the PS Indicators - then we should use their colours - NOT the muted ones from the previous design

[Uploading... Screen Shot 2019-02-06 at 15.28.36.png ]
