### ISSUE TITLE
End to End Testing with (Selenium?)

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#450]
End to End testing - Test the whole process life map making and synching.
Every time we deploy a new version it could run a possible test of 50 surveys.

**Comment by Danman7** [comment]
@zommerberg The task here is to first understand end-to-end testing, then to find all plausible and ways to automate them on deploy/merge/whatever. At the end you will share what you found and we will discuss.

@pA1nD Pavel can use as much of your help as you can spare.

**Comment by Danman7** [comment]
@stacylorraineprendeville @pA1nD I'm taking this task over. I will consult with Pavel and see what has been done so far. Moving this from sprint 7.

**Comment by vasildimitroffhristoff** [comment]
Here you can find a basic overview of my research  [E2E Report](https://docs.google.com/document/d/11lxFJ5HLQ5xxQTYqMYc1q-Xof4yJAkAuvAHgk6KlHeQ/edit?usp=sharing)

**Comment by stacylorraineprendeville** [comment]
@vasildimitroffhristoff @Danman7 Was it decided in the meeting to go with Detox?
I have opened a new epic for the tasks required in creating the end to end tests

**Comment by Danman7** [comment]
@stacylorraineprendeville We will first try to integrate Detox. I will write an issue for this and put it in the epic.
