### ISSUE TITLE
Sync screen shows "You are up to date" while having "Sync error"

### ISSUE THREAD

**Issue by vasildimitroffhristoff** [FundacionParaguaya/MentorApp#454]
![53352636_2163814683654809_6293623618454683648_n.png](https://images.zenhubusercontent.com/5c8259898ee9a94fea76d74e/c2421483-73ad-4eed-b029-bf9e8eccffef)

**Comment by stacylorraineprendeville** [comment]
@vasildimitroffhristoff This I presume would then need to be corrected in this sprint - correct?
