### ISSUE TITLE
Offline map in blank

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#458]
When I tried taking an offline survey (Paraguay demo version), the map did not appear, it was just blank. This means that the search location didn't work either.
 ![Screenshot_20190322-140154.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/0208a9fe-f54c-4646-9d59-670faa4fdd17)

**Comment by stacylorraineprendeville** [comment]
@aprojas Can we start using the bug template - Here we have no idea device etc and as the team grows this will become difficult - THe template is within git hub - OPen a new issue from there and it will appear.

**Comment by aprojas** [comment]
Noted! For this one, I used your tablet! @stacylorraineprendeville

**Comment by Danman7** [comment]
Offline map is not working at the moment.
