### ISSUE TITLE
Birthdate title does not appear

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#459]
The birth date (fecha de nacimiento) title in the other members section is not there. 

![Screenshot_2019-03-20-18-31-03.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/74600394-4ed9-44b3-b197-2fccc0937979)

**Comment by stacylorraineprendeville** [comment]
@Danman7 Would like to look into changing the birth date field as per dependant issue - Then is just removes this.

**Comment by Danman7** [comment]
@stacylorraineprendeville Is there an issue for updating the birth date field?

**Comment by zommerberg** [comment]
looks like this is already fixed.The "date of birth" is  appearing properly on the family members screen.

**Comment by aprojas** [comment]
This can be closed since all of it already appears in one screen and it indicates that it's a birthdate.
