### ISSUE TITLE
Maps in the Family Profile Screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#461]
WHEN ONLINE 
A map should be visible in the families profile screen that centres on the locator icon. On Click this takes the user to the location page.

WHEN ANYTHING OTHER THAN ONLINE (OFFLINE/LOCATION)
A static image of a map should be included in the family profile screen. On Click this takes the user to the location page

![Screen Shot 2019-03-25 at 18.38.12.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/b61dce33-6d6f-443d-84ef-5388f3af8766)

Images located at: https://www.dropbox.com/sh/zxu86n2t8h3zpwv/AADaWNC3JtABKA_DjhMTlP4Ha?dl=0

**Comment by Danman7** [comment]
This will be a separate instance of `react-native-maps` with different size and the same settings as the readonly version of the `lifemap/Location.js` component - no scrolling or zooming.

**Comment by stacylorraineprendeville** [comment]
@Danman7 @vasildimitroffhristoff pushed this back to grooming as I changed the spec somewhat....
