### ISSUE TITLE
Android Header Elements Missing

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#465]
As I downloaded form the internal testing track on tuesday 25 march
with the Huawei Device
The Android Header elements have (again!) disapeared from the device.
This issue has a history FYI

These are the elements to which I refer:
![Screen Shot 2019-03-26 at 10.45.57.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ac2dd9c7-e5d5-40d6-87da-6d2ce30bc206)

**Comment by stacylorraineprendeville** [comment]
And we re-open again ;)

**Comment by Danman7** [comment]
@stacylorraineprendeville Please check with the current version. I believe this is fixed since yesterday
