### ISSUE TITLE
The Offline Map - Rethinking, Technical and from a UX Perspectective

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#470]

**Comment by stacylorraineprendeville** [comment]
No closed ;) Until the solution is found

**Comment by Danman7** [comment]
@stacylorraineprendeville My bad. I thought as the meeting is done this is done.

As far as my current technical capabilities goes I am unable to find a solution. Both me and Iva (back in the day) did research on this and it is extremely difficult to do for non Java programmers. I did additional research now and I can't provide a solution that supports old devices.
