### ISSUE TITLE
Technical Review and Implementation of Talk Back report Part 2

### ISSUE THREAD

**Issue by vasildimitroffhristoff** [FundacionParaguaya/MentorApp#474]
1. TalkBack - read every screen's title once loaded.
2. Sync Screen - read the whole screen once.
3. Bug: something is reading Diego's name and random information including csv and family number. This happens randomly.
4. On certain devices, the keyboard doesn't appear & Input fields are not working.

**Comment by Danman7** [comment]
@stacylorraineprendeville Numbers 3 and 4 have to little information to develop. CSV sounds like the web app. Number 1 is too difficult to implement everywhere unless we refactor the navigation: #522. But we have made it read all lifemap screens.
