### ISSUE TITLE
Improvements to Responsive and the Indicator Pages

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#477]
@stacylorraineprendeville commented on [Sat Mar 30 2019](https://github.com/FundacionParaguaya/stoplight-web/issues/219)

Currently the responsive on the indicator pages is not correctly implemented.

The height of the page should NEVER by more that 100% of the screen.
A user should then never have to scroll down when viewing the indicator screens.

In vertical: This works by scaling up the size of the indicator page. When the page can no longer resize in height due to the image width - then either the yellow area can grow to the correct height or space is created top and bottom as shown below.

![Screen Shot 2019-03-30 at 10.13.17.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/dc921488-c312-4086-bc87-603c056cf9b7)

PLEASE NOTE - The Skip this indicator button should be to the right. The info option is not available currently but will be upcoming in a future sprint.

PLEASE NOTE - The height of the yellow area behind the text must be respected! We have instances where low quality resolution images are expanded to the point that the text is on one line - This should not be represented in this way - what should happen is the height of the yellow area should be respected and the text centred vertically. See below:
This then respects the scale up of the image proportionally and ensures the text area does not change in height throughout the survey.[Uploading... Screen Shot 2019-03-30 at 10.50.41.png ]

In horizontal we have the same issues
The height must never be more than 100% to avoid the user having to scroll
See below:
![Screen Shot 2019-03-30 at 10.55.41.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/5c482cfe-33b2-43f6-8e86-76ba33c05627)
![Screen Shot 2019-03-30 at 11.02.34.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/54bd3b4b-921a-4554-b219-1381b77b5455)

ADDITIONALLY:  Please make the text slight larger in the indicator pages and change the font to poppins
ADDITIONALLY:  Please add the slight curved corners top and bottom to the indicators - as per the design

**Comment by Danman7** [comment]
@stacylorraineprendeville While developing this, we've run into use cases not described here.

For example there are questions with so much text, that there is barely room for the image:

![Screenshot_20190412-155212](https://user-images.githubusercontent.com/3336245/56039742-a25e7b80-5d3d-11e9-97c6-97fcd28a6c63.png)

Yellow image next to this one has even more text, so it's not reducing the size of the green box.

**Comment by Danman7** [comment]
We can implement a scrollbar inside the text box if the text is too large. This way the proportions of the page will be kept with no global scroll.

**Comment by Danman7** [comment]
Fixed in #545
