### ISSUE TITLE
Radio Buttons and Check boxes

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#478]
This task is to implement check boxes and radio buttons within the App- This can be exploratory at this stage - Lets discuss the process and implementation required.

**Comment by diegotorrespy** [comment]
@stacylorraineprendeville @danicricco 

The back end should receive the data in the same way, no matter component is used in the front end. So this is a issue that should be discuss with @Danman7.

Side comment: It his really necessary? Because we have the `select` component that covers all possible cases.

**Comment by Danman7** [comment]
Radio buttons is basically the same as dropdowns (user can select only 1 answer), but in the form of a radio button. Checkboxes is in fact a multi select field (user can choose multiple answers for 1 question). Answer data for the first will be the same, for the second an array of answers.

@diegotorrespy @stacylorraineprendeville  We need the survey to tell us if this question is type `checkbox` or type `radio` and we can implement this. I will estimate it now, but it's blocked by the server.

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy We have an instance where a donor has requested multiple response - thus checkboxes- Just found out about this...so yes we need it - How would the select component we have currently cover this?

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy @javierpf Unblock by answering for next sprint

**Comment by Danman7** [comment]
@diegotorrespy Why did you change the estimate? :) I don't see this happening in 1 points.

**Comment by Danman7** [comment]
@stacylorraineprendeville I found a design for radio buttons, but I can't for checkboxes.

**Comment by stacylorraineprendeville** [comment]
![Screen Shot 2019-05-15 at 13.07.43.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/411ddc36-8a67-4bbe-8a5e-c3a522be07f8)

@Danman7 designs are these

**Comment by Danman7** [comment]
We are no longer blocked. @JDelPuerto You can close the issue.

**Comment by Danman7** [comment]
Docs: https://github.com/FundacionParaguaya/MentorApp/wiki/multiple-choices-question
