### ISSUE TITLE
Add text into the Poverty Stoplight Section

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#479]
Primary Participant Page Text
Tell us about yourself!
¡Cuéntanos sobre tí!

Family Members Page Text
Now, tell us about all the people you live with!
¡Ahora, cuéntanos sobre todas las personas con las que vives!

This text is CENTRE ALIGNED.
The design is found in the invision project "next sprint"

![Screen Shot 2019-03-30 at 10.34.12.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/b903515e-ad42-4ad4-9316-a71c9b38e67e)

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you just review the spanish on this issue - Its spanglish stacy/google transalte at present.

**Comment by aprojas** [comment]
@stacylorraineprendeville 
It's great! Just some minor changes on the second one. 

Family Members Page Text
Now, tell us about all the people you live with!
**Ahora, cuéntanos sobre tu familia.**

**Comment by stacylorraineprendeville** [comment]
hmmm @aprojas seguro? - creo que Kathi decia que es la gente con quien vive - no solo "familia"....

**Comment by aprojas** [comment]
That's what Nancy told me.. However, I think we can make a decision since it is something quite minimum. 
I would leave it like this then:
Ahora, ¡cuéntanos sobre las personas con las que vives!

**Comment by vasildimitroffhristoff** [comment]
![screenshot_20190423-123925](https://user-images.githubusercontent.com/47756276/56571323-5aedb000-65c5-11e9-98e3-d393ebed7afa.png)
After added the heading title to the family members screen. Is this ok?

**Comment by stacylorraineprendeville** [comment]
@vasildimitroffhristoff One thing that is wierd and I noticed this yesterday is that in the input fields - Name for instance has a different height than the fields with a dropdown - This is really strange - Can your review it
