### ISSUE TITLE
Saving of draft - Minimum requirements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#480]
If a user has reached the primary participant page BUT not added any content. Then when the user clicks on the X icon
A DRAFT WILL NOT BE SAVED
The message will be:

Are you sure you want to exit?

This is because we cannot have drafts created without the minimum requirement of a first name.

**Comment by Danman7** [comment]
@stacylorraineprendeville This is a description of what is currently happening in the app. What is the task?

At the moment the draft is saved only if user navigates to the next page from participant - either location or family members depending on what was answered in family size.

**Comment by stacylorraineprendeville** [comment]
No - Currently in the app I CAN save a draft without adding anything - Which leaves me in the situation with a draft on the home page with NO Name - I think we should rectify this in the next sprint @Danman7 because its kind of wierd.

**Comment by Danman7** [comment]
@stacylorraineprendeville In the current version of the app I cannot find any possible way to save a family without adding anything whatsoever. If you claim this is not the case, I believe you, but you must provide steps to reproduce. This way I can resolve it.

**Comment by stacylorraineprendeville** [comment]
@Danman7 I just did it again - Really easy to reproduce for me....I just get to the primary particopant page and exit without adding in any details and it saves an empty draft

**Comment by stacylorraineprendeville** [comment]
![Screenshot_20190417-102222.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/6663a7f2-a626-4e89-8a9a-e7fd06049e59)![Screenshot_20190417-102246.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/27e61dc2-a6e1-4109-9fd3-fdaf3500770e)

**Comment by stacylorraineprendeville** [comment]
Can you see the empty drafts above and the undefined families in the LIST?

**Comment by stacylorraineprendeville** [comment]
@Danman7 ... I had not logged out in a while - Could it be that this is the issue?

**Comment by stacylorraineprendeville** [comment]
Just logged out and then back in.............this is still possible - TO have a draft with no family name whatsoever -

**Comment by stacylorraineprendeville** [comment]
@Danman7 yep looks like this is fixed

**Comment by Danman7** [comment]
I have applied a dynamic flag for this. You can't be on the participant page, have errors and save the draft at any time.

**Comment by stacylorraineprendeville** [comment]
it came back today on May 13![Screenshot_20190513-175133.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/8c0a5707-315b-4a1d-b9d2-2df1d8dfe2c7)
