### ISSUE TITLE
Infinite Loop on Indicators

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#481]
At present the indicators go from green to red and are scrollable. However as the user gets to the red indicator he must then scroll backwards.
Infinite Loop will ensure that after red the user goes to green and infinitely loops.
This will also ensure the design is respected and that when you first load the screen in the indicator page the green indicator appears in the centre.
Can we also explore as part of this task our options in having the main indicator full size and the two to the left and right smaller whilst not in view.

![Screen Shot 2019-03-30 at 11.09.02.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/0b843edd-f6c6-4edb-bc34-5137c412a6fe)(Currently it appears too close to the left hand side not respecting margins and paddings)

**Comment by stacylorraineprendeville** [comment]
Just want to check if this has any dependancy on: 
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/mentorapp/477

**Comment by Danman7** [comment]
@stacylorraineprendeville Is this for the mobile app?

**Comment by stacylorraineprendeville** [comment]
@Danman7 yes

**Comment by Danman7** [comment]
Ok, we can implement this then.

**Comment by Danman7** [comment]
Fixed in #545
