### ISSUE TITLE
Remove Semaforo Image in App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#482]
Remove this image
![Screen Shot 2019-06-13 at 12.51.55.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/c82ff623-a22e-4c74-a780-23bcfb87dd49)

From this page

![Screen Shot 2019-06-13 at 12.51.27.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/3c29aa0c-d0ad-4257-86c8-0d4869c87746)

Reason is that the Fundacion does not want to relate themself with this older branding of a traffic light

**Comment by Danman7** [comment]
@stacylorraineprendeville No info to groom.

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you during your next testing sessions let me know if this issue crops up anyway else :)

**Comment by aprojas** [comment]
I still see the Stoplight @stacylorraineprendeville in the testing environment.

**Comment by stacylorraineprendeville** [comment]
@aprojas Guapi - Perdon! I meant to say if you see this anywhere else in the app or online write an issue - This issue is still in grooming ;)

**Comment by zommerberg** [comment]
Witch image should i put in its place after i remove it from the screen? @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@zommerberg lets try without or if this does not look nice then
![Screen Shot 2019-07-10 at 12 47 51](https://user-images.githubusercontent.com/45012899/60963400-f5ca7080-a310-11e9-8302-470ca972c973.png)
which you already have in the screen lifemaps

**Comment by zommerberg** [comment]
Here is a version with and without the image.What do you think? @stacylorraineprendeville 
<img width="276" alt="Screenshot 2019-07-10 at 16 30 09" src="https://user-images.githubusercontent.com/43446836/60973096-3a193900-a330-11e9-9147-cd646a62da7f.png">
<img width="271" alt="Screenshot 2019-07-10 at 16 31 37" src="https://user-images.githubusercontent.com/43446836/60973097-3a193900-a330-11e9-8d9c-77f127caf907.png">

**Comment by stacylorraineprendeville** [comment]
I think without...... @pavel
