### ISSUE TITLE
Online Map showing offline Map

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#485]
I created a test on the PY Demo Survey today.
I was online
However the map displayed the offline map for asuncion (I am in Bogota)

I created a test for the WARC survey -WITHOUT changing ANY device settings.
This correctly showed the online map of Bogota.

**Comment by Danman7** [comment]
@stacylorraineprendeville The map completely changed functionality since 1st of April. I can't find a way to reproduce this at the moment from my location. Can you reproduce this?

**Comment by stacylorraineprendeville** [comment]
Closed as not reproducible
