### ISSUE TITLE
Editorial changes on titles

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#492]
1. The title "Tablero" was not changed to Stoplight Mobile or Inicio.

![Screenshot_2019-04-01-13-56-09](https://user-images.githubusercontent.com/44477708/55404965-17080d80-5527-11e9-9901-5a8a7b4e1b95.png)

2.  The titles are not translated, even though I chose Spanish. 
(I saw this when taking the Ecuador survey)

![Screenshot_2019-04-01-13-57-09](https://user-images.githubusercontent.com/44477708/55405037-399a2680-5527-11e9-8369-76b7782c5997.png)

![Screenshot_2019-04-01-14-13-19](https://user-images.githubusercontent.com/44477708/55405048-3c951700-5527-11e9-896b-99c7b3545b0f.png)

**Comment by Danman7** [comment]
@aprojas For 1 What should the title be for Spanish?

For last screen (Family Details): This title comes from the survey. It's not possible to change at this stage. Unless we add multi language support to the surveys.

I will fix the rest.

**Comment by aprojas** [comment]
For Primary Participant would be: Miembro principal @Danman7

**Comment by stacylorraineprendeville** [comment]
@aprojas @Danman7 Can you create an issue for that title and multi language support for surveys

**Comment by Danman7** [comment]
@aprojas I was asking about 1 which is `The title "Tablero" was not changed to Stoplight Mobile or Inicio.`. What is the proper title there for spanish? Inicio?

**Comment by vasildimitroffhristoff** [comment]
There's an already closed issue which deals with the first point which states that the title for both versions should be "Stoplight mobile"
[https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/mentorapp/437](url)

**Comment by Danman7** [comment]
Fixed by #539

**Comment by aprojas** [comment]
I know this is closed, but when taking the surveys, I saw that the title "Primary Participant" was translated to "Participante de la familia"
But I commented on this issue saying this:

For Primary Participant would be: Miembro principal 

@Danman7 

Who decided that it should be "Participante de la familia"? 
This is just to know so we can sort it out.

**Comment by aprojas** [comment]
Also, if the "Family details" title was not solved in this issue, shouldn't we create a new one? Or else, it would just get lost. 

@Danman7 @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@aprojas please create the necessary issues that are not completed. Any issue left from this one and one for the text exactly as you require/request

**Comment by stacylorraineprendeville** [comment]
@Danman7 Can yuo create the relevant issue for what is required from the back end
