### ISSUE TITLE
Progress bar is slow

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#493]
This is NOT urgent. It is only a speed bug. 

When I moved forwards and backwards when taking a survey, the progress bar would still move but it would be slower, OR when I went to a previous screen, the screen would show first but the progress bar would take longer to "update" and move backwards too. 

Maybe it's my device. 

Samsung SM-T560
Android version 4.4.4

**Comment by aprojas** [comment]
This is not urgent @Danman7 
The release can go out but this can be reviewed?

**Comment by Danman7** [comment]
This will be fixed in #568
