### ISSUE TITLE
Amends for Geco - Chile Survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#494]
These are the comments from our partner Geco from Chile.
(I ALREADY UPDATED THE SPREADSHEET TOO)

Section: Primary Participant
1. Type of document:
ONLY INCLUDE IN THE DROPDOWN LIST:
- Cédula de identidad
- Pasaporte
- Documento o título de viaje
- Licencia de conducir

Section: Caracterización de la persona que responde:
2. Add question:
- Nacionalidad:
With a dropdown list (I'm waiting for JF to give me the list)

Section: Caracterización del Hogar
3. Typo: "En mi hogar, ¿tenemos camineta..."
- Change "camineta" for "camioneta".

4. Add question at the end:
- ¿Cuántos dormitorios hay en su hogar?
With a number field to fill in. 

Section: Educación
5. In the dropdown question of: ¿Asiste actualmente a alguna institución educativa?
Include a 3rd option: "No sé"

6. In the dropdown options of the questions "Cual es el nivel máximo alcanzado" and "cual es el grado máximo alcanzado":
- Change: "Kinder" to "Kinder o menor"
- Add: "No aplica"

Section: INDICATORS
7. Indicator 3: Ocupación/Trabajo mayor de 18
- Change the text in level yellow to the level red, and viceversa. (I already changed it in the spreadsheet). 

8. Indicator 43: Incidencia pública
- Change text in level green to this: 
"• No tenemos problemas.
 • Tenemos problemas que requieren del Estado, presentamos una solución como agrupación vecinal o de forma individual y perseveramos en ello hasta revolver el problema."

**Comment by stacylorraineprendeville** [comment]
@aprojas lets wait for this list of nationality before starting this task - otherwise it becomes two tasks...

**Comment by aprojas** [comment]
This is the list for the FIRST countries that should appear, then the rest of the nationalities list continue:
- Chilena 
- Boliviana 
- Colombiana
- Haitiana
- Peruana
- Venezolana

Here's the list of nationalities IN SPANISH for coding.

https://gist.github.com/edgardo001/767169452b99e021250769ae12a1aaf1

**Comment by aprojas** [comment]
Is this already groomed? @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #584](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/584) via [**ZenHub**](https://www.zenhub.com/)
