### ISSUE TITLE
Sync Labels not coherent between dashboard and sync screens

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#497]
The sync labels are:
- Draft
- Completed
- Sync Pending
- Sync Error

Within the sync screens this naming is not respected nor is the colouring.
On the dashboard we also have inconsistencies with the naming above - though the colouring is correct

![Screenshot_20190402-134621.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/6ab8fc36-0c42-44c6-b555-41caf69e0b77)

![Screenshot_20190402-134658.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/d4dbc6eb-95a1-4991-a795-4c5c7df9cf8a)

**Comment by Danman7** [comment]
Fixed in #546
