### ISSUE TITLE
Focus Field Colour

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#498]
Please ensure the focus field element (teardrop) is the green colour of the App - Currently we see a green that is not part of the brand identity.

![Screenshot_20190402-131602.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/2f1ef71b-2468-4e46-b8a7-c20cf32f7fbe)

**Comment by Danman7** [comment]
@stacylorraineprendeville At the moment both the label at the top or the border at the bottom are `#309E43`. What color should they be?

**Comment by stacylorraineprendeville** [comment]
@Danman7 referring to the tear drop element that appears on focus

**Comment by Danman7** [comment]
Aha! This is a part of the Android OS UI, not the app. Same as the title bar with the battery, this will require some research on our side to find out how to manipulate it. I will reestimate.
