### ISSUE TITLE
Vibrate effect on choosing indicator

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#500]
Currently when choosing an indicator the tick appears - however we could also use a sound or vibrate.
This task is to first brainstorm IF we want this and secondly what effects are available to us as "low hanging fruits"

**Comment by Danman7** [comment]
Easiest to implement will be a vibration pattern. It looks like sound is a bit more complex, but not much. Puting question so we discuss it.

**Comment by Danman7** [comment]
@stacylorraineprendeville Can we settle on a short vibration?

**Comment by stacylorraineprendeville** [comment]
@Danman7 We can  - Very happy with that!
