### ISSUE TITLE
Warning on Logout review

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#501]
The warning on logout  -is this clear you will loose all pending syncs?
The issue is to discuss this and needs to be thought about with upcoming priorities creation (retrospectively etc)

![Screen Shot 2019-06-13 at 12.47.46.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ef8ad431-83b5-4f2b-a231-598842b1fafb)

**Comment by Danman7** [comment]
If the solution is to add a checkbox or text to the modal, I estimate this at 1. Putting a question so we discuss it.

**Comment by Danman7** [comment]
@stacylorraineprendeville Are we decided on what to do here?

**Comment by stacylorraineprendeville** [comment]
Yes - Add the text with the checkbox.
