### ISSUE TITLE
Incorrectly re-appearing priorities message

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#502]
When completing the WARC Survey
A message appeared to create 5 priorities
I created 5.
When I clicked continue - the message re-appeared asking me to create priorities (with NO number stated) and i needed to again say "got it" - then when I click on continue I was allowed to go to the next page. Please remove this additional message.

This additional message also appears when I resume a draft with 5 priorities created. It asks me again to create priorities.

![Screenshot_20190402-133429.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ce3e201b-6ee6-4a66-8253-01ca56e1e14f)

**Comment by Danman7** [comment]
At the moment the tip shows only on continue if minimum priorities don't match. We will remove the unnecessary tip.
