### ISSUE TITLE
Bug in accessing a "pending sync" direct from a family profile

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#504]
I created a lifemap.
It was pending sync - I was offline.
I went into the family.
I was then allowed to resume the draft of the pending sync (?)

I clicked on resume draft
I went back a few screens - made no change and closed again on the close screen - pending in the navigation showed 2 but there is only one! ....so I went in again and made changes - went up to 3 in the navigation but again one in the list.

I checked on the platform - this was noted 3 times in the activity feed- 
3 families created and then I went back to the app and it had synched back those three!

![Screenshot_20190402-134613.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/60ce28b6-981d-466e-a2b3-0da7ecf3b42c)

![Screen Shot 2019-04-02 at 19.56.54.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/af38d29d-002b-4459-98ec-b34bcb5a2b6a)

**Comment by stacylorraineprendeville** [comment]
One idea @Danman7 create a new screen saying "pending draft" in the families list?
Would this remove the issue?

**Comment by Danman7** [comment]
A new screen is a large task. This is a tricky situation and in order to preserve the print we will pending sync families in the list.

**Comment by stacylorraineprendeville** [comment]
Ok - I was just thinking like this: Obviously THIS is not a design just an idea - but if it does nto save much time then your solution - the only thing is I do not have your solution clear from the comment... @Danman7 
![Screen Shot 2019-04-04 at 20.03.05.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ccf62c94-610e-4044-a4a9-f06334df688b)
