### ISSUE TITLE
Incorrect field type when writing amounts in FUSAI survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#506]
When I was taking a FUSAI survey, I wanted to add the amounts in the following fields shown in the screenshot. However, they are set as text fields rather than number fields.

![Screenshot_2019-04-04-10-25-53.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/a8136720-aee9-473d-aee3-dde520a817ba)

They should be like these:

![Screenshot_2019-04-04-09-59-22.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/865ae533-af97-4881-b39d-26af5d5af718)

DEVICE DETAILS:
Samsung SM-T560
Android version 4.4.4

**Comment by stacylorraineprendeville** [comment]
@aprojas  Please re-assign to Diego on FP PSP Server - This is his - Can you add here whether this error is in the spreadsheet or tech - we need to find out where the holes are

**Comment by stacylorraineprendeville** [comment]
@aprojas Also this is endemic - All surveys feature errors like this - All surveys need to be reviewied by Replicas/Methodology

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #582](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/582) via [**ZenHub**](https://www.zenhub.com/)
