### ISSUE TITLE
Sentry Reports for App crashes

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#512]
Please review if we have app crashing reports within Sentry (or anywhere!) for the following sierra leone related issue.
See epic for details.

**Comment by Danman7** [comment]
I’ve reviewed the sentry logs and have found an error that fits the description very well. ~15 minutes before yesterday’s standup a Google Pixel 2 phone experiences a crash on visiting the terms and conditions screen. As you said, they click on their survey and it crashes as the terms and conditions screen is the first one they should see. The error is related to a survey structure change done last december, more specifically terms and privacy not being a whole text, but separated into title and contents. I see they experienced this error on the 2nd and 9th of April. https://github.com/FundacionParaguaya/MentorApp/issues/252 should definitely fix any further

**Comment by stacylorraineprendeville** [comment]
@Danman7 How many other errors are recorded in sentry with these kind of characteristics? Just trying to get a handle on how many clients are experiencing crashes....

**Comment by Danman7** [comment]
@stacylorraineprendeville In order to do that we need to go trough 450+ issues. I'm tracking this in #520
