### ISSUE TITLE
Improve Sentry Reporting

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#513]
### Problem

There are many errors reported in sentry. We can get realtime notifications about new errors happening to understand, which client might have problems. But most errors are happening during development.

It's not clear which user had the error.

### Solution

(1) Disable sentry reporting in development
(2) Include the username
(3) Make sure once more that data from a failed survey sync can be completely recovered in Sentry

**Comment by Danman7** [comment]
(2) Is already implemented and should be available on all environment.
