### ISSUE TITLE
App crashes after pressing continue on read-only screen

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#514]
### Problem

Select a family from the familieslist (e.g. name: Ana Mexico Rojas). Select "Datos de la familia". Here you have a green button to continue. Clicking this button will crash the app.

Android Version: 9, User: demo

### Solutionn

Not sure, how the UI should be here but the app should not crash.

**Comment by stacylorraineprendeville** [comment]
@pA1nD I have added to this issue.

**Comment by Danman7** [comment]
This should not have a continue button. I'm checking.

**Comment by Danman7** [comment]
It does. I'll give this to Pavel as a starting issue
