### ISSUE TITLE
Minor changes to Skipped Indicator Page in concept & design

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#515]
Instead of the title being "skipped indicator" 
the title of the page is the indicator title and the text within the page is slightly altered

All screens (skipped, priorities, acheivements) are states of indicators - thus are the indicator page in this instance is a "skipped" indicator page -

![Screen Shot 2019-04-09 at 15.46.58.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ed3900eb-9f9b-4def-8de4-0ba4520f90ba)

**Comment by Danman7** [comment]
@stacylorraineprendeville Are we talking about making the list of skipped indicators into a series of screens?

**Comment by stacylorraineprendeville** [comment]
@Danman7 No - This is simple the TITLE of the page - At present we call it a skipped indicator in the title - conceptually this is incorrect - (my error) it is an indicator page - So the title is that of the indicator - the content of the page is "this indicator is skipped"

**Comment by Danman7** [comment]
We actually have such a page in the web app, but not in the mobile app. This appears when reviewing the indicators or if you press on an indicator in the skipped screen?

**Comment by stacylorraineprendeville** [comment]
This appears when you are reviewing the lifemap at the end of the process - You can add priorities by clicking on red or yellos - You can add achievements by clicking on greens and you have a skipped indicator in grey which when you click on can still give you the option to answer it - again - I guess it becoms more useful later - For a completed draft when I decide to go back and answer a question - thoughts @Danman7

**Comment by Danman7** [comment]
OK, we can estimate it.
