### ISSUE TITLE
Wrong display screen in smartphone

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#526]
This is how it is displayed on a Samsung smartphone (S7 edge)

1. In the indicator images section, big blank space on the dimension/indicator title (not visible in the screenshot) and the images and text don't fit the whole screen.

![Screenshot_20190417-081313.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/23b04e3f-6569-4ee1-81fb-bffcb7220ebc)

2. Logout/families titles are on top of the other in the menu dashboard

![Screenshot_20190417-081436.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ed9135c7-5593-40c1-8404-5f4598a1fe4e)

**Comment by vasildimitroffhristoff** [comment]
The first issue was already fixed in issue
