### ISSUE TITLE
App Icon not showing anymore

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#534]
### Problem

After the last update, the app icon does not show anymore (see screenshot) but it shows something that looks like a default icon.
![WhatsApp Image 2019-04-17 at 21.38.59.jpeg](https://images.zenhubusercontent.com/59a891da8f62dc7798c4d58a/9ab37370-e364-4372-86bb-d321b17ad1e8)

I'm Using Huawei P10, Android 8.

For Stacy it still seems to show the right icon.

### Solution

Show the PS icon again.

**Comment by Danman7** [comment]
I tried reproducing this for a bit and couldn't, but we will try to research: https://android.jlelse.eu/android-and-the-mystery-of-the-disappearing-launcher-icon-154f9267f98e

**Comment by stacylorraineprendeville** [comment]
@Danman7 Right now I no longer have the icon

**Comment by Danman7** [comment]
We are still trying to find a way to properly reproduce this so we can be sure it doesn't appear.
