### ISSUE TITLE
Zoom out is very limited in MAP

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#543]
When I'm on the map (online) I try to zoom out but it does not allow me to go further. It currently limits me to just a little more than the map already appears when I first open it.

**Comment by Danman7** [comment]
This is related to #524. We need to finish that one to properly estimate this one.

**Comment by Danman7** [comment]
@aprojas It sounds like you are talking about zoom in, not out. You can zoom out the map to see an entire city. Can you specify if you're trying to see a lot of the map or a detailed portion of a bit of the map?

**Comment by Danman7** [comment]
Fixed in #734
