### ISSUE TITLE
Incorrect 2nd member name

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#544]
When choosing more than 1 member in the family, in the next screen, it appears as "Miembro de la familia 1", when it should be "Miembro de la familia 2" or "Family member 2", since the number 1 is the one who is completing the lifemap.
This happened with Nelixia and Geco surveys. 

![Screenshot_2019-04-22-09-16-35.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b6609907-41c2-4c9d-a66a-b3e6462b5567)

**Comment by vasildimitroffhristoff** [comment]
This issue is referenced and fixed and solved inside issue #479
