### ISSUE TITLE
Indicators titles and images do not appear

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#549]
In this new version 1.7.1.
I logged out and logged in, disconnected the wifi and then,
I took a Geco survey offline and the titles and images of the indicators did not appear!

![Screenshot_2019-04-23-10-12-20.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/fbc2bead-fd6c-4eb6-b6dd-70e559a364be)

**Comment by aprojas** [comment]
I could not see the images and titles either when taking the Banco Solidario - Ecuador survey, this time I took it ONLINE.

![Screenshot_2019-04-23-11-24-46.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/8e8f5344-cf07-493f-add1-45e77618a8df)

@Danman7

**Comment by aprojas** [comment]
This also happens in the WARC survey when taking it ONLINE:

![Screenshot_2019-04-23-12-49-57.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/cca0e9b3-fb99-4a35-9d2f-8213f0859208)

@danman7

**Comment by stacylorraineprendeville** [comment]
@Danman7 Can this be reviewed BEFORE deployment.

**Comment by Danman7** [comment]
@aprojas @stacylorraineprendeville Me and Vasko cannot reproduce the missing images in any way on the devices we have available. We've logged in and out several times, tried with 4-5 different surveys, both online and off. I see images every time. I could surmise that the caching of images was skipped/didn't happen for Ana for whatever reason, but we need to reproduce it to debug it. I'm adding a cannot reproduce label and leaving this issue open.

The issue with the indicator titles I see for each survey and is tracked in #556

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you reproduce? If not close

**Comment by aprojas** [comment]
Does not happen anymore.
