### ISSUE TITLE
Responsive UI for Whole App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#55]
- [ ] Text scales as do all other elements
- [ ] All design elements are responsive until tablet portrait width
- [ ] Scaling elements "end" at tablet portrait width

**Where**
Using the mobile application - On ALL pages of the app - 
In this instance an Android Samsung with screen size 480 pixels by 800 pixels

**Who** 
All user types

**What:** 
Whilst on the dashboard (however this is visible throughout the app) I am viewing all text on the page at the same size as the smallest mobile device. Other elements such as button widths are incrementing responsively.

**Expectation**
The text should scale as do all other elements. 
We aim to ensure usability/visibility standards for all devices with this issue.

**Specification**
All design elements are responsive until tablet portrait width.
Scaling “ends” at tablet portrait width.
In tablet landscape view we use the exact same width and font sizes as the portrait view with space added left and right - This differentiation is to avoid the text and imagery becoming disproportionately large/incurring unnecessary vertical scroll/incrementing unnecessarily programming time. 

**Note**
In a later stage we would like to request targeted landscape tablet designs for certain pages. One current example of this is the tablet landscape view for indicators which already features a different design.

**Comment by Danman7** [comment]
@stacylorraineprendeville Shall we add new tasks here?
