### ISSUE TITLE
Logging in takes too much time

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#551]
When logging in after updating the new version 1.7.1. it took me more than 10 minutes to enter! It got really slow in the "downloading offline maps".

**Comment by stacylorraineprendeville** [comment]
@Danman7 not a deal breaker for release but lets review this before we add further offline maps.......

**Comment by Danman7** [comment]
We can improve the size of the download maps with little quality loss, but I need to check it out. I can estimate this though.
