### ISSUE TITLE
Login Button disappears on click

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#552]
When I click on the login button on the login screen the button disapears - This is not the correct behaviour - please ensure the button remains visible and functions as per the other buttons throughout the app.

**Comment by Danman7** [comment]
@stacylorraineprendeville We can disable the button while it's loading, but we don't have other buttons in the app with such state and I can't find any disabled/loading design in invision. Can we discuss this?

**Comment by stacylorraineprendeville** [comment]
@Danman7 This is the only button on the app which when you click on it disappears and leaves a blan space - Can it not just remain on the screen? We can discuss if you need too...

**Comment by Danman7** [comment]
Sure, we will improvise with the disabled state and loading indicator.
