### ISSUE TITLE
Incorrect list in dropdown Nationality list

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#553]
IN THE GECO SURVEY>

This appears first in the Nationality order:

![Screenshot_2019-04-23-10-09-12.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/bd53ac79-7807-4b25-8c89-9859c01e6251)

It should start with these and then continue normally:

![Screenshot_2019-04-23-10-09-36.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/494a2e7d-f913-4b92-96d8-7c8ba9586ba6)

This is connected to the issuee #601 in Server Repo

**Comment by stacylorraineprendeville** [comment]
@Danman7 @aprojas 
The first in the list should be Chile
It should then follow an alphabetical order
Remember to have 4 or 5 elements at the top of the list is a new feature and has a seperate ticket.

**Comment by Danman7** [comment]
@stacylorraineprendeville @aprojas This is functionality that has not been discussed thus far. For nationality we've setup so the first nation is the survey default country, which I have clearly in the survey configuration. For specific socio economic questions we show the data as we receive it in the API call to the server. For specific questions for specific surveys we have no way of knowing what the proper order should be unless it is stated in that order or we discuss another structure.

**Comment by aprojas** [comment]
I do not understand this. Could you explain this more thoroughly? 
The requested list does appear in the dropdown, the only thing is that it appears after other random nationalities. After the option Chilena, Boliviana, Colombiana, Haitiana, Peruana, Venezolana, the rest of the list in alphabetical order continues. 

But in your comment, I'm understanding that it is not possible and was not groomed. However, it does show in the list??

@danman7 @stacylorraineprendeville

**Comment by Danman7** [comment]
Can we meet on this, as it seems that we don't make sense to each other? We can discuss it while viewing the app in a shared screen.

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you please confirm  - Is this still happening?
Where?

**Comment by aprojas** [comment]
I cannot see this anymore in testing or demo environment! I can close this. @stacylorraineprendeville
