### ISSUE TITLE
Width of Non Sticky buttons throughout the App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#554]
A default for the non sticky buttons throughout the app seems to be near to a 100% width.
This was not the desired outcome for the design. It is confusing to the user.
Only the sticky buttons (Such as continue - Should be full width).

The following is a guideline to the desired outcome for the buttons throughout the app.
The most prominent example we have of this right now in the app is the dashboard.

The extra pdf provides further information
![Screen Shot 2019-04-23 at 10.13.53.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/2b8111b1-340b-48dc-9c51-ebdc453cc71c)[https://app.zenhub.com/files/150255038/4a520299-b6aa-472c-b163-97779edf0b7a/download](https://app.zenhub.com/files/150255038/4a520299-b6aa-472c-b163-97779edf0b7a/download)

This is incorrect.....(does not look like a button)

![Screenshot_20190423-111516.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/49dd0c55-2202-4606-8e36-e51609aa4410)

**Comment by Danman7** [comment]
@stacylorraineprendeville Will you agree that this includes the following buttons:
- Create a lifemap on Dashboard
- Retry on Sync
- Agree/Disagree on terms

Are we missing something to make our estimate?
