### ISSUE TITLE
Continue button did not work in Irradia

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#555]
I started taking an Irradia survey OFFLINE and
The continue button did not work when trying to move past the members section, before the map.

I tried going back and forth and still didn't work. It ONLY worked when I LEFT the survey and then resumed it again.

**Comment by Danman7** [comment]
I've tried to reproduce this with various settings with both 1 family member and multiple ones for the Irradia and other surveys. I'm always able to continue to the location screen.

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you reproduce this?

**Comment by aprojas** [comment]
I tried this again and didn't happen anymore. You can close this!! 

@stacylorraineprendeville
