### ISSUE TITLE
Height on the Dashboard and other screens

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#557]
![Screenshot_20190418-150639.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/2fb6e405-28e1-42be-84d5-0659975901ea)(https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/40bc3538-6967-4189-a0b7-5dbc3b089594)When the content is "short" i.e. that it does not reach the height of the screen - Then the content should be centred vertically within the screen.
the most prominent area that we see this is on the dashboard.
Please ensure a 100% height within the dashboard content on login.

Correct Placement
![Screen Shot 2019-04-23 at 10.13.53.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/26460cfc-02df-459d-98eb-b2b18f9978c6)

**Comment by stacylorraineprendeville** [comment]
Lets wait on this until we have the new dashboard designs

**Comment by Danman7** [comment]
We can check the height of the drafts and if it's short, we can center the rest to the remaining space.

**Comment by stacylorraineprendeville** [comment]
great!
