### ISSUE TITLE
Incorrect title in Irradia survey. Translate to Spanish

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#558]
In the Irradia survey:

The title is in English "Income and Employment". It should be in Spanish: Ingreso y empleo

![Screenshot_2019-04-23-11-15-23.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/807885d7-cfba-4069-8a5c-9bef57ee0e82)

**Comment by Danman7** [comment]
The title comes from the survey `topic/dimension` field. We can't translate that as it comes from the server. Absolutely no offense meant, but we have discussed this exact same issue at least twice before. We need multi language surveys (maybe).

**Comment by aprojas** [comment]
This is actually solved already! @Danman7 
And it is not from the server, since this is socioeconomic section, this has been changed by Diego once.

**Comment by aprojas** [comment]
I'm going to close it!
