### ISSUE TITLE
Wrong display of special characters

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#559]
When taking a FUSAI survey, there were wrong characters when reading titles with special characters. 

![Screenshot_2019-04-23-15-44-01.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/3b8310d3-afc1-453d-92fa-a1008767d0f7)

**Comment by stacylorraineprendeville** [comment]
@Danman7 this is also happening in family profile screens

**Comment by stacylorraineprendeville** [comment]
@aprojas This screen grab does not show the incorrect characters???

**Comment by aprojas** [comment]
Sorry for not making this clear, but it is shown in the first two options of the dropdown list:

It should be:
Propia con título
Propia sin título.

I just stated in the issue that this also happens with some titles, however, since this ticket is kind of old, I don't know if it changed. 
@Danman7 @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
Survey is fusai - Título

**Comment by aprojas** [comment]
This is in review but I can still see the incorrect characters. @stacylorraineprendeville @Danman7
