### ISSUE TITLE
App crashes when logging in

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#560]
When I logged in and the app was loading, it got to 100% and then it crashed. 
However, then I clicked on the app and the dashboard appeared just like nothing happened.
This especially happens when the images are downloading. 

This also happens when I want to take a Roots of Renewal survey.

![Screenshot_2019-04-23-16-12-58.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/7803489c-ca4c-4d7f-81f1-97419218c50a)

**Comment by Danman7** [comment]
@zommerberg Use the office old KitKat tablet to build the app on a slow device. Log out and then log in with demo and check if the app crashes or freezes during sync. Check `Loading.js`.

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you review as we cannot reproduce this.

**Comment by aprojas** [comment]
This happened to my app again today when I was logging out of it. @stacylorraineprendeville 
Now I'm not sure if it's only my tablet..

**Comment by Danman7** [comment]
We thought its related to caching images, but you @aprojas told me you had more than a gigabyte of free space. So I'm continuing to try and reproduce this.
