### ISSUE TITLE
Edition errors in App Release

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#561]
![Screenshot_20190423-192149.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ce063f77-298e-48b6-ac6b-16ecae2a4b09)

In English - Please note the word "below" should only feature one l

In the spanish version we have no translations......
lets add-
We found you! - ¡Te encontramos!
You can tell us more about this location in the form below - Puede decirnos más acerca de esta ubicación en el siguiente formulario
We cannot find you! - ¡No podemos localizarte!

**Comment by stacylorraineprendeville** [comment]
@aprojas please can you review the translations

**Comment by aprojas** [comment]
I would suggest "Dinos más acerca de esta ubicación en el siguiente formulario" or "Puedes decirnos más acerca de esta ubicación en el siguiente formulario", because we speak as "tu" not "usted". 

The rest is super! 
@stacylorraineprendeville
