### ISSUE TITLE
Retrospective of Family Location often showing current location

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#562]
Logging in as demo demo
Going to list family such as: 
Family demo demo + 1 + 
Family veseto hristov + 1

The location page is incorrectly displaying the current location of the device on load 
 I.e. - I see Colombia!!!! Incorrect - These surveys were not taken by me!

Please also review the title - Not aligned centre!

**Comment by Danman7** [comment]
I've fixed the centering.

Showing the current location of the device is a bug. However both these surveys don't have a location saved. This might be because user chose not to give the app permissions to his location or just the location didn't return anything. I'll show the form when this happens.
