### ISSUE TITLE
BANCO Solidario - Translate "Family details" to Spanish

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#565]
In the Banco Solidario Ecuador survey, there is a screen title named "Family details", we need it translated to:

"Datos de la familia"

This is very urgent because the client will not start taking surveys if this is not fixed, and this is also an old request. 
This was also translated for USEM Mexico, and Paraguay. 

This is also happening with:
- IRRADIA
- FUSAI
- Paraguay DEMO version

**Comment by stacylorraineprendeville** [comment]
Reasons for complications are noted in this issue:
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/mentorapp/492

For last screen (Family Details): This title comes from the survey. It's not possible to change at this stage. Unless we add multi language support to the surveys.

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy @Danman7 I have told the internal team we will fix this next sprint - Whomever falls the task - lets get it done. Re groom if necessary

**Comment by diegotorrespy** [comment]
@aprojas @stacylorraineprendeville 

This issue was solved by a database update of the ```topic``` column in all the surveys involved. 

**Environments affected:** ```demo```, ```platform```

**Comment by aprojas** [comment]
This is reviewed and done!! @stacylorraineprendeville
