### ISSUE TITLE
Clear input values of hiden components 

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/MentorApp#569]
At this moment when a question that trigger the condition to show another question depends on it and then this field is filled, the value is not clear again if the triggering question changes and the other question is hide.

Step 1: Question "Tengo un salario mensual?" is answered with "Si", so the next question "Cuanto? (Liquido)" appears and the user fill this field.
![1.jpeg](https://images.zenhubusercontent.com/5c1a3b279be21e037cb696fc/36abc48b-8866-4155-878a-a0ec5832697c)

Step 2: Question "Tengo un salario mensual?" is changed to "No", so the question "Cuanto? (Liquido)" disappears.
![2.jpeg](https://images.zenhubusercontent.com/5c1a3b279be21e037cb696fc/384f99b9-0046-415a-bb29-965f5c6daccf)

Step 3: Question "Tengo un salario mensual?" is changed again to "Si", so the question "Cuanto? (Liquido)" appears again filled with the previous value. That means if the survey is submitted the value will be stored in the database even if the triggering question changes again to "No".
![3.jpeg](https://images.zenhubusercontent.com/5c1a3b279be21e037cb696fc/e987a43a-3526-47d3-ac89-d5465b012815)

**Expecting behaviour**
Clear the value of the components when these are hiding by their triggering question.

**Comment by Danman7** [comment]
@diegotorrespy We are talking about DEMO survey? Please, when you have issues related to specific survey logic also add the survey name.
