### ISSUE TITLE
Title does not appear in indicator 8 of Nelixia

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#570]
In the NELIXIA SURVEY: 

The dimension title "Salud y Medioambiente" , does not appear in the indicator 8 of Water.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #632](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/632) via [**ZenHub**](https://www.zenhub.com/)
