### ISSUE TITLE
Image caching performance

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#576]
We should check how caching 1000+ images is handled by old devices. There should be a way of continuing image caching from where it left if the app closes prematurely.

**Comment by stacylorraineprendeville** [comment]
@Danman7 Do we need this? Could we not just create more demo account users----no client has more than 1 survey so far it seems ---so this issue is just within the demo account?

**Comment by Danman7** [comment]
I agree, we already cache as quickly as posible after a short research.
