### ISSUE TITLE
Continue button missing on resuming draft

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#584]
Feedback from Stacy: 
`When I resume a draft I now can no longer resume - it leads me to the page BUT the continue button has disappeared- We just recently had the issues to remove the continue button in the read only pages - seems like it has been removed everywhere - we need it when working on a draft`

**Comment by Danman7** [comment]
@stacylorraineprendeville I'm not able to reproduce this. I've tried 2 different surveys and quitted the snapshot at every possible screen. Every time I go back to resume I can continue no problem.

**Comment by stacylorraineprendeville** [comment]
@Danman7 This is an issue still  - please go via the family list profile and resume the lifemap - this is where you will locate the issue - You need a lifemap page accessed from within the family profile - NOT the dashboard.
This seems to be a largely non tested area - @aprojas  can you mae sure this comes up in the test cases.
