### ISSUE TITLE
Whole text of indicator doesn't appear

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#600]
The text in indicators that are longer is not appearing completely, It doesn't even scroll down to show the rest of the text. 

![Screenshot_2019-05-07-09-25-20.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b7bed9ae-b562-45b4-8e27-29df2a9aca17)

**Comment by Danman7** [comment]
@stacylorraineprendeville Can you please double check this? What are the required amendments, as from our end the feature has been developed per specs.
