### ISSUE TITLE
Add decorative balls in socioeconomic part

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#601]
Please add the decorative balls image in the socioeconomic pages. 

![Screenshot_2019-05-07-09-51-13.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/253ae9d4-3aba-469b-8525-20490eb841b4)

**Comment by zommerberg** [comment]
Do we have the design for that?

**Comment by stacylorraineprendeville** [comment]
@zommerberg You already have the image in the primary participant pages.

**Comment by zommerberg** [comment]
So we want this kind of balls ?
<img width="273" alt="Screenshot 2019-06-12 at 12 30 27" src="https://user-images.githubusercontent.com/43446836/59340055-f0780700-8d0d-11e9-8e19-dc7b1f534a17.png">

And not this kind of balls?
![Screenshot_1560329576](https://user-images.githubusercontent.com/43446836/59340072-fa016f00-8d0d-11e9-9cac-74d58894d453.png)

IF you want the balls from the first screenshot, could you give me the text for the balls in spanish and english
@stacylorraineprendeville 
@aprojas

**Comment by stacylorraineprendeville** [comment]
@zommerberg the balls from the second are fine :)
