### ISSUE TITLE
White space in the navigation elements

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#605]
White Space to the right of the navigation elements - pretty sure we have an open issue for this but please check. This should be removed. 

![Screenshot_2019-05-07-10-05-02.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/37c8e2dc-210a-4768-87e1-920a6e74e86c)

**Comment by Danman7** [comment]
This most probaly is a responsive issue. We can't seem to reproduce it on our phones and tablet. @aprojas Are you seeing this on your tablet? In portrait or landscape?
