### ISSUE TITLE
Little more height in the sticky continue buttons

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#606]
Please add a little more height in the sticky continue buttons. 

![Screenshot_2019-05-07-09-51-13.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/a2cefb9c-206b-44e6-8e81-d7d2ea05109d)

**Comment by Danman7** [comment]
@stacylorraineprendeville I would like you to approve any UX changes.

**Comment by stacylorraineprendeville** [comment]
Approved @Danman7 - We are looking at adding approximately 10 pixels more....just makes it easier to click for the user.
