### ISSUE TITLE
Center these titles on the screens

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#607]
Centre the titles on the life map on all screens - primary participant somehow now appears left aligned…..and later they are more. - Your life map page for instance.

![Screenshot_2019-05-07-10-12-34.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f3d89c90-9656-4d3d-b096-4df882e4ed7f)

**Comment by Danman7** [comment]
As per design: https://projects.invisionapp.com/d/main#/projects/prototypes/16366210 there are some left aligned and some centered titles.

@stacylorraineprendeville What is the expected global centering for all screen titles?

**Comment by stacylorraineprendeville** [comment]
Yes @Danman7 let´s centre align ALL - Not sure but I think this is an error in the designs
