### ISSUE TITLE
Email and Phone Number in the family profile page

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#610]
Please see: Email and Phone Number as per the design in the family profile page. 
Icons should appear when the EMail and phone number have been completed.
On click the email address can open up the phone email client and the phone number can make a call.

![Screen Shot 2019-05-07 at 20.01.46.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e9cb216d-673c-4d5b-9342-d241ebe2f276)

**Comment by Danman7** [comment]
@aprojas The expected behaviour is to click on the buttons and either open mail app or start a call?

**Comment by aprojas** [comment]
The previous comment is for @stacylorraineprendeville ! @Danman7

**Comment by stacylorraineprendeville** [comment]
@Danman7 Yes - This would be the behavior - I am just updating the issue now
