### ISSUE TITLE
Design review with Stacy

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#614]
Various issues with the text fields - Making a design review….Spacing between fields is not correct, Larger text (maybe) - two line issues on margin right .

Let's review text fields and spacing and marging all in a call, and make some amends to make it better!!

**Comment by Danman7** [comment]
@stacylorraineprendeville @vasildimitroffhristoff Is this clear? I don't see much specs here.

**Comment by stacylorraineprendeville** [comment]
@Danman7 The idea Dan is to review some of the design directly with Vasil - Rather than creating a long list of issues - I would like out some sizing of fonts - etc - I am pushing to the next sprint as I was not available last week
