### ISSUE TITLE
Text color in search field is not accessible grey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#617]
Text color in search fields has not been amended to the accessible grey - it is still too light. 
Please amend for accessibility

![Screenshot_2019-05-07-11-49-45.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/a198c16b-7923-42a4-be86-65fd8bc0ee1e)

**Comment by Danman7** [comment]
@stacylorraineprendeville Can you specify an accessible color?
