### ISSUE TITLE
Location and Resume Drafts

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#622]
As a user I take a lifemap in the field and add the offline location on the map - When I go back to the office I resume the draft to add some priorities - I run through each of the screens to review the work - What happens to the location screen? Does this appear in read only, Does it try to change the info?
Do we need an interface when the user is in a draft to ask if we need to update location?

This task is to review this use case and brainstorm the implementation.

**Comment by Danman7** [comment]
@stacylorraineprendeville Once the offline location or any location is added to the draft, it doesn't try to change it in any way. You can change it as you see fit, dragging around before draft is synced. Once synced you can review the location in the family location read only page as normal.

What is the task here?

**Comment by stacylorraineprendeville** [comment]
@Danman7 Ijust wanted to review this - I think I will need to make a usability test for this......

**Comment by Danman7** [comment]
Just a note. In read only we don't show the map offline as it can be anywhere outside cached maps.

**Comment by Danman7** [comment]
Closing due to no communication and updates.
