### ISSUE TITLE
Dashboard Visualisations for the App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#623]
An idea is to state the number of indicators overall in the dashboard - To provide some visualisation, increments to progress for the mentors and neatly tie in to the methodology.

![Screen Shot 2019-05-07 at 19.03.11.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ee43fbbb-7cb8-4d20-9037-883edd4461b8)

A second (less favorable idea is to state the number of families)
![Screen Shot 2019-05-07 at 19.03.33.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/a46b34c8-84f2-4b16-8440-544a9667390d)

This task is to discuss the two implementations, pros and cons and estimations for both.

**Comment by Danman7** [comment]
- For the indicator count: it takes all indicators from the drafts or all families the account has access to? For the drafts it's easier than getting all the data from the families. The second option is not difficult to implement, but difficult to do so without breaking app performance. We will have to think about it.
- For displaying the families count: it's extremely easy to implement for no time.

**Comment by stacylorraineprendeville** [comment]
@Danman7 Can you convert this issue into showing the families in the first step....can you split out a seperate spike issue for the dashboard indicators to get info from ALL families - I think it will be worth it but for sure we need to judge effect on performance - in the meantime adding the families gives us something to start with to make the dashbaord more attractive

**Comment by Danman7** [comment]
We will implement the families count in this issue. The indicators are covered in #678
