### ISSUE TITLE
Taking a photo in the App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#624]
As a user at the end of my lifemap or at an achievement being made users would love to be able to take a photo.
This issue is about understanding what is involved in making this happen.

**Comment by vasildimitroffhristoff** [comment]
Simple implementation lives inside branch taking_photo (Using react-native-camera-kit)
![Screenshot_20190521-135528](https://user-images.githubusercontent.com/47756276/58090688-7fdb4000-7bd0-11e9-939e-ab0e951b717e.png)

**Comment by vasildimitroffhristoff** [comment]
Possible solutions: 

- [ ] - react-native-camera-kit (Wix)
- [ ] - react-native-camera (react native community)
- [ ] - CameraRoll (React Native) 

An example implementation using Wix's solution can be found in branch **taking_photo**
Two buttons for options were added. **Take a picture** and **upload picture** from the file system.
When you click on take picture button currently an array of objects alerts. It contains the images that were taken using the app ({size, height, width, src}).

![Screenshot_20190521-135528](https://user-images.githubusercontent.com/47756276/58091866-62f43c00-7bd3-11e9-9663-5f5ccefad472.png)
![Screenshot_20190521-141508](https://user-images.githubusercontent.com/47756276/58091884-6a1b4a00-7bd3-11e9-8fa9-c13a5e13c262.png)
