### ISSUE TITLE
Priorities Improvements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#625]
This task is to improve the creation of priorities in the mobile app.
Currently when you complete the indicator screens you reach the completion of the lifemap (pre creation of priorities)
Step 1 is to create a new intermediary screen as below - This screen simply has the poverty stoplight balls full height and the message to create priorities.
When you click on got it the functionality is to take you to the next screen (lets review the UX on this could anchor down!)
![Screen Shot 2019-05-07 at 19.33.15.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/fcbffd49-7fe0-4d3a-8c2d-9656be8441fa)

The next screen you go to is that which you already have: (could be an anchor tab into the same page)
![Screen Shot 2019-05-07 at 19.40.39.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/137a25c8-694b-402c-b0e7-68af0b8aec73)

When you click on a priority INSTEAD of going to a new screen a pop up message appears
![Screen Shot 2019-05-07 at 19.48.49.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/f5bab27d-9de6-4c70-9fcf-63402e9d98b3)

This would also be in place for Achievements.
This means that you do not need to leave the screen to make the priorities.

When you click on the top of the screen the message disappears (or do we need a x button?)
![Screen Shot 2019-05-07 at 19.53.18.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/298cc5db-e83d-4dba-a82e-94539d96c2f2)

Important - In late phases a USER may want to edit indicator answers from this screen - this would involve a seperate screen.

**Comment by aprojas** [comment]
This is done. Closing it.
