### ISSUE TITLE
NullPointerException in ReadableNativeArray

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#635]
Related sentry report: https://sentry.io/share/issue/db61c883ef1c42aaa288f1c2f453118e/

We are unsure of what can cause this issue or how to reproduce it. There are some hints here: https://github.com/facebook/react-native/issues/19413 and here https://github.com/facebook/react-native/issues/19423

Since this is an unknown issue we need to:
1. Study report and try to reproduce it
2. If reproduced look for a possible solution in the links. If not, monitor if this appears again on the issue reports.

**Comment by Danman7** [comment]
Might have been solved by 6f4a4f13351da5d6b90e43db737949811b862e64. We continue to monitor.

**Comment by Danman7** [comment]
Issue is not resolved. `Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference` was experienced today by user Andy C. We also seem to experience it from time to time.

**Comment by Danman7** [comment]
We are able to reproduce it from time to time, but we don't exactly understand what is causing it and higher priority issues are taking the time.

**Comment by stacylorraineprendeville** [comment]
Andy C @Danman7 is the UK - the known issue we have had with the UK was related to the resume Draft - Does this help?

**Comment by Danman7** [comment]
@stacylorraineprendeville Not sure if related. We haven't had this for a few weeks. Will keep in icebox.

**Comment by vasildimitroffhristoff** [comment]
We assume it's been fixed in a react-native library update
