### ISSUE TITLE
NoSuchKeyException lineNumber in ReadableNativeMap

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#636]
Related sentry reports: https://sentry.io/share/issue/459650e706554d789da61449ce0fad93/ and https://sentry.io/share/issue/bfcab3541e4743988310c3e0219a2363/

Like #635 this is another issue experienced by the `solidario92` account that we are unsure what is the cause or how to reproduce it. Possible explanation here: https://github.com/facebook/react-native/issues/24382

**Comment by zommerberg** [comment]
No idea how to reproduce that.

**Comment by Danman7** [comment]
We haven't had that in recent weeks after maps update.
