### ISSUE TITLE
Integrate Intercom

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/MentorApp#65]
Integrate Intercom into the React Native App.

There is great documentation available here:  https://medium.com/@eileenzhong/intercom-integration-with-react-native-80cfbbf98aff

**Comment by pA1nD** [comment]
@IvaKop is there any progress you achieved on this?
@pA1nD the link seems tobe outdated.

**Comment by IvaKop** [comment]
@pA1nD @stacylorraineprendeville I need a bit of clarification here, what is it that we need exactly inside the app? This product has several aspects and I need to know what we are trying to achieve here. Is it just that clients can write to us from the app? Where should that option be located, in the entire app or specific screen? Thanks in advance!

**Comment by stacylorraineprendeville** [comment]
@IvaKop Question here - What happens if the user is offline? As I understand this could give access to the FAQ?
This is important in validating the use of this feature as if we add a primary navigation element we will need to know what happens when the user is offline.

**Comment by pA1nD** [comment]
If we use Intercom for the FAQ (which we do at the moment), the FAQ would be not accessibel offline (as far as I know). We could build a tool that creates an offline copy of the FAQ and bundles it with the app. (some effort)

Otherwise there would just be a message that you are offline and you can't use the help section at the moment.

**Comment by IvaKop** [comment]
@pA1nD @stacylorraineprendeville are we using only the FAQ or the life chat functionality as well? Please clarify the requirements for this issue, thanks!

**Comment by pA1nD** [comment]
My idea was to use both. But esp. the Life Chat.

@stacylorraineprendeville what's your opinion?
