### ISSUE TITLE
Tickbox NOT appearing on indicator selection

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#650]
The checkbox (tickbox) is NOT appearing on indicator selection (again)
Can we review the logic of this - Should be:
1. Touch 
2. Tickbox appears
3. User moves to next screen

We have client complaint on this one  - So can we review as to why this keeps appearing/disapearing!

**Comment by Danman7** [comment]
@stacylorraineprendeville Thank you for the specific steps to reproduce. This makes our work a lot easier and less communication heavy.
