### ISSUE TITLE
GECO Multiple Offline Maps

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#652]
GECO Currently have 1 offline map for Santiago - They need 

Antofagasta y Mejillones el lunes 27 de mayo

Arica el lunes 2 de junio 

Iquique el jueves 6 de junio.

**Comment by Danman7** [comment]
@stacylorraineprendeville This will be directly covered by #619.

**Comment by stacylorraineprendeville** [comment]
This feature will not be ready until 3rd June.
For the client to access this feature we could allow them to use the internal testing track.

This would require we release into the internal testing track at the latest Thursday 23rd. - Wednesday 22nd would be better!

What does this mean to the client?

They currently have one mentor user under the name of : tcontreras@gecogroup.com
They wish to create two more users BEFORE 27th.
We will need these emails - and we with the one above we can add to the internal testing.

Also back end add the co-ordinates
