### ISSUE TITLE
Missing coordinates in some GECO surveys in demo

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#653]
@aprojas commented on [Tue Apr 23 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/617)

There are some coordinates which are missing for several families in the reports of GECO. 
We don't know why this happens. But the street address does appear.

![2019-04-23 (2).png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/761edeb4-40cc-4369-b273-c5a4cef7799c)

---

@stacylorraineprendeville commented on [Tue Apr 23 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/617#issuecomment-486005706)

@aprojas Is GECO using location ?

---

@diegotorrespy commented on [Wed Apr 24 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/617#issuecomment-486333954)

@aprojas @stacylorraineprendeville 
These empty columns are due that the coordinate data was not saved. 

@Danman7 
Is there a possibility that the application does not capture this data? Or that the user can omit this step?

---

@diegotorrespy commented on [Mon Apr 29 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/617#issuecomment-487716803)

@stacylorraineprendeville  @Danman7 

Since this is not a server side platform, I don´t have much to say. The problem is related to the app that is not sending the coordinates.

---

@stacylorraineprendeville commented on [Mon May 13 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/617#issuecomment-491861912)

@Danman7 Not sure if you have seen this as it is not in your repository - In what instance would the app not take any locations - Is this a bug ? Or just that location was not present?

**Comment by stacylorraineprendeville** [comment]
@Danman7 This was in the wrong repository and as such looks like it was missed - I added to this sprint as we are on the map and this is the client that we are working to achieve the date for....

**Comment by Danman7** [comment]
I tested this for a few hours today. The only way I see that it possible to get no location is if the device either has no location turned on or the location doesn't return anything within 10 seconds (as described in specs). In both cases the user would see an appropriate message "We can't find you". It's not possible to skip as the continue button is not visible while we are getting the location.

This doesn't exclude the possibility of some edge case, which I can't think of in the app. But as far as my sprint goes, I couldn't find it within a reasonable time.

@stacylorraineprendeville Would you like me to continue testing?

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy We need to know what the column "direction" is because it contains a addres BUT the fields that should containt user text input are empty......
please define where this content comes from....

**Comment by diegotorrespy** [comment]
@stacylorraineprendeville @Danman7 

There is a column `address` in the family table where is stored this information when it comes from the front end

**Comment by stacylorraineprendeville** [comment]
@aprojas We have no known bug for the missing co-ordinates

**Comment by aprojas** [comment]
I cannot think of anything else rather than that they have not turned their location ON, since the coordinates still appear with the location on but wifi off.. @stacylorraineprendeville Should we close this?
