### ISSUE TITLE
AddFamilyMember: firstName screen resets all family member first names if family member count updated

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/MentorApp#66]
To Reproduce:
Set 2 family members
Fill in Name of Second Family Member
Then Set 3 Family Members
Fill in name of third family member (note that confirmation disabled and state sets the name of the second family member to '')

OR

Set 3 Family Members and fill in names
Then set to 2 family members. Name still appears but cannot proceed

**Comment by Danman7** [comment]
I can no longer reproduce this. Probably fixed in 6bf83d204018b457bee654d51e5b887cd49a37ce or 0e372426bfd7641ce30524ba7be146ae66bdbb6c.
