### ISSUE TITLE
CHANGE HARD CODED MAP FOR GECO SURVEY

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#664]
Change Map from Santiago - Back end also required.

**Comment by Danman7** [comment]
@stacylorraineprendeville I need coordinates of the area that should be cached [top left: lat, long, bottom right: lat, long]

@diegotorrespy I would need the survey.surveyConfig.location - the center to be changed.

**Comment by JDelPuerto** [comment]
@stacylorraineprendeville  I need the center of the area[latitude, longitude]  to be cached

**Comment by Danman7** [comment]
@JDelPuerto Center is latitude: -23.6281968 longitude: -70.4747688

**Comment by JDelPuerto** [comment]
@Danman7 We updated the coordinates in demo

**Comment by Danman7** [comment]
@JDelPuerto The center is miscalculated on my side. Can you make the Geco survey center at
```json
{
  "latitude": -23.6513184,
  "longitude": -70.3981301
}
```
I have hardcoded the center for this release. Map is saved in this area:
<img width="360" alt="Screenshot 2019-05-17 at 12 15 34" src="https://user-images.githubusercontent.com/3336245/57917705-e9401380-789d-11e9-8157-1360ec965ac3.png">
