### ISSUE TITLE
Downloading whole countries offline

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#666]
Check if we can download whole countries offline for a particular client.

**Comment by Danman7** [comment]
I spent a couple of hours trying to find a good approach for this. There seems to be no way to download tiles related to a single country. There was an API that you can use to get country boundaries (http://a.tiles.mapbox.com/v3/examples.map-vyofok3q/geocode/spain.json) that is now not working. So in any case we would need to calculated boundaries ourselves.

Approach: **Get the whole country in one single map**
![whole](https://user-images.githubusercontent.com/3336245/57846060-162bf200-77dc-11e9-9ca0-28e310c30784.jpg)
Countries tend to not have box shapes so we end up downloading a lot of excess data. As we can clearly see the whole of Chile for example is way over the free 6000 tiles.

Approach: **Get the country as overlapping map sections** 

This mean we download the whole country in sections, so there is less excess. But now we need to spend a ridiculous amount of time calculating each section's boundaries. We will still go over the limit in the end. I don't see that is feasible.

Approach: **Paid account for unlimited download**

We can use the enterprise setup to download as much as we need, but we would still need to optimise the what the map shows otherwise we will end up with hours of syncing and gigabytes of maps.

I couldn't find how apps like Maps.me are doing offline maps, but they have their own source of vector maps, which we don't

**Comment by stacylorraineprendeville** [comment]
@Danman7 thanks for this work - I would like @pA1nD to comment as well...............................what do we think is best?
