### ISSUE TITLE
Equador sync error

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#673]
Related sentry report: https://sentry.io/share/issue/4757b54ea648405b91de1505d379794c/

User `solidario35` from Ecuador has experience 4 sync errors yesterday. Error is 

```
Exception while fetching data (/addSnapshot) : could not execute statement; SQL [n/a]; constraint [person_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
```

@zommerberg Can you do a couple of lifemaps with the Ecuador - Banco Solidario survey and check if we experience a sync error?

**Comment by diegotorrespy** [comment]
This was due an outdated sequence that was changed in the production database. I have updated the sequence to fix the issue.

**Comment by stacylorraineprendeville** [comment]
For this issue to be DONE - I would need to know the effect on the client - Will these surveys now sync automatically? @Danman7 @diegotorrespy

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy this was the first sync error - Can you explain the why´s here - This is different to the issue that we spoke about last friday....
@javierpf FYI
