### ISSUE TITLE
Switching house description field name from "address" to "houseDescription"

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#674]
We are saving house description in the draft as address. In order to switch the name we need to know from @diegotorrespy can we do it. What will happen to the old data?

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy response here please - what to do?

**Comment by diegotorrespy** [comment]
@Danman7 
I think you mean the key `streeDescription` right?
If this key changes in the front end, we will also need to change it in the back end. There would be no problem with the old data as only the field name will be changed.

**Comment by Danman7** [comment]
@diegotorrespy I'm not aware of any `streeDescription`. We are not sending anything like that back to the server. Is this an already existing key?

**Comment by diegotorrespy** [comment]
@Danman7 
I am seeing this in the mobile app:
![streetDescription](https://user-images.githubusercontent.com/645391/60669943-86024480-9e3d-11e9-8c57-5453babc6668.jpeg)

The question Street or house description will be received in the server as `streetDescription`. This change is not available yet but if you agree with the name of the key I will add this.

**Comment by Danman7** [comment]
@diegotorrespy Yes we can agree. I need you to:
1. Add `streetDescription` to submiting a draft to the server and it will correspond to the above field in the screen shot.
2. Still accept the `address` field from any not yet synced drafts that use the old structure and save it to `streetDescription` on the server.

Is this clear enough?

**Comment by diegotorrespy** [comment]
@Danman7 
Perfect! I'm going to make this change in that way to avoid incompatible request. Thanks.

**Comment by zommerberg** [comment]
i am getting sync erros when trying to sync with streetDescription or houseDescription @diegotorrespy

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy Do we have any news on this?
