### ISSUE TITLE
Choose existing family at survey start

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#686]
https://projects.invisionapp.com/d/main#/console/17595809/364766976/preview
https://projects.invisionapp.com/d/main#/console/17595809/364767093/preview
https://projects.invisionapp.com/d/main#/console/17595809/364767399/preview

This task includes a user choosing whether to start a new survey with an existing family. If yes we show the family list so he can pick the family. We need to display the family's participant, members and location data, so they can review and re-edit them if need be. This includes the whole `familyData` object. Any other data, like socio economics and indicators, they need to fill in again.

Watch the bottom got it popup. We can know if this draft is a retake based on the existence of a `familyId` property, which a draft will only have if a family has previously synced with the server.

**Comment by vasildimitroffhristoff** [comment]
What's the purpose of the "+" icon sitting inside the navigation in terms of functionality?

**Comment by stacylorraineprendeville** [comment]
@vasildimitroffhristoff please see the retaking epic - the plus symbol was a design error from a copy paste
