### ISSUE TITLE
UI for indicator improving (achieving) - on retaking lifemap

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#688]
![Screen Shot 2019-08-08 at 09.39.39.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/52889a65-8ed0-4b9a-bdfe-52b7ff0dbc15)

This task includes a popup that shows a user that his indicator has went up since last snapshot. So if a certain question goes from 1 to 3 (red to green), we show the above. OR if an indicators goes form red to yellow (this is also an achievement)

When retaking a survey, the indicators must be retaken from scratch, meaning `indicatorSurveyDataList` is empty. But at the same time we need to know what the last indicator was. This means we need to also have something like `oldIndicatorList` in the draft, that we don't submit to the server.

**Comment by stacylorraineprendeville** [comment]
Please note that here I make an amend. 
The idea would be that when we encounter an indicator that has moved up - we also ask the questions related to an achievement.

Like so:
![Screen Shot 2019-06-11 at 18.08.49.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ca29bbb2-159c-40fd-81c9-cdcb568eacfa)
