### ISSUE TITLE
Show static map image in Dashboard>Families 

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#697]
In the families screen - please show the static image of the map as per the families profile screen.

![Screen Shot 2019-05-27 at 20.19.56.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/c9f22fe2-543c-4f31-9e0c-d701e1bdb6e1)

Static Image found at:
https://www.dropbox.com/sh/zxu86n2t8h3zpwv/AADaWNC3JtABKA_DjhMTlP4Ha?dl=0

This is while a further pending task related to showing the live map is completed - Issue 462

**Comment by Danman7** [comment]
@zommerberg We use the `assets/images/map_placeholder_1000.png` image.

**Comment by Danman7** [comment]
Will be introduced by retaking a lifemap.
