### ISSUE TITLE
Cut images of the indicators for UK 

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#713]
The UK Hub reported that since the new release, their images are not cut and not complete in the app. 
They are using a Galaxy TAB A (2016) SM-T280. 

Their comments:
I have uninstalled and reinstalled new APP and it’s worse.
The attached is just a couple of examples. By and large they all cut the heads off pictures and people. 

(I CANNOT ATTACH THE PICTURES SINCE THEY ARE TOO BIG)

**Comment by aprojas** [comment]
This is also happening for the GECO survey (I suppose it happens to all surveys, but only some users realize it)

This display is in Diego's phone:
Sony Xperia Z5 E6653 Android 7.1.1

![Screenshot_20190530-153142.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/66c4e080-d0bc-4a03-b7e2-a20095b72630)

![Screenshot_20190530-153703.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/8b91e533-d159-4dda-a507-f63be29b2c55)

**Comment by Danman7** [comment]
Fixed by reverting the indicators slider.
