### ISSUE TITLE
Overplaced text in socioeconomic question

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#714]
In the UK survey, in the socioeconomic section, the dropdown answers of the textbox overplace (not sure if it's the correct word) the question and is not in the appropriate space.

![Screenshot_20190530-000757_Stoplight Mobile.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/c3f4cd7b-12b5-4dc4-b45c-647c36d2f19c)

**Comment by Danman7** [comment]
This also includes a case where long question labels don't go on 2 lines and don't show completely.
