### ISSUE TITLE
The sync circle doesn't stop loading in families screen

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#716]
In the families profile screen, the synchronization circle never stops loading. 

![Screenshot_20190530-001113_Stoplight Mobile.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/0acad6a4-f7db-45ae-b1fe-a68ec9dcc57e)

**Comment by Danman7** [comment]
We've been testing a few times and can't reproduce this.

@aprojas The fetch families request usually takes around 15 secs on demo. Are you logging in with demo?

**Comment by stacylorraineprendeville** [comment]
@aprojas please respond on this or we close

**Comment by aprojas** [comment]
This can be closed @stacylorraineprendeville @Danman7
