### ISSUE TITLE
App crashes on Create a new survey

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#718]
Ana wrote:
```
I logged in in the app with
username: gecouser
password: gecouser

It still crashed when I clicked on "Create a new survey"
```

We need to investigate this particular user and use case. We may find what is causing the issues all over the app by narrowing it down.

**Comment by aprojas** [comment]
The app also crashes when I log in with demo/demo. I really think it might only be my device.
When @diegotorrespy  logs in with his phone with any user, it works perfectly fine. 
He is in the internal testing track right?
@Danman7 @stacylorraineprendeville
