### ISSUE TITLE
Conditional question not showing 

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/MentorApp#726]
There is a Sierra Leona conditional question which is not showing in the app  "if no, how does your family obtain water"  this question should appear if the previous question "Does your house have a water service" is answered NO.

This is working in the web app at this moment, so it is unlikely to be a survey definition bug.

**Comment by stacylorraineprendeville** [comment]
@JDelPuerto leave new issues in "new issues" here we review and add to the pipeline. If it is high priority it will most likely NOT be seen in grooming pipeline. As a BUG you can always move direct into bugs.

**Comment by aprojas** [comment]
This is already working in demo! Ready to deploy
@vasildimitroffhristoff @JDelPuerto
