### ISSUE TITLE
Socioeconomic questions are not completely visible

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#728]
In the GECO survey, I was not able to read all of the questions because it was not showing. It stopped showing when the screen finished. So, it didn't have two lines. 
It only appeared when I chose an answer.

This happened with the following android device:
Sony Xperia Z5 E6653 Android 7.1.1

![Screenshot_20190530-153035.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b37e27c5-c9f4-4734-b2ea-f806d89124c1)

**Comment by zommerberg** [comment]
Already fixed in 714
