### ISSUE TITLE
TypeError: null is not an object (evaluating 'f.surveyConfig')

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#739]
Sentry report: https://sentry.io/share/issue/59ca6fba9dde4959a608efcf0a1161bf/

The Ecuador people are experiencing this in `familyParticipant.js` and it's related to `let docValues = survey.surveyConfig.documentType`. Check if you see this in the Ecuador survey. Maybe we need a case where there is no document type in the survey config.

Same thing with, the same Ecuador people, happens for:
- `survey.termsConditions.title` in Terms.js (report: https://sentry.io/share/issue/ae9f2f8eab6b48d4bc136285890ded1f/)

**Comment by zommerberg** [comment]
we no longer use let docValues = survey.surveyConfig.documentType
