### ISSUE TITLE
GIT HUB Vulnerability

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#744]
Please investigate

![Screen Shot 2019-06-06 at 12.10.36.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/c474110f-1ae5-4cf8-a73a-bfbd726af9fb)

**Comment by Danman7** [comment]
This is a new feature that GitHub has introduced. One of the nested dependencies we have is an old version. I will update all sub dependencies in bulk.

**Comment by Danman7** [comment]
Fixed by 245b17c7d3c65b9e4c4f99bf8c46f6794eb46f78
