### ISSUE TITLE
Remove Postal Code option in Online Map Search

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#747]
When I'm taking a survey and I'm online,
The search bar of the map says "address or postal code". 
However, if I add a postal code, nothing happens. 
This was previously reported by the UK, but it does not work either here in Paraguay. 

Please remove this from the text and thus we avoid the confusion.

**Comment by zommerberg** [comment]
Is that the right translation for "Search by street" ? Búsqueda por calle

**Comment by stacylorraineprendeville** [comment]
@zommerberg make sure to tag @aprojas  :)

**Comment by aprojas** [comment]
Hi @zommerberg yes it's correct!
