### ISSUE TITLE
Opening Screen Flash of Distorted Logo + Missing Text

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#75]
As you you open the app - A large distorted version of the logo appears before resizing to the correct version.
Please remove this - The correct version on load is:
Please note the poverty stoplight logo text as the title and branding of the app
<img width="300" alt="screen shot 2018-11-26 at 17 06 32" src="https://user-images.githubusercontent.com/45012899/49039164-c1e57500-f19d-11e8-8101-9ff6099abbba.png">

**Comment by Danman7** [comment]
Fixed splash screen stretching in 89a5b93f62b06301cb545b5064319ae08516061a. As we are expecting changes to the design of the logo itself we will implement this later.
