### ISSUE TITLE
Lifemap States and Possibilities

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#754]
This issue is to discuss lifemap states and the permissions of what can and cannot be done on a lifemap from the mobile app.

**Comment by stacylorraineprendeville** [comment]
See description in the blocking issue - From here we can make a more technical spec. @Danman7 @vasildimitroffhristoff

**Comment by vasildimitroffhristoff** [comment]
How is this relevant for retaking. And are there any next steps on this?
