### ISSUE TITLE
familyMemberDraft.gender - undefined is not an object

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#758]
Sentry reports: https://sentry.io/share/issue/df63c9d35131434d874b936583108f81/, https://sentry.io/share/issue/329c997b9ba241b7be47b742453057f8/

Chile people have experienced the above crash. It's related to the gender field in `FamilyMembersNames.js` and possibly to the `other` fields functionality.

**Comment by zommerberg** [comment]
The client received the error on the old version of the FamilyMembersNames component, i believe this is no longer an issue because we completely changed this component and i cannot reproduce it right now.
