### ISSUE TITLE
Android Header elements styling

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#76]
Currently the android header elements (i.e.Battery power/Time/etc...) are in white. This causes a usability issue in visibility.
The correct colour is #7A756F
The visualisation then should be
<img width="303" alt="screen shot 2018-11-26 at 17 10 23" src="https://user-images.githubusercontent.com/45012899/49039451-91520b00-f19e-11e8-987c-006e1aad587e.png">

:

**Comment by Danman7** [comment]
As per documentation it is not possible to change the icon colors themselves, only the background color: https://facebook.github.io/react-native/docs/statusbar. The icons have one of two themes (light and dark) which are set through the barStyle prop. I've researched and tried a lot of hacks, but this doesn't work.

**Comment by stacylorraineprendeville** [comment]
@Danman7 
Here you can see in the image - There is a change from the previous version - but the background is now transparent - so this means I still cannot see the header elements
![img_0404 copy](https://user-images.githubusercontent.com/45012899/49594372-7d539980-f954-11e8-86a2-1b2787f90f5a.jpg)

**Comment by Danman7** [comment]
The quality is good enough. I assume you are talking about the invisible icons at the top.

**Comment by stacylorraineprendeville** [comment]
This issue re-appeared after a new app update. When I removed the cache it re-appeared again.

**Comment by stacylorraineprendeville** [comment]
I have now lost the styling on these elements.

**Comment by stacylorraineprendeville** [comment]
@Danman7  Lets just use black background and white icons - I presume this resolves the issue - correct?

**Comment by Danman7** [comment]
Yes, est at 1.
