### ISSUE TITLE
App crashes in Geco survey (internal track)

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#762]
In the internal test track:

The app crashes when taking a Geco survey AFTER selecting the "nationality" in the socioeconomic section. 
It was taken ONLINE.
The device was a Samsung Note. (Edu)

This happened with my Samsung tablet too.

**Comment by Danman7** [comment]
Found the sentry report: https://sentry.io/share/issue/c7e1fb39c8fc4af0b4ca21c4eb08df9b/
