### ISSUE TITLE
Email or Save file to Phone at end of lifemap

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#769]
Currently online we will shortly add the option to print the lifemap in an improved format.
We are also actively reviewing the options of emailing the lifemap and downloading the lifemap.

This issue is an investigative spike.
What are our options from the mobile app to mirror the functionality above?

**Comment by stacylorraineprendeville** [comment]
@vasildimitroffhristoff do we have a seperate issue for the email? Was it included?

**Comment by vasildimitroffhristoff** [comment]
No, we don't. Just copied the online functionality
