### ISSUE TITLE
Fonts: Usage of Poppins

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#77]
Fonts utilised within the header area and within the supporting navigation should be Poppins.
Please refer to the invision file:
Currently Roboto is being used incorrectly.
Poppins is part of the brand identity of the poverty stoplight.
Roboto is our supporting font for legibility of smaller text.

**Comment by IvaKop** [comment]
Fonts in the navigation and headers are Poppins as specified in the design.

**Comment by stacylorraineprendeville** [comment]
See image below - We have Poppins in the text of the page - BUT in the header and in the primary navigation we do not
![img_0404 copy](https://user-images.githubusercontent.com/45012899/49594558-de7b6d00-f954-11e8-95ec-701c0e3ed5c0.jpg)
