### ISSUE TITLE
Add these 2 maps for Nelixia - Guatemala

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#778]
These are the 2 maps requested for Offline maps by the partner Nelixia. Is this okay or more info is needed?

1. Taxisco
![Mapa Comunidad Buenos Aires, Taxisco[69677].png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1db3a188-a63d-429f-952e-414f04eb792f)

2. Guanagazapa
![Mapa Nueva Todos Santos y Nueva Bendición, Guanagazapa[69678].png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ad63cf4d-8097-4191-ac8c-b7aea38409bd)

**Comment by vasildimitroffhristoff** [comment]
For downloading maps I need the boundaries. We would also need a center for each map. They can be formulated like this:

{
  "surveyConfig": {
    "offlineMaps": [
      {
        "name": "Taxisco",
        "from": [-90.5224, 14.0268],
        "to": [-90.3482, 14.1153],
        "center": [14.0712586,-90.4641823]
      },
      {
        "name": "Guanagazapa",
        "from": [-90.7447, 14.1658],
        "to": [-90.531, 14.2786],
        "center": [14.2258199,-90.6434727]
      }
    ]
  }
}

**Comment by JDelPuerto** [comment]
The maps are available on testing now @vasildimitroffhristoff
