### ISSUE TITLE
Text drops stick to screen after Primary Participant

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#779]
In the Emprender survey, when filling in information of Primary participant, the text drops still show in the screen even if I go through the survey. 
This was done with a Samsung tablet.

![20190610_100203.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/332e39f4-a39f-4cf7-8fed-d7280b0ede3a)

![20190610_100402.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5a2dbfda-d60a-4e9c-838b-9257fed536b5)

![20190610_100501.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/408dad74-6617-40bf-b0f6-21d2861c8ad4)

**Comment by stacylorraineprendeville** [comment]
Might well just be performance

**Comment by zommerberg** [comment]
i cant reproduce it on android KitKat, what version are you using? is this still an issue? @aprojas

**Comment by aprojas** [comment]
I'm going to check @zommerberg
