### ISSUE TITLE
A demo survey with NO mandatory questions

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#781]
For testing purposes we are constantly having to add fake data to get to the screens we want.
it wastes time.

For Demo purposes for Sales this is also uncomfortable and inconvenient - You just want to show someone the indicators but you are stuck filling out a screen of content in a demo.

This task would be to create a survey that ONLY exists in DEMO for the STOPLIGHT team.
It would show basic conditional on age.
Radio Buttons and Checkboxes
AND
would have NO mandatory questions in the family section.

It is only for high level DEMO´s (Leaders of FP) and TESTING

Thoughts?

**Comment by Danman7** [comment]
This will need a survey configuration property to determine if the survey has no mandatory participant details. Not sure if we have an issue for this at the backend. Otherwise I can groom it based on expectation that there will be one boolean prop that is going to make no property mandatory in the survey.

**Comment by stacylorraineprendeville** [comment]
@loorely Can you make a back end issue for what Dan is referencing here - Add it to the same epic and estimate - I will add it to the next sprint

**Comment by loorely** [comment]
@stacylorraineprendeville  Done, this is the issue: https://github.com/FundacionParaguaya/MentorApp/issues/811

**Comment by vasildimitroffhristoff** [comment]
@stacylorraineprendeville we will have drafts , where fields for first name, last name and so on won't be required and we agreed with Jorge to set them as null values. How should these be outputted in the draft list items on the Dashboard and the Families Screen.
