### ISSUE TITLE
Strange characters when taking a survey

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/MentorApp#784]
**Description**

At this moment, when a new lifemap is created in the mobile app, the request is going without the encoding system and sometimes the data contains accents and special characters like `ñ` that are being saved badly in the server.

**To Reproduce**
1. Create the a lifemap that contains accents or special characters like `ñ` with the mobile app.
2. Search for the created lifemap in the web platform, in the reports for example.
3. See the texts.

**Screenshots**
![special-characters-issue](https://user-images.githubusercontent.com/645391/59463174-5ab6a780-8df3-11e9-9340-7d02296b198a.png)

**Additional context**
This issue was solved in the previous version of the lifemap online in the issue: https://github.com/FundacionParaguaya/fp-psp-frontend/issues/343, related to the encoding format in the front end.

**Comment by Danman7** [comment]
We have removed the URI escaping we applied to fix the strange symbols in the front end as it apparently had a side effect. We will think of another solution.
