### ISSUE TITLE
Wrong display of header in small screens

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#788]
With a small screen (specifically SAMSUNG NOTE phone), the visualization is not optimal.
(reported by Edu)

The following screenshot is from the GECO survey: 

1. Too much white space in the header where the indicator name is
![Screenshot_20190613-211929_Stoplight Mobile.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/2be108e7-8e1d-4924-9e1e-c50dba55eac5)

**Comment by stacylorraineprendeville** [comment]
@aprojas please split this into two issues
1 for form fields

1 for header space - Please note the headspace issue will be iced - explain to Edu if you allow one client to add 250 plus characters in one title and then 30 in another this will always happen.

Both of the above issues should additionally be in the mobile app repository

**Comment by aprojas** [comment]
Ok @stacylorraineprendeville just updated this.
