### ISSUE TITLE
Indicator Definitions

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#789]
As a user
when I am viewing an indicator
** and this indicator has a definition defined in the survey **
when I click on the i icon
I want to see a modal window with the indicator definition text
so that I can read more before answering.

The navigation element: (i con)
![Screen Shot 2019-06-14 at 17.09.54.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/af2f6883-dcf0-42e1-a4a1-38b1633bbd45)

The modal window:
![Screen Shot 2019-06-14 at 17.10.38.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ff5f9b61-5749-4b90-a2ca-c940daa76cc1)

**Comment by stacylorraineprendeville** [comment]
@Danman7 can you make sure we can use the existing scollbar that was made for the indicators - I guess we can re-use - correct?

**Comment by zommerberg** [comment]
I need to get the required text for each indicator with defined definition from the back end.  @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@zommerberg this is already working on the front end in the platform - so contact anyone from the team to make this happen

**Comment by zommerberg** [comment]
Could i get the translation for "Indicator definition" @aprojas

**Comment by aprojas** [comment]
"Definición del indicador" @zommerberg
