### ISSUE TITLE
Auto select of First Form Field

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#79]
On entering a form based page - the first field of the form should be auto-selected for input.
This is a usability requirement.
<img width="290" alt="screen shot 2018-11-26 at 17 25 40" src="https://user-images.githubusercontent.com/45012899/49040086-5b158b00-f1a0-11e8-880f-7f6c615e54f5.png">

**Comment by Danman7** [comment]
This can be achieved with `autoFocus` prop.

**Comment by Danman7** [comment]
Is closed in #538
