### ISSUE TITLE
UI Improvements to life map completion and priorities screens

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#793]
#### The current page for when you complete the lifemap is results focussed and not interesting! It should be more celebratory. 
![Screenshot_20190617-142635.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/0338403f-5489-4e0c-ab6a-e629966cfeec)

## Adding a priority is quite a sad affair ;)

![Screenshot_20190617-142641.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/b8ef694d-458e-4ccb-bd8d-bd42ea9ca002)

#### This takes aims to improve this.

Step 1: When you reach the life map conclusion page you receive a lifemap that fills the screen with a congratulations message. This is a preview screen. Clicking on continue takes you to the next screen. If you can make the balls animated in some way flickering on and off briefly? - Something to also liven up the page?

![Screen Shot 2019-06-17 at 20.34.36.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e451b135-3b7a-451a-9030-3a39deb99e2a)

Step 2: Continuing from the previous screen you go to the dedicated priorities page - Here we really explain the process. See the static text relating to the number of mandatory priorities (if there are) embedded into the text (it does not need to countdown). Clicking on continue without completing the priorities would STILL give you the existing pop footer message if priorities were required.

![Screen Shot 2019-06-17 at 20.38.52.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/1063fa78-7d7f-4685-92de-fcd9f634fbda)

Step 3:Don´t take the user to a seperate page to create a priority use a pop/up modal instead- Remember later we will make many improvements to priorities - For now lets just improve the interface of what we have and not complicate things. Please check as part of this task the text input fields for what will I do to get it - Can we have text fields? We really need mulitline here

![Screen Shot 2019-06-17 at 20.46.46.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/5b32fc30-c8b4-4405-8408-27f4bcb2a689)

**Comment by Danman7** [comment]
@stacylorraineprendeville We can add multiline text fields. We can groom based on this design.

Otherwise this is a restructure of the screens after skipped indicators. Some screens become modals (can still be displayed as screens in terms of the navigation, just appear as modals).

**Comment by stacylorraineprendeville** [comment]
@Danman7 if you need another issue for the mulitline can you make one....:)Add it to the same epic

**Comment by zommerberg** [comment]
could i get all of the required translations?

**Comment by zommerberg** [comment]
@aprojas

**Comment by stacylorraineprendeville** [comment]
@zommerberg which texts are NOT in the app currently?

**Comment by aprojas** [comment]
Is it ok "Make priority" and "make achievement"? Sounds strange. 
Shouldn't be make a priority or make it a priority? 
Make achievement I think should be Write your achievement!

These are the translations: 
Elige 5 indicadores y explica por qué son importantes y que harás para conseguirlos.
¡Hazlo una prioridad!
¡Define tu logro!

Please @stacylorraineprendeville confirm

**Comment by zommerberg** [comment]
could i also get the translation for the " You created a Life Map" and "congratulations" and "now lets make some priorities"?
The text that is not in the apps is
-You created a Life Map
-congratulations
-Make priority
-make achievement
-the long text about the priorities
-now lets make some priorities

**Comment by stacylorraineprendeville** [comment]
@aprojas @zommerberg 
This is overcomplicating - We use these terms in the app currently.
Please review them Ana and tell us - Was it create or make priority
and No in english you can say either make a priority or make priority. Depends on how it is -
Please first confirm what is existing and help me out on this guys

**Comment by zommerberg** [comment]
-we have "achievement" and not "make achievement"
-we have "priority" and not "make priorities"
-we have "Create a life map" and not "You created a Life Map"
-we have "You need to add %n priorities" and not "Choose %n indicators below and explain why they are important and what you will do to achive them!"
-we dont have "congratulations"
-we dont have "now lets make some priorities"
@aprojas @stacylorraineprendeville

**Comment by zommerberg** [comment]
One more question. If there are no mandatory priorities what should i show? no message at all or "create priorities" @stacylorraineprendeville  @aprojas 
<img width="281" alt="Screenshot 2019-06-26 at 13 25 50" src="https://user-images.githubusercontent.com/43446836/60172825-2214c600-9816-11e9-9614-9e68ee7bd345.png">

<img width="277" alt="Screenshot 2019-06-26 at 13 26 52" src="https://user-images.githubusercontent.com/43446836/60172826-2214c600-9816-11e9-9b87-4e79b01b7b0d.png">

**Comment by stacylorraineprendeville** [comment]
The text where you say create priorities is not correct
It should state  as per above in the design
"Choose 5 indicators below and explain
why they are important and what you will do to achieve them!"
The idea was if this is not mandatory to remove the "5" and replace it with either nothing or I guess for better english "from the"

**Comment by stacylorraineprendeville** [comment]
<img width="353" alt="Screen Shot 2019-06-26 at 12 58 45" src="https://user-images.githubusercontent.com/45012899/60174795-263ee480-9812-11e9-9f85-a4608c7e45be.png">
@zommerberg

**Comment by Danman7** [comment]
@stacylorraineprendeville @aprojas Could you guys five translation for the final screen? The choose N indicators below. We will put the number where we need to.

**Comment by zommerberg** [comment]
+ all the other translations

**Comment by aprojas** [comment]
**Achievement**: Logro 

**Priority**: Prioridad

**Create a life map**: Crear un Mapa de Vida

**Choose %n indicators below and explain why they are important and what you will do to achieve them!**:
¡Elige %n indicadores y explica por qué son importantes y que harás para conseguirlos!

**Congratulations**: Felicidades

**Now let's make some priorities!**: Ahora, ¡escribamos algunas prioridades!

@stacylorraineprendeville Do you think these are correct?
----------------------------------
In the web app: it says "Make this a priority!" and "Mark achievement!"
Shouldn't it be the same? @stacylorraineprendeville @zommerberg @Danman7 

![priority](https://user-images.githubusercontent.com/44477708/60293397-1d6f1100-98ed-11e9-8ece-8f6ea1728e6c.PNG)

![achievement](https://user-images.githubusercontent.com/44477708/60293408-22cc5b80-98ed-11e9-963e-6f73c8b89eea.PNG)

**Comment by zommerberg** [comment]
If we dont have any mandatory indicators - what should it say in spanish and english?
-Choose some indicators below and explain why they are important and what you will do to achieve them!:
-¡Elige indicadores y explica por qué son importantes y que harás para conseguirlos!

**Comment by stacylorraineprendeville** [comment]
@aprojas Yes ana - All text should be aligned - We are running into difficulties as this  terminology is not very clearly defined. 
Can you confirm exactly what is the terminology in the app currently and that of the online - then we can create the issues required to align this. We need to look at both english and spanish as often these are different.

**Comment by stacylorraineprendeville** [comment]
@zommerberg 

Choose from the indicators below and explain why they are important and what you will do to achieve them!:
¡Elige de los indicadores y explica por qué son importantes y que harás para conseguirlos!

**Comment by stacylorraineprendeville** [comment]
@zommerberg still not done!

**Comment by zommerberg** [comment]
What is not done? the animations of the balls? @stacylorraineprendeville
