### ISSUE TITLE
Form fields don't fit whole socioeconomic question

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#794]
With a small screen (specifically SAMSUNG NOTE phone), the visualization is not optimal.
(reported by Edu)
The following screenshots are from the GECO survey.

The titles do not fit and the questions do not fit within their box.

![Screenshot_20190613-211740_Stoplight Mobile.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5c9444a3-5140-4a65-a0d5-7356c3efead2)

**Comment by Danman7** [comment]
We weren't aware there was a separate issue about this. This should already be in version 1.9.11
