### ISSUE TITLE
Map functionality does not allow user to pin location

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#80]
When a user is within the location section the ability to pin to a location is not possible.
i.e. On interacting with the map the user cannot choose a new location. The red location pointer is not "movable" neither by double or single click.
The only option is to proceed with the preselection.

- [x] The user should be able to move the red pin of the location to a new area.
- [ ] Generally on google maps a blue circle appears to show the user the location exactly to where they are. Options here?
- [ ] We must add a button for usability to aid the user in choosing/selecting a location - The current implementation is not clear -that of using the continue option as selection-because it is not implicit to the user - A proposed example is below:
<img width="363" alt="screen shot 2018-11-27 at 18 41 37" src="https://user-images.githubusercontent.com/45012899/49113360-21ae4f80-f274-11e8-8fb0-116fc8eaeeab.png">

**Comment by stacylorraineprendeville** [comment]
@Danman7 I also believe that we need a button to "select this location" - I will create an enhancement issue for this.

**Comment by stacylorraineprendeville** [comment]
@Danman7 This for me should be the highest priority after bugs the crash that system.
@pA1nD you agree?

**Comment by Danman7** [comment]
Have you tried holding on top of the marker until it moved slightly up (used if you are doing it with a finger so you can see it). I cannot reproduce the issue with changing the marker on any device or emulator I have. I can alway move the marker on new or old devices.

**Comment by stacylorraineprendeville** [comment]
Feel free to split the issue and create an enhancement issue in line with your needs Dan. You can then assign enhancement issues to me if they require further specification..
----------------------------
Regarding the functionality I struggle to use the map in this state. I had not understood the wait time on holding the marker and I feel other users will struggle. Two people here that have used it said that the map does not work.
Can we find a better solution?
In the earlier PSP app I could drag the map with one finger - at the same time the red pointer remained in a centre place - This ensured I could easily plot the point to my area. As our users are already using this functionality could we implement this? 
Right now when I scroll around the map I simply loose sight of the pin....
@pA1nD @gigerbytes Your thoughts please...

**Comment by Danman7** [comment]
I have made the map update on drag and the marker is centered. I can implement the button at a later stage.

**Comment by pA1nD** [comment]
@Danman7 cannot reproduce and question can be deleted here, yes?
