### ISSUE TITLE
Amends to "preparing app" screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#816]
This is two part.
1. Referring to the app preparing as "synching" is causing confusion when we debug. Lets remove this
2. A better design - Our users get stuck on this page and have no idea how long things are going to take - Progress bars per element would help.
3. Animation - Happier page :)

Add animation
![Screen Shot 2019-06-20 at 18.56.39.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/45fff4a6-196b-4718-9966-9c37c8880581)

Additional message when things are going slow
![Screen Shot 2019-06-20 at 18.57.52.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/dffd361c-60ce-4a1c-b2d0-5c0989024e2b)

**Comment by zommerberg** [comment]
When should the message "Hmm.. it might take a while" appear? when we start downloading the maps? @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@zommerberg I thought it already existed - It was something we added way back when Bjorn was with with us more - Time related to if things were really slow.
If it is not there it is NOT a request to create it

**Comment by Danman7** [comment]
@stacylorraineprendeville This was added back when we started the app and we almost immediately removed it with Iva as the way we did it back then was problematic. We never re-introduced it. So we don't have it and what Pavel is making is better than what was there.

**Comment by Danman7** [comment]
@zommerberg Can you switch the word `syncing` with `downloading`?
