### ISSUE TITLE
Error when opening the app

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#820]
I cannot open my app since it shows that I already logged in with a 1-survey screen loading forever. But when I click the back button and write in the credentials of t/demo, the same loading screen appears. 

This is what happens:
I log out
I close all of the apps
Then I open the app
And it still shows that screen as if I logged in before.
But I already saw that I logged out

I also restarted the tablet but nothing happens. 

![Screenshot_2019-06-21-08-42-50.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/14dad9f6-b6c5-4877-9f80-250d4d6cb16f)

**Comment by Danman7** [comment]
This shoud be fixed with #823
