### ISSUE TITLE
Emprender conditional issues in Mentor App

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#824]
1. If answer of "Actualmente estudia?" (of screen EDUCACION) is si, then it should show D52, D53 and D56, but it does not show D56, it only shows the other 2. - Vasil has fixed this.....waiting for new deploay
2. The questions D66 and D67 (of screen EMPLEO) are not shown in any case.. This is strange because I think  I tested it before, and it did show! - Vasil has fixed this.....waiting for new deploay
![Screenshot_2019-06-24-07-54-34.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/3c294dc3-4a66-45ba-86fc-7e3682b4a1b9)
3. The D65 should be a numerical option. (With Jorge) - Vasil has fixed this.....waiting for new deploay
4. The pictures of the indicators are not shown since "Fuente de ingreso diversificada".  I waited for 10 seconds for most of them, and they do not show. I was taking the survey online.
![Screenshot_2019-06-24-08-02-24.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/39c1c7f1-f4cc-499f-9264-f799c8495e0a)
![Screenshot_2019-06-24-08-03-23.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/32df87d0-5489-4dca-a452-7b3ab200ba92) - With Dan - Having problems reproducing this.....

5. MAP: I was online, but it didn't take me to my actual location, it took me to another city in Argentina. - With Ana/Dan/ This should route to Columbia.....Having problems reproducing this (demo + demo)

**Comment by Danman7** [comment]
I'm taking 4 and 5.
