### ISSUE TITLE
New family not added to the Families list

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#83]
When I create a new life map and complete the process - Then I reload the app and see my draft displayed the corresponding family is not listed in the families page.

As part of the creation of a new lifemap a family should be created and added to the families list.

Additionally but part of this same issue it should not be possible that a draft does not have a family.
Currently drafts can be saved without a family.

**Comment by Danman7** [comment]
Duplicate of #94 

@gigerbytes @stacylorraineprendeville Since you are posting issues related to this: This functionality is not been worked on and is not planned in this release.
