### ISSUE TITLE
Strange text in Retry screen

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#834]
Dan commented: That is either missing or broken translations.

![Imagen de iOS (3).jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b221604d-21b0-4318-b2d3-46c5f43112a8)

**Comment by Danman7** [comment]
We have no spanish translation for this phrase.

@aprojas We need translation for `{n amount of} items have a sync error`. Not the part in the `{}` brackets. It's only for context.

**Comment by aprojas** [comment]
{number} elementos tienen un error de sincronización.

@Danman7

**Comment by zommerberg** [comment]
we also need a translation for  "syncErrProblem": "Looks like we have a problem!"

**Comment by stacylorraineprendeville** [comment]
@aprojas

**Comment by aprojas** [comment]
¡Parece que tenemos un problema!

@zommerberg
