### ISSUE TITLE
Translation missing for "Retry"

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#835]
The button "Retry" is missing a translation for Spanish. 

Could it be "Reintentar", "Intentar de nuevo", "Sincronizar de nuevo". ?

What do you think?
@stacylorraineprendeville 

![Imagen de iOS (3).jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/728fca74-b09f-4ad8-8929-b7e85a2615a1)

**Comment by stacylorraineprendeville** [comment]
Reintentar @aprojas

**Comment by Danman7** [comment]
This is a duplicate. Please refer to #834 for what we need in terms of translations.
