### ISSUE TITLE
Reduce required permission for the app

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#836]
Do we need all the permissions we are asking for? Don't take more than an hour to see.

**Comment by zommerberg** [comment]
I did some research and right now we need all of the permissions:
android.permission.INTERNET - for internet access and debug mode
android.permission.VIBRATE - fir vibration
android.permission.READ_EXTERNAL_STORAGE /android.permission.READ_EXTERNAL_STORAGE - for pdf related stuff
