### ISSUE TITLE
Changes to Achievements text

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#840]
The current achievements text is difficult to understand.

Please change the questions to: 

Question 1: “What did you do to achieve this?”
Question 2: “Who or What motivated you to get there?”

**Comment by zommerberg** [comment]
can we also get the spanish translations?

**Comment by stacylorraineprendeville** [comment]
@zommerberg please tag @aprojas

**Comment by aprojas** [comment]
Question 1: “What did you do to achieve this?”
- ¿Qué hiciste para conseguirlo?

Question 2: “Who or What motivated you to get there?”
- ¿Quién o qué te motivó a alcanzarlo?

@zommerberg
