### ISSUE TITLE
Amends to "preparing app" screen #2

### ISSUE THREAD

**Issue by zommerberg** [FundacionParaguaya/MentorApp#844]
Currently we dont receive the number of families and the number of surveys so we cant make it in % like in the screenshot below.
We need to know how many families/surveys are in total and how many of them we are already downloaded so we can know the %,just like the maps and images

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563313966666139613839366461356438336436613064302f34356666663461362d313936622d343731382d393936362d396333376338383830353831.png](https://images.zenhubusercontent.com/5ca1c17b45147541ad689fff/a5b8065f-22b2-4c00-892c-d35adcfeedc9)

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #794](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/794) via [**ZenHub**](https://www.zenhub.com/)
