### ISSUE TITLE
Dropdown population within mandatory Poverty Stoplight form elements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#85]
The elements that should populate the dropdown elements are listed within the google "forms" document (access provided on request). 
Within the participant details section and the family members section we have incorrect data population. For instance currently in the app unde
Gender we have the titles Female/Male/Prefer not to disclose 
however the correct version of this is:

- Male
- Female
- Other
- Rather not say

This is throughout the mandatory poverty stoplight section of the forms.

**Comment by stacylorraineprendeville** [comment]
@pA1nD Is this known?

**Comment by pA1nD** [comment]
@stacylorraineprendeville this is not a bug. This is a value that you can configure in the Survey Editor (or as long as it's not there in the Database)! Therefore it can be different in any survey and is dynamic data!
