### ISSUE TITLE
Add maps for Emprender

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#855]
These are the following areas in which Emprender need for offline maps, it is ordered by priority:

1. Antioquia
https://www.google.com/maps/place/Antioquia,+Colombia/@7.1454347,-77.7479047,7z/data=!3m1!4b1!4m5!3m4!1s0x8e4429b2d9a8a783:0x540a36ca7581959a!8m2!3d7.1986064!4d-75.3412179

2. Bolívar https://www.google.com/maps/place/Bol%C3%ADvar,+Colombia/@8.8946644,-77.0186116,7z/data=!3m1!4b1!4m5!3m4!1s0x8e58d045e0af6885:0xa6019304f60f9615!8m2!3d8.6704382!4d-74.0300122

3. Atlántico
https://www.google.com/maps/place/Atl%C3%A1ntico,+Colombia/@10.6810271,-75.5517449,9z/data=!3m1!4b1!4m5!3m4!1s0x8ef42d42d5e8daf3:0x47f316b8b238017f!8m2!3d10.6966159!4d-74.8741045

4. Casanare
https://www.google.com/maps/place/Casanare,+Colombia/@5.341483,-73.1640948,7.69z/data=!4m5!3m4!1s0x8e6b0c344eb87e33:0x28f41949c946a900!8m2!3d5.7589269!4d-71.5723953

5. Meta
https://www.google.com/maps/place/Meta,+Colombia/@3.2646689,-75.2407958,7z/data=!3m1!4b1!4m5!3m4!1s0x8e164161220f4a6f:0xd6451c8f086f37c6!8m2!3d3.2719904!4d-73.087749

6. Bogotá
https://www.google.com/maps/place/Bogot%C3%A1,+Colombia/@4.6482422,-74.3880189,10z/data=!3m1!4b1!4m5!3m4!1s0x8e3f9bfd2da6cb29:0x239d635520a33914!8m2!3d4.7109886!4d-74.072092

7. Caldas
https://www.google.com/maps/place/Caldas,+Colombia/@5.2896123,-75.8344707,9z/data=!3m1!4b1!4m5!3m4!1s0x8e473d9c128bde71:0x680d4e47949c9e8c!8m2!3d5.29826!4d-75.2479061

8. Córdoba
https://www.google.com/maps/place/C%C3%B3rdoba,+Colombia/@8.3973047,-76.7685247,8z/data=!3m1!4b1!4m5!3m4!1s0x8e59ba9ae89045f3:0x891a27b2b7a97e22!8m2!3d8.049293!4d-75.57405

**Comment by loorely** [comment]
@aprojas @JDelPuerto ready to check in testing

**Comment by aprojas** [comment]
I cannot see this in testing in the mentor app!
I am offline and with the location on, there is no list of maps, it just shows me the coordinates.

@loorely @JDelPuerto

**Comment by stacylorraineprendeville** [comment]
@zommerberg in light of hwat we asaw today maybe this is interesting for you?

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you update the comments with the latest status report here - so that it can be tracked

**Comment by aprojas** [comment]
I tested this in the Internal test track and it works fine!
@stacylorraineprendeville
