### ISSUE TITLE
App Updates Messages

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#857]
We need to inform users to update the app. 
This is because we cannot avoid breaking changes in the app, we should give pre-notice to the users of around 2 weeks to 1 months. 
There should be a release that will be able to cope with the breaking changes without them being applied, yet. 
For this reason, we introduce a protocol (tbd) how the frontend can get information of the availability of an important update. 

This is a design to show this information and ask the user to update the app.

Final designs - https://invis.io/YVPU88VBQRU
OJO! Wording might change!
![Screen Shot 2019-07-04 at 11.49.59.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/6068c409-f44c-40c3-8791-82347db02fa3)

**Comment by stacylorraineprendeville** [comment]
@javierpf @Danman7 I thought we had an epic for this?

**Comment by Danman7** [comment]
We need the backend to have a way to communicate app states via API. We can discuss this @diegotorrespy @loorely

**Comment by stacylorraineprendeville** [comment]
@javierpf This is where we need the epic to cover the back end work

**Comment by Danman7** [comment]
We are waiting for backend to document how this will be implemented. We can't put it in a sprint until that happens.

**Comment by stacylorraineprendeville** [comment]
@javierpf @Danman7 
Can you get this grooming

**Comment by Danman7** [comment]
These are the docs: https://github.com/FundacionParaguaya/FP-PSP-SERVER/wiki/API-Versioning
