### ISSUE TITLE
UK Signal survey has no indicator images

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#861]
![Screenshot_2019-07-03-09-52-22.png](https://images.zenhubusercontent.com/5c2c8f966098e40af396a45d/fcf89a60-843d-4567-9810-c7b7d4a93b3c)

Ana reported internally that she can't see indicator images. I have been able to reproduce it.

**Comment by aprojas** [comment]
I still cannot see them @Danman7

**Comment by Danman7** [comment]
Closing as Ana has reported this happens only on her device. I can relate this to #631 and we will track it there.
