### ISSUE TITLE
Fix bug in radio buttons

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/MentorApp#862]
The bug  it's present in radio buttons for family members.Data for testing is in Banco Solidario Survey in testing.

**Comment by gonzarodriguezt** [comment]
Issue moved to [FundacionParaguaya/stoplight-web #495](https://github.com/FundacionParaguaya/stoplight-web/issues/495) via [**ZenHub**](https://www.zenhub.com/)
