### ISSUE TITLE
Retry pending sync drafts

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#863]
At the moment when you click on a pending sync draft:
![Screenshot 2019-07-03 at 17.36.46.png](https://images.zenhubusercontent.com/5c2c8f966098e40af396a45d/2ef331c6-bdc7-471a-ad1e-f6a826371f63)
the user is sent to the family screen, with the lifemap tab open:
![Screenshot 2019-07-03 at 17.36.30.png](https://images.zenhubusercontent.com/5c2c8f966098e40af396a45d/a9017d54-6ed0-4f7c-96e9-c15e3cc9de88)

When the user taps on in progress drafts or sync errors, he gets sent to the resume draft. The reason pending syncs behaves differently is that if the user tries to re-submit the draft it will result in duplicated lifemaps in the DB after device goes online.

We have reached a situation when the user would need to retry syncing these drafts, so we need a button for him to retry. We will make the button available only, when online.

**Comment by stacylorraineprendeville** [comment]
@Danman7 we are missing the central image in the image above?

Here is the design with a button added

![Screen Shot 2019-07-04 at 13.40.42.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/1e6e6a7c-1a79-4937-8574-13d805fd261d)
