### ISSUE TITLE
Map on Draft does not consistently show location

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#87]
When I login to the app and the choose an existing draft, then navigate to the location page. The map does not load.
The spinning cursor appears "getting your location" and continue without end.
This bug is intermittent - sometimes it works - sometimes it does not.
I am testing with full internet connection

**Comment by Danman7** [comment]
Since this was reported, I've introduced a 20 second timeout to the call and inserted a very minimal timeout error to the top of the map if they pass and no location: d1b41eabbb97e38a21c030ec2c3b9f9f350e9675. I will implement the proper UI for the map after all issues and stability is handled.
