### ISSUE TITLE
UK crash in resuming draft button

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#870]
UK is showing demo surveys to new clients and this crash happened:

1. July 2
They reported that their app crashed when they resumed draft with demo/demo.
2. I asked them to update the app. 

July 4
1. They have updated the app to the latest version 1.9.12
2. They logged in with demo/demo
3. They completed a survey to the half, they closed it to save a draft. 
4. They opened the draft, and when they clicked on "Resume draft" in the stoplight indicators section, the app crashed. 

I tried to reproduce this in demo/demo with my app and I cannot do it. 

July 8
New update available that will fix this issue 1.9.13
Uk updated the app and said that it worked for them! Good news.

**Comment by Danman7** [comment]
This is a known issue that has already been fixed in #850 and is in production

**Comment by Danman7** [comment]
Still an issue: https://sentry.io/share/issue/0db5d754ac5345779ca64dcc6034cd8e/

**Comment by stacylorraineprendeville** [comment]
@zommerberg @vasildimitroffhristoff where are with this?
