### ISSUE TITLE
Life Map - Editorial Revision

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#875]
the correct spelling of Life Map
is

Life Map

with capitalised letters. 
This is confirmed by the Methodology team.
Please ensure this is in place in the app.

**Comment by zommerberg** [comment]
Just to confirm.
If we have "Create a life map" i simply havge to change it to "Create a Life Map" with uppercase ,and if we have "To complete the lifemap..."  i have to change it to "To complete the Life Map...". 
Is that correct? @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@zommerberg correct - strange but it is what methodology ask for!
