### ISSUE TITLE
Send email with lifemap at the final screen 

### ISSUE THREAD

**Issue by vasildimitroffhristoff** [FundacionParaguaya/MentorApp#876]
Currently we have options to print the lifemap in an improved format and download it as pdf file. We want also to be able to send it as and email.

Currently we have options to print the Life Map in an improved format or download it as PDF file. We want also to be able to send it as and email.

Specs:
1. Create an extra button before PRINT and DOWNLOAD, that says EMAIL.
2. When the user taps on EMAIL button, the Life Map in PDF will be sent to their email that was introduced at the beginning of the survey.
3. If the user did not include an email at the beginning of their survey, then the button should not appear.
4. When the user taps on the button, a pop up should appear with the same message that appears in the Web App.

Observation: This already is working in the Web App.

**Comment by stacylorraineprendeville** [comment]
and in the instance the client has NOT given an email - this option will NOT appear?

**Comment by vasildimitroffhristoff** [comment]
Yes, this should not be visible if the client hasn't added an email.

**Comment by Danman7** [comment]
@kranelox @aprojas These are the specs for the remainder of the task as discussed with @loorely and @diegotorrespy. If something is not right, please notify us before work starts.

## Overview

The goal is to send an email to the client with their lifemap as a PDF once the mentor that took the survey gets back online. This will be achieved using the back-end to generate the PDF and send it. What is left on the mentor app team's side is to edit the email modal and send a flag along with the lifemap to the server once the user syncs the draft.

Testing will require coordination with the backend guys as our part alone just sends a flag, not an email.

## Assumptions
- The user press the email button, the app will store a flag "sendEmail" along with the draft data to send it later in the sync process
```javascript

{
  draftId: 'example-draft',
  achievements: [],
  familyData: {},
  // ...
  sendEmail: true
}
```
- After the button is pressed the app shows a modal with the following text in English and Spanish: `Your Life Map will be sent to your email as soon as the survey is synced. Click "Close" to finish the survey!`, `Tu Mapa de Vida será enviado a tu correo cuando tu encuesta esté sincronizada. ¡Selecciona "Cerrar" para terminar la encuesta!`
- When the app syncs the draft, the server will check the "sendEmail" flag and send the lifemap if this flag was set to true.
- When the above is implemented there is no way to test if any email is sent before the backend guys complete their part. We will need to coordinate on this.

## Out of scope
- We don't generate the PDF in the app and store it while waiting for wifi connection
- The app doesn't send any PDF via email
- Any additional UI change except the email button not appearing when there is no email and the modal which shows after clicking it is out of scope

**Comment by diegotorrespy** [comment]
@Danman7 @aprojas @kranelox 

That is exactly the behaviour that we are expected in the server ! thanks for clarifying the specs Dan!
We have already start the changes in the back end to support this feature. As soon as we got them deployed in the testing environment we will comment in this thread.

**Comment by diegotorrespy** [comment]
@Danman7 @kranelox 
The new field `sendEmail` is already available in the `testing` environment to be integrated with the app.

**Comment by vasildimitroffhristoff** [comment]
@diegotorrespy the **sendEmail** field was added  and sent with the Draft as discussed , but no Email was received. 

**env** Testing

The following is the Draft data which we are sending to the server: 

```
{
    "query": "mutation addSnapshot($newSnapshot: NewSnapshotDTOInput) {addSnapshot(newSnapshot: $newSnapshot)  { surveyId surveyVersionId snapshotStoplightAchievements { action indicator roadmap } snapshotStoplightPriorities { reason action indicator estimatedDate } family { familyId } user { userId  username } indicatorSurveyDataList {key value} economicSurveyDataList {key value multipleValue} familyDataDTO { latitude longitude accuracy familyMemberDTOList { firstName lastName socioEconomicAnswers {key value } } } } }",
    "variables": {
        "newSnapshot": {
        	"sendEmail": false,
            "surveyId": 12,
            "created": 1557477303107,
            "draftId": "816d3bb0-72fe-11e9-9aac-55b31dca377",
            "economicSurveyDataList": [
                {
                    "key": "areaOfResidence",
                    "value": "OTRO",
                    "other": "Getho"
                }
            ],
            "familyData": {
                "familyMembersList": [
                    {
                        "firstParticipant": true,
                        "socioEconomicAnswers": [],
                        "birthCountry": "PY",
                        "firstName": "Hauss",
                        "lastName": "Max",
                        "gender": "O",
                        "customGender": "Tree",
                        "birthDate": 1391731200,
                        "documentType": "6",
                        "customDocumentType": "Note",
                        "documentNumber": "2",
                        "email": "vasildimitrovhristo@gmail.com"
                    }
                ],
                "countFamilyMembers": 1,
                "country": "PY",
                "latitude": 42.6942057,
                "longitude": 23.3224726,
                "accuracy": 19.09600067138672
            },
            "status": "Draft",
            "achievements": [],
            "priorities": [],
            "indicatorSurveyDataList": [
                {
                    "key": "familySavings",
                    "value": 3
                },
                {
                    "key": "garbageDisposal",
                    "value": 2
                },
                {
                    "key": "dentalCare",
                    "value": 2
                },
                {
                    "key": "eyesight",
                    "value": 3
                },
                {
                    "key": "separateBedrooms",
                    "value": 2
                },
                {
                    "key": "properKitchen",
                    "value": 3
                },
                {
                    "key": "safeBathroom",
                    "value": 3
                },
                {
                    "key": "electricityAccess",
                    "value": 3
                },
                {
                    "key": "road",
                    "value": 3
                },
                {
                    "key": "capacityToPlanAndBudget",
                    "value": 3
                }
            ]
        }
    }
}
```
