### ISSUE TITLE
Upload offline map for Chortitzer Paraguay

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#877]
The local partner of Paraguay, Chortitzer, needs an offline map for their survey.

Offline map: Loma Plata
https://www.google.com/maps/place/Loma+Plata/@-22.3733411,-59.8480616,13.67z/data=!4m5!3m4!1s0x9471f802ffee4035:0xd3da5271a3d9c1c2!8m2!3d-22.3744575!4d-59.8295234

**Comment by stacylorraineprendeville** [comment]
@aprojas can you make sure this is stated earlier...we already began the sprint.

**Comment by aprojas** [comment]
It works properly @JDelPuerto
