### ISSUE TITLE
Question missing in Education for Spanish and English demo

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#880]
Device: Samsung SM-T560
Version: 1.9.13
Environment: Testing
Connection: Online
Logged in as: t/demo - demo

Steps:
Create a survey
Choose English Demo - Spanish demo
Go to Education section

Expected Result: 
To show the questions regarding Education

Actual Result:
The question "Currently studying" in English demo is missing
The question "¿Actualmente estudia?" in Spanish demo is missing
Only shows the radio buttons "yes, no, I prefer no to answer"

![Screenshot_2019-07-09-17-27-30.png](https://images.zenhubusercontent.com/5c48c8dbf88
3486cde30d849/169a9607-f990-48b6-a47f-4705aee6caf1)

**Comment by stacylorraineprendeville** [comment]
@aprojas which survey?

**Comment by aprojas** [comment]
English Demo - Spanish demo
@stacylorraineprendeville
