### ISSUE TITLE
App crashes in "Open" in Google Play Store

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#886]
Previously, I was logged in in the app with t/demo, in the 1.9.13 version
Then,
I downloaded the latest version of the internal test track 1.9.14 in my device 
When it finished downloading, I clicked on the "Open" button
The app did not even open, it directly crashed. 

Connection: Online
Device: Samsung SM-T560

We tried this with Edu's phone (his email is also in internal test track) and it did work properly, he downloaded and the app opened. 

It looks like it is only my device. And it is NOT sending any sentry errors. 

![Screenshot_2019-07-09-17-40-12.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/7e6adc13-8858-4e8f-a3f2-0e2ff4b04c05)

**Comment by stacylorraineprendeville** [comment]
@aprojas what memory and hard drive space do you have available on this device?

**Comment by aprojas** [comment]
Is this what you need? @stacylorraineprendeville 
![Screenshot_2019-07-10-09-32-59](https://user-images.githubusercontent.com/44477708/60973015-5a77d200-a2f5-11e9-9398-d85c8aa9a269.png)

**Comment by vasildimitroffhristoff** [comment]
@aprojas on the modal with the crashing message click on report and there you will find various tabs. In one of the tabs you will get stacktrace. Please make a screenshot of that one.

**Comment by zommerberg** [comment]
I think this is directly related to #888
