### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#89]
Currently languages are mixed on the page - i.e. When a user moves into the spanish view they are presented with english text

**Comment by stacylorraineprendeville** [comment]
@Danman7 Again - I know you already know about this - but it is so we have all issues in one place.

**Comment by stacylorraineprendeville** [comment]
@pA1nD Have you arranged for the translations?

**Comment by pA1nD** [comment]
Things that are still to be translated @Danman7 :
- [ ] Navigation
- [ ] Countries
- [ ] Dates generated by moment
