### ISSUE TITLE
Indicator Page Design Responsiveness and functionality

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#90]
This is heavily related to the lack of responsiveness of certain elements on the page as reported in
https://github.com/FundacionParaguaya/MentorApp/issues/55
As the individual indicator images are NOT stretching to the height of the screen then we see a all three indicators on the page.
This in turn means that the green "selector" button is NOT functioning (It would not be clear with the design being presented in this way to which indicator it would be selecting)
The correct function is that in a portrait device only ONE indicator is visible as the MAIN image - A user can see that other indicators are available but the focus of the screen should be on ONE indicator - Thus the correct use of the swipe.

<img width="488" alt="screen shot 2018-12-03 at 08 51 50" src="https://user-images.githubusercontent.com/45012899/49372382-327a1d80-f6d9-11e8-82d8-1492b4239f1d.png">

**Comment by stacylorraineprendeville** [comment]
@Danman7 Of all the issues with design and responsiveness - this one is the biggest issue.

**Comment by pA1nD** [comment]
@stacylorraineprendeville can't access the link as it's in your gmail!

**Comment by stacylorraineprendeville** [comment]
@pA1nD aiesh! perdon....really struggling to test properley with my set-up here - picture is in as a screen grab now.......if the indicator image is not responsive and does not occupy the full screen then the green tick circle does not function - because the user has no idea which indicator it refers to as sometimes the position is 50/50 between two.....

**Comment by stacylorraineprendeville** [comment]
OK @IvaKop - I have moved to a new larger device - and am still having issues with the responsiveness on indicators - Also this is being reported by the internal team.
The issue is we do not scale to height. See the two images below - Portrait version does not scale to 100% height - neither does it centre align the green indicator
Landscape version does not decrease sizing to respond to the height forcing the user to scroll on each indicator to view both text and image.....
![screenshot_20181210-200453](https://user-images.githubusercontent.com/45012899/49759813-022b1400-fcc3-11e8-9390-625b8a24de94.jpg)
![screenshot_20181210-20221](https://user-images.githubusercontent.com/45012899/49759818-02c3aa80-fcc3-11e8-91c9-259c85073ab3.jpg)
