### ISSUE TITLE
Achievement Popup when selecting a yellow indicator

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#902]
Version: 1.9.14 of Internal test track
Environment: Testing
Connection: Online
Logged in as: t/demo - demo

**Steps:**
Choose any survey
Go to lifemap Section
Choose a yellow indicator to create a priority

**Expected Result:**
Popup the "priority" questions to complete a priority. If I have a yellow indicator I might want to create a priority, not only when it is red. 

**Actual Result:**
The Popup to create an "achievement" is displayed. 
This should only happen when the retaking a survey is available, when a green changes to a yellow. 

![Screenshot_2019-07-15-09-43-08.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/bfcf07a7-4e3f-4c7f-926a-5fb47b221776)

**Comment by Danman7** [comment]
Fixed in a pull request.
