### ISSUE TITLE
Text amendments in new screens

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#903]
Change these texts:

1. 
Change: Crear prioridades!
To: ¡Crear prioridades!
![Screenshot_2019-07-15-09-42-40.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/6c769398-0956-4ebd-b789-3226d1993943)

2. 
Change: Tu Has Creado un Mapa de Vida.
To: Has creado un Mapa de Vida.
![Screenshot_2019-07-15-09-42-29.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/91bbdf3c-6dc1-4444-b017-f7004c707795)

3. 
Change button: Marca el logro!
To: ¡Marca el logro!
![Screenshot_2019-07-15-09-43-08.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1896bfbb-e855-48a1-96d5-a4589150dbfc)

4. 
Change button: Hacer una prioridad.
To: ¡Hazlo una prioridad!
![Screenshot_2019-07-15-09-42-56.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/cfced4c3-7f51-4958-85dd-da366b6d6c02)

**Comment by stacylorraineprendeville** [comment]
@aprojas the text should never have been "create priorities" - @zommerberg can you please go back to the initial issue - read the comments and add the correct text
