### ISSUE TITLE
NoClassDefFoundErrorcom crash on Location screen

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#906]
Sentry reports: https://sentry.io/share/issue/5bfc49ca3d1e4579923da1b77331e3a4/, https://sentry.io/share/issue/bc51238de0af41c3b7b1d17f9e91a9e8/

There is a crash reported on old KitKat devices. It appeared after `1.9.14` so it's possibly related to MultiDex.

Reading: https://github.com/nitaliano/react-native-mapbox-gl/issues/775, https://github.com/mapbox/mapbox-gl-native/issues/13844

**Comment by vasildimitroffhristoff** [comment]
We assume that that was fixed with updating the Mapbox library
