### ISSUE TITLE
Undefined familyData.countFamilyMembers in socio economic questions

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#907]
Sentry reports: https://sentry.io/share/issue/d905479c6ee54ee599c21d14ea647580/, https://sentry.io/share/issue/7141e141d8df4c799cdfa27205c70304/

**Comment by Danman7** [comment]
Connected to #912

**Comment by pA1nD** [comment]
We assume this will be fixed by #958

**Comment by Danman7** [comment]
Issue is fixed by refactoring.
