### ISSUE TITLE
Ongoing Edition Issues

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#91]
This issue will contain a list of all issues related to spelling and grammar. The idea is to create a checklist the we can grey out once the amend has been made.

- [x] Skipped Questions Page - Page title is Skipped Questions - Not "thank you"
- [x] life map is written Life Map
- [x] Spelling on page - Begining of life map (after socio economic) "approximately"!
- [x] Location page in life map process - "Country" to change to "Country of residence"
- [x] Number 1 of Terms & Conditions - No space between 1 and the full stop

**Comment by pA1nD** [comment]
@stacylorraineprendeville could not find or understand the not checked ones.

**Comment by stacylorraineprendeville** [comment]
Spelling on page - Begining of life map (after socio economic) "approximately"!

this spelling error has not been corrected @IvaKop

**Comment by stacylorraineprendeville** [comment]
@pA1nD I have changed this in the latest pull request....
