### ISSUE TITLE
no padding bottom 

### ISSUE THREAD

**Issue by zommerberg** [FundacionParaguaya/MentorApp#914]
we need to add padding bottom on every page, because it looks bad without padding(stuck to the bottom) on some devices

**Comment by zommerberg** [comment]
@stacylorraineprendeville  could you tell me on witch screen the app was looking bad on landscape mode on a Tablet? i cant find a padding problem on the office tablet.

**Comment by stacylorraineprendeville** [comment]
@zommerberg We looked at it together - any mobile in portrait with a full family screen is an example - though this should be a generic style for all content to have some padding from the botton

**Comment by zommerberg** [comment]
can i get example screenshots ? @stacylorraineprendeville

**Comment by zommerberg** [comment]
The issue is about the content going down and expanding on horizontal tablets.
This is a normal behaviour.
