### ISSUE TITLE
Missing Close Icon in Life Map Creation

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/MentorApp#92]
I can't simply exit a draft, and would have to click "back" through all the screens. 

This is because the exit option is missing from the top right of the header.
Please add the X option and revert the user to the correct exit message (UX will specify this)

<img width="239" alt="screen shot 2018-11-26 at 18 36 31" src="https://user-images.githubusercontent.com/45012899/49044433-830aeb80-f1ac-11e8-901d-b53fb6f1e6d9.png">

**Comment by stacylorraineprendeville** [comment]
@gigerbytes I added a different description and the image - This is definitely what you refer to correct?
