### ISSUE TITLE
No Connection message flashes and is removed without interaction

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#936]
## Problem

When offline - User tried to login
No connection message with retry button appears - flashes and user is redirected to the userlogin page

## Solution
No connection message should remain until user interacts with screen - clicking on retry button

**Comment by vasildimitroffhristoff** [comment]
Duplicate of #949

**Comment by Danman7** [comment]
@stacylorraineprendeville This is heavily related to the duplicate issue and will be fixed with it.
