### ISSUE TITLE
Error screen "we are having problems downloading offline maps" when exiting draft

### ISSUE THREAD

**Issue by vasildimitroffhristoff** [FundacionParaguaya/MentorApp#949]
**1st time:**
_OFFLINE
User: d/geco_
I took a new survey, after the location screen, in the **first** socioeconomic screen, I exit the survey to save it as a draft, and the error screen "**we are having problems downloading offline maps**" appeared for 3 seconds, and then my main dashboard showed.

**2nd time:**
_OFFLINE
User: d/aprojas_
I took a new survey, after the location screen, in the **first** socioeconomic screen, I exit the survey to save it as a draft, and the error screen "**we are having problems with your connection**" appeared for 3 seconds, and then my main dashboard showed.
![Screenshot_2019-07-24-08-57-41](https://user-images.githubusercontent.com/44477708/61796787-2374e680-adf4-11e9-8624-3acef5296be7.png)

**3rd time:**
_ONLINE
User: d/geco_
I took a new survey, after the location screen, in the **first** socioeconomic screen, I exit the survey to save it as a draft, and the loading screen appeared, starting to cach images again, and when it finished loading, my main dashboard showed with the draft. 
![Screenshot_2019-07-24-09-24-37](https://user-images.githubusercontent.com/44477708/61797055-aeee7780-adf4-11e9-8e05-a198fe5d7039.png)

**4th time:**
_ONLINE
User: d/geco_
I took a new survey, after the location screen, in the **second** socioeconomic screen, I exit the survey to save it as a draft, and it works with no problem. 

**5th time:**
_OFFLINE
User: d/geco_
I took a new survey, after the location screen, in the **second** socioeconomic screen, I exit the survey to save it as a draft, and it works with no problem. 

**6th time**
_OFFLINE
User: t/nelixiademo_
I took a Nelixia survey, exited the survey in a socioeconomic screen to save a draft, and the the error screen "**we are having problems with your connection**" appeared, and it was showing the loading screen on and off with the error screen, even though I tried clicking "retry" nothing happened. I had to connect to wifi, and then the loading screen started loading with no problem. It took me to the main screen and the draft was there.

**Comment by pA1nD** [comment]
Version used: 1.9.15 (internal test track).
Always the same survey used.
