### ISSUE TITLE
Inconsistent Rollover behaviour - Globally throughout App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#95]
- [ ] Globally throughout the app we have a transition on rollover which is equal to a fadeout - This is the opposite of the specification which is that colours become more intense. Colour settings for buttons on active/rollover can be found in the invision page
The standard green button for continue for becomes the darker green see below:

![Screen Shot 2019-02-06 at 15.17.30.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/f4aea744-6590-45a5-8300-b79f442f730c)

- [ ] The above issue is also present on the indicators page - a fade out on select.
Again we want to make it more prominent to denote it has been selected. The original spec was the circular button highlight
![Screen Shot 2019-02-06 at 15.22.25.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/99364cf3-ec36-4fca-920e-64c212b404f2)

- [ ] Choose Survey Page - Again when you choose a survey we have a fadeout - However better would be the background to increase density of colour - as below - this is also the case on the indicators page.
![Screen Shot 2019-02-06 at 15.24.55.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/5feb2815-0f3b-48b8-a9b6-17d280d601d5)
This is one of the new colours: F3F4F6

**Comment by Danman7** [comment]
The state of the Find a family button from your image is different from the one I have in inVision:
<img width="676" alt="screenshot 2019-02-13 at 11 33 24" src="https://user-images.githubusercontent.com/3336245/52701602-4668b800-2f83-11e9-8a99-5a32acb34c49.png">
My guess is that, we do the darker text color, not the grey background.

**Comment by Danman7** [comment]
`* The above issue is also present on the indicators page - a fade out on select.
  Again we want to make it more prominent to denote it has been selected. The original spec was the circular button highlight`

@stacylorraineprendeville So if there is no circular button now, what's the proper behavior?

**Comment by stacylorraineprendeville** [comment]
The circular area with the tick mark that appears when you have chosen the indicator is that which should appear on touch (minus fade out)
