### ISSUE TITLE
Chosen stoplight indicator not showing when changing socioeconomic answer

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#950]
I think this is not a bug, but it is a feature that should not have been implemented this way. 
I reproduced this being offline and online.

When already in the stoplight indicator section I chose some level greens, yellows and reds - 
I went back to the socioeconomic to change one of my answers
Then I moved forward again to the stoplight indicator section
I could not see any of my chosen levels I had picked before going to the socioeconomic question.

This happens everytime I go BACK to the socioeconomic section, not only if I change an answer.

**Comment by aprojas** [comment]
With d/geco:
I tested this after updating the app in the latest internal test track release 1.9.15, and it's still happening. 
@Danman7 

This ALSO happens in the production environment with the Activate survey.

**Comment by pA1nD** [comment]
We assume this will be fixed by #958

**Comment by Danman7** [comment]
This was a bug, firmly fixed in #958
