### ISSUE TITLE
Inconsistent Text sizes in Form Labels

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#96]

**Comment by stacylorraineprendeville** [comment]
- [ ] Form input fields have different text sizes - e.g. "gender" is a different size to "First name" for instance

- [ ] Spacing within text elements is incorrect - no padding is given to the top in the activated state. Please refer to invision

- [ ] Styling on dropdown elements to be improved for first release in the best way possible - Version on the left is seen as minimum - version on the right -optimum
<img width="866" alt="screen shot 2018-11-15 at 11 55 40" src="https://user-images.githubusercontent.com/45012899/49050221-14845880-f1c1-11e8-8521-cc048380e8dc.png">

**Comment by Danman7** [comment]
I see the difference in label sizes. But just in case @stacylorraineprendeville can you tell me the android version of the device you are using as the screenshots look nothing like both of my real devices.

**Comment by stacylorraineprendeville** [comment]
The screenshots Dan are the designs in Invision.

The device is a Samsung Galaxy Tab A6
