### ISSUE TITLE
Add check for "Out of memory" when user is downloading resources

### ISSUE THREAD

**Issue by vasildimitroffhristoff** [FundacionParaguaya/MentorApp#966]
Add check for "Out of memory" when user is downloading resources and show notification

**Comment by pA1nD** [comment]
For now on hold, as it seems lower priority.

@vasildimitroffhristoff found, that there are multiple alerts shown by the device that the system is running out of space. This should be enough to make the user aware.

**Comment by vasildimitroffhristoff** [comment]
This issue will be resolved in #631
