### ISSUE TITLE
Validation on day and year of birth date

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#97]
- [x] Validation of Day and Year in the dropdown its delayed - An error message only appears when the user clicks on the next input field - When the user clicks on the next field it hides the invalid message - thus creating a usability issue

- [x] Validation on year is incorrect - This allows any number even those such as 4444

**Comment by Danman7** [comment]
Fixed in bc3de4e0056683b1f76b80a0d987dcc12b742a09, 51a90514a2cb503714bf97c8ce332388430593d9, 21c9fb309919c58122c3a618900d32884050d00c

**Comment by stacylorraineprendeville** [comment]
Hi Iva
1. When I say next input field - I mean when you add a date and go directly to the next input field - (in this form the next input field is Document Type).
e.g So I enter a date 4444 and then click directly to the input field "Document type" - I am allowed then to choose a document type - this brings up a dropdown so effectively I do not see the validation error of the date- Does this make sense now?
It would be better that users are informed at the time they commit a mistake so that they verify immediately before proceeding to the next step. How can we enforce this? If in day we have the first numerical character over the number 3 then can we generate the error message immediately?

2.For validating the Year - Can we validate number by number obviously the first numerical character can only be 1 or 2 the second can only be 9 or 0 - Is this possible? (I do not try to push this for launch next week but long term the form usability will need to be reviewed and reviewed, we could take several iterations to have top usability) . In this instance if I type 4 as the first character of the year could we generate the error message immediately?

**Comment by stacylorraineprendeville** [comment]
@IvaKop We also need this to restrict in the day 01 - 31

**Comment by stacylorraineprendeville** [comment]
@IvaKop Some users are stating they prefer the dropdown for all elements - For me I do not like long year scrollers - but I am wondering whether indeed it may alleviate these validation issues and would like to know what the team think....your thoughts?

**Comment by IvaKop** [comment]
Hi @stacylorraineprendeville , I found a tiny bug in the navigation and fixed it already so the validation now works as expected but we can switch to dropdowns if this is what the users need.

**Comment by stacylorraineprendeville** [comment]
I do not think that people are clear enough about what they want (some people want the date picker) and it is very subjective. For now lets not complicate further.
Sierra Leone report that they can use numbers like 51 in the date for primary participant and for additional family members - I am presuming this is because this issues update is not yet in the app - correct? @IvaKop

**Comment by IvaKop** [comment]
@stacylorraineprendeville ok, then we leave it as it. The day issue will be fixed with the next update, yes.
