### ISSUE TITLE
Download screen went to 200%

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#972]
When I logged in with a demo user,
user: d/Nelixia Demo
password: Nelixiademo

The loading screen went up to 200% when caching the images.
![Screenshot_2019-07-25-10-52-18.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/fd743fcf-7d61-43aa-b952-7dfe7d39ad8f)

Then, the main screen appeared BUT with some numbers above the Green, Yellow and Red titles. Even though there were no surveys taken with this account yet.

**Comment by zommerberg** [comment]
closed in #967
