### ISSUE TITLE
Missing images in Activate survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#973]
Connection: Offline and online
Survey: Activate FUPA
Version: 1.9.15
Environment: Production
User: aprojas

Problem: I was taking a survey, and when I got to the Stoplight indicators section, especifically in the indicator "Formar parte de un grupo", 1 of the images was cut in half and the rest of the stoplight images did not appear. 
I tried reproducing this error 2 times, one offline and one online. 
I checked in the web platform, and all of the images were there, so this only happened in the mobile app.

When I logged in with the user, there was no crash, I saw that all of the images loaded to 100%, so they were not supposed to be missing.

Screenshot:
![Screenshot_20190725-155957.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/33258c9a-0f0c-4304-bbce-3d434cde6064)

**Comment by pA1nD** [comment]
@aprojas can you still reproduce this?

**Comment by aprojas** [comment]
This doesn't happen anymore! @pA1nD
