### ISSUE TITLE
Missing numbers in Reds, Yellows, & Greens

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#974]
Connection: Online
Environment: Testing
Version: 1.10.0
User: t/demo

I logged in with t/demo-demo, and in the main screen, I cannot see the numbers of the reds, yellows and greens. They are not loading. 

![Screenshot_2019-07-25-16-18-36.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/4ad40a6d-235e-44d7-bf7a-49e7a9abc722)

**Comment by Danman7** [comment]
@aprojas This is a feature requested by @stacylorraineprendeville and completed during spring in #928
