### ISSUE TITLE
When Online showing another location

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#975]
Connection: Online
Environment: Testing
Version: 1.10.0
User: t/demo
Survey: UK SHORT DEMO

I was online, and in the location screen, I saw Gateshead location (in the UK). It should have shown Paraguay. Also, it only showed my real location after clicking on the green location icon twice. 

![Screenshot_2019-07-25-16-26-08.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/51cc561a-296d-40c8-bb71-8d685001fb40)

**Comment by Danman7** [comment]
Duplicate of #865
