### ISSUE TITLE
App crashed after location screen in UK SHORT DEMO

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#976]
Connection: Online
Environment: Testing
Version: 1.10.0
User: t/demo
Survey: UK SHORT DEMO

When I clicked on continue on the location screen, the app crashed. It should have gone directly to the Stoplight indicator section, not through a socioeconomic section.

Sentry error: TypeError - ctor(src/screens/lifemap/SocioEconomicQuestion)

**Comment by pA1nD** [comment]
Sentry here: https://sentry.io/organizations/poverty-stoplight/issues/1118973148/

**Comment by vasildimitroffhristoff** [comment]
This issue is already close in #891
