### ISSUE TITLE
Wrong character for thousand position

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#977]
Internal test track: 1.9.10
Connection: offline
User: t/demo

Please correct:
When in English language, the separator has to be COMMAS (,)
When in Spanish language, the separator has to be PERIODS (.)

I found it the other way around. 

![Screenshot_2019-07-25-16-44-40.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/fc0e69c3-3b45-45aa-afa0-7dfbeb4620c9)

**Comment by zommerberg** [comment]
In the feature  we will remove the possibility to change the language in the survey.
In order to test this - select the language before opening the survey, navigate to socialeconomics and check if it is commas or dots. the exit the survey ,change the language and try again.

**Comment by aprojas** [comment]
It still shows commas even though I choose SPANISH from the beginning, before choosing a survey. 

![Screenshot_2019-07-26-15-11-46.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/099c58fb-7588-49ef-86d3-b2751e3a7b7a)

@zommerberg

**Comment by aprojas** [comment]
The app still allows me to change the language in the middle of a survey. Is that the behaviour it should have? @zommerberg

**Comment by stacylorraineprendeville** [comment]
@aprojas should be that the navigation bar is now disabled when within a survey - Does this have a ticket @pA1nD ?

**Comment by pA1nD** [comment]
You can track progress here: https://github.com/FundacionParaguaya/MentorApp/issues/997

(already merged and will be deployed today)
