### ISSUE TITLE
Cannot enter Second First name

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/MentorApp#98]
In participant screen, I cannot add a second name to the first name field (because some people have 2 first names).

Reason is the <space> character is not "alphanumerical". The solution would be to allow the space character as well.

**Comment by Danman7** [comment]
I can freely enter spaces in both primary participant and family members screens. Looks like it's fixed here d1b41eabbb97e38a21c030ec2c3b9f9f350e9675
