### ISSUE TITLE
Wrong location shown even if online

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#985]
Connection: Online
Environment: Testing
Version: 1.10.0
User: t/demo
Survey: Paraguay - Chortitzer

I was online, and in the location screen, I saw the Guatemala city map. It should have shown Paraguay, my location. 
This is different from the #975 issue because in this one, I saw another country's map, in the other issue, I saw the map belonging to that survey's country.

![Screenshot_2019-07-26-08-39-36.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/bd21500b-1610-4a2c-8d98-3f5fa202f5a2)

**Comment by Danman7** [comment]
This will be resolved wil #865 as well.
