### ISSUE TITLE
Cannot save draft for Demo surveys

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#992]
Version: Internal test track 1.10.0 rc2
Connection: Online
Surveys: 
1. Stoplight Demo - English
2. Stoplight Demo - Spanish

I cannot save the draft in any screen, even if I include names, I click on the X button to save a draft, and when I click on "Save draft", I cannot see that survey in the main screen saved as a draft.

**Comment by stacylorraineprendeville** [comment]
@vasildimitroffhristoff It would need to save with a generic name and surname - correct?

**Comment by vasildimitroffhristoff** [comment]
This one will be solved in #781
