### ISSUE TITLE
Cannot click finish on a Demo survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#993]
Version: Internal test track 1.10.0 rc2
Connection: Online
Surveys: 
1. Stoplight Demo - English
2. Stoplight Demo - Spanish

When I'm taking a survey and arrive to the final screen to close and save it, the button to save the survey disappeared. 
This happens in any scenario, if I make priorities or not.
 
![Screenshot_2019-07-26-15-15-04.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/58298b1c-41f2-4a58-b227-42126ec9cbea)

**Comment by Danman7** [comment]
This is a feature. It was requested this way.

**Comment by stacylorraineprendeville** [comment]
No - we thought about this as an option because of the back end requirements - but it was discussed in standup while I was in Bulgaria - seemed not ness as the back end was already set up @danman7

**Comment by vasildimitroffhristoff** [comment]
Will be solved in #992
